const contents = {
    market:{
        name1:"外汇市场：当代发展最快的金融市场",
        name2:"",
        content:[
            "一、外汇市场与期货及股票市场的比较",
            "并不单单是在线外汇交易的兴起促进了整个外汇市场的成交量。随着外汇市场在过去数年波动性的提高，许多交易者也日益意识到外汇市场波动将影响股票市场和债券市场。因此，如果股票、债券和商品交易者们想要做出明智的交易决策，就必须追踪和考虑外汇市场的变化。下面是一些外汇市场波动影响股票和债券市场的历史实例。",
            "欧元/美元汇率与公司利润",
            "对于股票交易者，特别是投资那些大量出口美国的欧洲公司的交易者而言，密切关注汇率的变化对于预测公司的收益和利润状况是非常重要的。自从2003年开始，欧洲的制造商们就大肆抱怨欧元的升值和美元的贬值。导致美元走软的罪魁祸首是美国快速增长的贸易赤字和预算赤字，也就是所谓的“双赤字”问题。这个问题导致欧元兑美元汇率飙升，而这又使得欧元区出口给美国消费者的商品变得更加昂贵，最终导致欧元区公司的利润下降。在2003年，由于德国大众公司没有进行充分的汇率对冲，造成了大约10亿欧元的利润损失，而荷兰国家矿业公司，这家化工集团则警告说欧元兑美元汇率变动百分之一会导致公司利润损失700万到1100万欧元。不幸的是，不充分的汇率对冲在2008年的欧元区仍旧是一个普遍存在的问题。因此，密切关注欧元兑美元的汇率变化对于预测欧元出口商们的收益和利润水平是极其重要的。",
            "日经指数和美元",
            "参与日本股票的交易者们也需要注意美元走势的变化，以及美元走势如何影响日经走势的涨落。日本最近已经经历了长达十年的经济停滞。在这期间，美国的共同基金和对冲基金大幅减持了日本股票。当日本经济开始复苏的时候，这些基金争抢着入场，他们对自己的投资组合进行了调整，以免错失掉日本经济复苏带来的投资机会。对冲基金借入美元以便买入日本股票，增加持有的日本股票敞口。不过，这样做却使得他们对于美元利率变化极端敏感，对于美联储货币政策是否进入紧缩周期非常敏感。美元借贷成本的上升会打击日经指数的上扬走势，因为更高的利率会提高美元贷款的融资成本。美国经常拥有巨大的项目赤字，美联储为了维持和增加美元资产的吸引力就必须持续提高利率水平。因此，持续的加息伴随着日本经济的低速增长或许会使得基金过度融资买入日本股票的行为变得无利可图。因此，美元的变动对于日经指数的涨跌具有重要的影响。",
            "二、外汇市场与期货及股票市场的比较",
            "传统意义上来说，外汇市场并不为大众所追棒，因为管制、资本要求和技术等方面的原因，使得最初能够参与外汇市场的主体被局限于对冲基金和商品交易管理顾问基金这类管理大量资金的金融机构，以及大公司和其他机构。传统的外汇市场之所以被局限于这些大型机构，主要原因是交易者承担的风险完全是个性化的。换言之，一个交易者可能采纳了一百倍的杠杆，而与此同时另外一个交易者却没有采用任何杠杆。但是，最近几年许多公司开始向散户(零售小额交易者)提供进入外汇市场的途径。这些公司向散户交易者提供交易融资和杠杆，免费的即时执行交易平台、行情图表和实时新闻等。这就使得外汇作为可选的交易标的的吸引力大大上升了，而外汇交易也因此变得大众化。<br><br>许多股票和期货交易者已经将外汇加入到他们的交易对象池中，或者转向只交易外汇。之所以出现了这样的趋势，是因为这些交易者开始意识到外汇与股票和期货相比具有更多的吸引力。</p>",
            "外汇与股票比较",
            "外汇现货交易与证券股票交易相比具有如下区别：",
            "外汇市场的主要特征",
            "外汇市场是全球最大的金融市场，并且成交量和流动性还在不停地增长。",
            "外汇市场是全天候的24小时交易市场。",
            "交易者既可以从上涨走势中赚取利润，又可以从下跌走势中赚取利润。",
            "不存在交易限制。",
            "立即执行的交易平台最小化了成交滑移点差和错误。",
            "即使存在更高交易杠杆带来更高风险的问题，许多交易者仍旧认为外汇市场是一个“物有所值”的市场。",
            "股票市场的主要特征",
            "市场流动水平一般，主要依赖于股票日成交量。",
            "市场运行从纽约时间上午9:30持续到下午4点，盘后的场外电子盘交易时间存在限制。",
            "现有的成交和交割费用，以及佣金较高。",
            "存在上涨方能抛空的规则，也就是必须在上涨中卖空，这令日内交易者受到极大的制约。交易限制或许也对日内交易者产生了负面影响。",
            "完成交易涉及的步骤太多，以至于增加了成交滑移和错误的几率。",
            "外汇市场是全球最具流动性的市场，其巨大的成交量和极高的流动性允许交易者们能够以较低的交易成本和较高的杠杆参与其中。这是一个24小时运作的市场，无论牛熊市都能赚钱，错误率和成交滑移价差都被最小化，没有交易限制和上涨抛空的规定。交易者们可以运用与股票市场中采纳的一样的分析技巧来研究外汇市场。对于基本面交易者而言，可以像分析股一样分析国家，对于技术面交易者面言，外汇市场是一个使用技术分析的理想市场，因为专业交易者们已经在广泛地采用各种技术分析工具。为了更好地明白外汇市场为什么具有如此的吸引力，为什么如此值得我们去参与其中，我们应该更进一步深入地了解外汇市场的特征。",
            "外汇与期货比较",
            "外汇市场的主要特征",
            "它是全球最大的市场，并且流动性还在增长。",
            "24小时全天候交易。",
            "无论牛市还是熊市都存在获利机会。",
            "没有上涨方能做空的限制。",
            "即时执行的交易平台最小化了成交滑移价差和其他错误。",
            "虽然较高的杠杆水平增加了风险，但许多交易者则认为外汇市场带来了更高的潜在收益。",
            "期货市场的主要特征",
            "市场流动性有限，依赖于各月份交易合约的流动性。",
            "交易清算费用和佣金导致更高的交易成本。",
            "期货交易的开市时间短于现货外汇市场，并且取决于交易品种;每个交易品种或许有不同的开盘和收盘时间，盘后交易时间存在限制。",
            "期货的交易杠杆高于证券，但是远远不及外汇交易中可以运用的杠杆水平。",
            "通常情况下，期货市场中熊市持续的时间较长。",
            "场内交易的构架增加了成交滑移价差和其他错误的概率。",
            "正如股票市场上许多分析和交易策略可以运用于外汇市场一样，期货市场中的策略也可以运用到外汇交易中。绝大多数期货交易者都运用技术分析手段，正如之前在股票对比部分提到的一样，外汇市场是运用技术分析的理想场合。实际上，技术分析是职业交易者们运用最普遍的分析工具。",
            "三、外汇交易的不同途径",
            "外汇现货",
            "外汇期货",
            "外汇期权",
            "交易型开放式指数基金",
        ],
       
    },
    first:{
        name:"初识外汇——外汇基础知识",
        content:[
            "外汇交易员从来不会只买卖一种货币，市场运行的方式亦是如此。他们先卖出一种货币，再用这笔钱买进另一种货币。总之，货币不会被单独交易。",
            "思考一下，1美元值多少钱？难道是1美元？同样，1英镑价值1英镑吗？任何货币与自身价值比较都是没有意义的，只有当它们被组合成对的时候才能显现出价值。当你面对一个货币对的时候，你看到的不仅仅是两种货币还包括它们之间的比较。现在，你可以用另一种方式问刚才的问题，1美元值多少英镑呢？或者说，1英镑可以购买多少美元呢？",
            "将货币以成对的方式交易对新手来说是个难题，因为新手们已经习惯了买卖单一的股票或者销售单一的共有基金这种模式，货币对这一概念对他们而言还很陌生。所以，如果你还不能接受货币对的概念，别担心，还有许多人和你一样。我们保证你会逐渐熟悉。",
            "货币对",
            "在一组货币对中，左边的货币被称为基准货币，右边的货币被称为计价货币。有一个简单的方法可以让你分辨两者：基准货币的强弱决定了货币对的走势，而计价货币的强弱则决定了货币对的价格。",
            "例如，最常见的货币对是欧元/美元，其中欧元是基准货币，美元是计价货币。欧元对比美元的强弱程度决定了货币对升值或贬值。如果欧元比美元强势，那么欧元/美元就会升值，反之则贬值。下面是一个帮助你理解货币对变化的口诀：",
            "基准货币强，计价货币弱，则货币对升值；",
            "基准货币弱，计价货币强，则货币对贬值；",
            "计价货币强，基准货币弱，则货币对贬值；",
            "计价货币弱，基准货币强，则货币对升值。",
            "要记住，一个巴掌拍不响。基准货币和计价货币当中任何一方的变化都会影响整个货币对的变化。",
            "欧元/美元的价格表示购买1欧元需要支付多少美元。比如，欧元/美元的价格是1.3055，它表示购买1欧元需要1.3055美元。与之类似，如果货币对价格涨到1.4277，那就表示购买1欧元需要1.4277美元。",
            "那么，是谁决定把哪种货币作为基准货币，哪种货币作为计价货币的呢？答案很有趣一是国际标准化组织(ISO)。作为一个非政府组织，该组织致力于给混乱的世界带来一点秩序。",
            "货币对主要分为以下三种：",
            "主要货币对",
            "新兴市场货币对",
            "交叉货币对",
            "主要货币对",
            "主要货币对是指由美元和世界其他六大货币所构成的货币对，包括：",
            "欧元/美元( EUR/USD)",
            "美元/日元( USD/JPY)",
            "英镑/美元( GBP/USD)",
            "澳大利亚元/美元( AUD/USD)",
            "美元/瑞士法郎(USD/CHF)",
            "美元/加拿大元( USD/CAD)",
            "新兴市场货币对",
            "新兴市场货币对是指由美元和世界上其他主要货币构成的货币对。新兴市场货币之所以得其名是由于其较差的流动性，例如，瑞典克朗(SEK)、新西兰元(NZD)、南非兰特(ZAR)等等。但是随着新兴市场货币越来越普及，它们的流动性也在逐渐被改善。",
            "接下来，让我们看一看新兴市场货币对的列表，你可从中选择一些进行投资以扩充个人投资组合：",
            "美元/港币(USD/HKD)",
            "美元/瑞典克朗( USD/SEK)",
            "新西兰元/美元( NZD/USD)",
            "美元/新加坡元(USD/SGD)",
            "美元/挪威克朗( USD/NOK)",
            "美元/墨西哥比索( USD/MXN)",
            "美元/南非兰特( USD/ZAR)",
            "美元/丹麦克朗( USD/DKK)",
            "美元/泰铢(USD/THB)",
            "交叉货币对",
            "交叉货币对表示基准货币和计价货币都不是美元的货币对。例如，欧元和英镑，澳大利亚元和日元组成的货币对就是交叉货币对。 下面是一些常见的交叉货币对",
            "英镑/日元( GBP/JPY)",
            "欧元/英镑( EUR/GBP)",
            "澳大利亚元/日元(AUD/JPY)",
            "欧元/瑞士法郎( EUR/CHF)",
            "加拿大元/日元( CAD/JPY)",
            "货币对以基点为单位变化",
            "常做股票、证券或者商品期货交易的人习惯于用元和分作单位的报价。但是外汇市场却不是这样——货币对的价格单位是基点。",
            "什么是基点？基点的英文PIP是\"Price Interest Point\"的简称，即“价格兴趣点”。你也可以称它为“点”。在大多数情况下，一个基点代表了一个货币单位的万分之一。但是也有例外，比如，日元的一个基点代表了1日元的百分之一。一直以来，基点是外汇市场中最小的交易价格点，可是近来外汇交易商却开始使用更小的交易单位。最初，他们把“二分之一基点”用在欧元/英镑、欧元/瑞士法郎等货币对的交易上。后来随着交易量的扩大，一些交易商开始用“十分之一基点”作单位，也就是小数点后五位数。",
            "基点价值",
            "那么，一个基点价值多少？这个问题问得非常好，答案一般取决于几个因素。",
            "在股票交易中，股票涨或跌了多少钱可以直接换算成你赚或亏了多少钱。但是在计算每一个基点(或在某些情况下，每十分之一个基点)的价值时，你必须知道基准货币是什么，以及交易合约规模是多少才能计算。我们在第十二章讲解外汇市场的投资工具时会对合约规模做进一步说明，但是现在你只须知道标准合约包含10万个货币单位，而小合约包含1万个货币单位。有个公式可以帮助你计算出基点价值：",
            "(1个基点/汇率)X合约规模=基点价值",
            "让我们代入真实数据，假设你想知道一份美元/日元标准合约中1个基点的价值，并且已知美元/日元汇率为82.65，你可以代入公式计算出结果，表示如下：",
            "(0.01/82.65)×100000=12.10(美元)",
            "再举一例，假设你想知道一份欧元/美元小合约中1个基点的价值，并且已知汇率为1.3387，把数据代入公式，可得",
            "(0.0001/1.3387×10000=0.74699(欧元)",
            "当然，如果你想知道美元在不是基准货币的情况下的1个基点价值多少，你得在计算中多加一个步骤。为了把1个非美元货币的基点价值转换成美元的基点价值，你需要用到以下公式：",
            "基点价值×汇率=美元的基点价值",
            "在刚才欧元/美元的例子中，美元的基点价值为：",
            "0.74699×1.3387=1(美元)",
            "有了这个公式，你就能够计算出任何货币的基点价值。",

        ],
    },
    wave:{
        name1:"外汇波动的背后推手——什么在推动货币价格",
        name2:"",
        content:[
            "一旦我们知道了是什么东西创造出了自由货币市场，我们就能更好地理解今天是什么影响着货币的价值；而且对现实知道的越多，我们就能为未来做好准备。例如外汇，只有明白了它背后的操作模式才能更好地去拿捏利润的关键时刻。不浪费每一次获得财富的机会。",
            "一、贸易流",
            "贸易流表示由两国之间商品或服务的流通而产生的货币流，它一般会受到两种影响：",
            "外国对本国商品的需求",
            "本国对外国商品的需求",
            "外国对本国商品的需求",
            "外国对本国商品产生需求的同时，本国货币的需求量和外国货币的供应量通常也会相应增加。本国货币需求量的增加可使本国货币升值，而外国货币供应量的增加会使外国货币贬值。它的原理如下。",
            "假设一位西班牙顾客想要购买美国制造的某件产品。作为消费者，这位西班牙人会很自然地想到用欧元支付，但是美国却希望他用美元支付。为了让这桩买卖成功，西班牙顾客必须先把欧元兑换成美元后再付钱。",
            "这一兑换过程增加了市场上欧元的供应量，同时也助长了美元的需求量。这意味着欧元价值下降，美元价值上升。",
            "本国对外国商品的需求",
            "一般来说，本国对外国商品产生需求的同时，外国货币的需求量和本国货币的供应量也相应增加。外国货币需求量的增加使外国货币升值，而本国货币供应量的增加使本国货币贬值。",
            "在刚才的例子中，如果我们把美国和西班牙的角色对调，就能得到一个新例子，不过原理都相同。你要记住，在国际贸易中，当货币从买方流向卖方时，买方货币贬值，卖方货币升值。",
            "二、投资流",
            "投资流表示两国之间由一国投资者在另一国买卖资产而产生的货币流，它受三种因素影：",
            "外国对本国资产的需求",
            "本国对外国资产的需求",
            "资产遣返",
            "外国对本国资产的需求",
            "一般条件下，外国对本国资产产生需求的同时，本国货币的需求量和外国货币的供应量也相应增加。本国货币需求量的增加使本国货币升值，而外国货币供应量的增加使外国货币贬值。它的原理如下。",
            "假设一个日本投资者想购买新西兰政府债券。作为投资者，日本人很自然地想到用日元支付，但是新西兰政府却希望他用新西兰元支付。为了让这桩买卖成功，日本投资者必须先把日元兑换成新西兰元后，再把钱付给债券发行商。",
            "货币兑换增加了外汇市场中日元的供应量和对新西兰元的需求量，从而导致日元升值，新西兰元贬值。",
            "本国对外国资产的需求",
            "本国对外国资产产生需求的同时，本国货币的供应量和外国货币的需求量也相应增加。本国货币供应量的增加使本国货币贬值，而外国货币需求量的增加使外国货币升值。",
            "在刚才的例子中，如果我们把日本和新西兰的角色对调，就能得到一个新例子来说明这一点。在国际资产交易中，当货币从买方流向卖方时，一般来说，买方货币贬值，卖方货币升值。",
            "资产遣返",
            "资产遣返增加了本国货币的需求量和外国货币的供应量。本国货币需求量的增加使本国货币升值，而外国货币供应量的增加使外国货币贬值。",
            "三、货币供应量",
            "货币供应量是指一个国家发行的货币总量。这个概念似乎很奇怪，但是在今天这个法定货币(指没有任何实物资产作本位的货币)和计算机的时代，任何货币供应量的改变都可在瞬息间完成。政府的财政部门再也不必为了增加货币供应量而加印纸钞一一尽管他们也可以这么做。现在，他们只需在镜盘上敲几个键就能达到目的。",
            "一个国家的货币供应量对外汇交易员来说很重要，因为它对货币价值有直接影响。货币发行量越大，货币价值越低;货币发行量越少，货币价值越高。",
            "一国的货币供应量通常由以下部门或机构决定：",
            "政府财政部",
            "中央银行",
            "财政部在决定货币发行量中所扮演的角色",
            "我们在之前提到过，财政部控制了造币厂的货币印刷。鉴于法定货币没有实物资产作为货币本位，财政部只需命令造币厂准备好纸和墨并开动印刷机就能增加货币供应量。随着这些新印纸币的进入，货币供应量在真正意义上增加了。",
            "当然，如果这些纸币是用来代替破旧和损害的货币，市场中流通的实物货币数量就不会变化。在这里，你只需记住一点：开动一下印钞机的开关就能完成货币供应量的增加。",
            "中央银行在决定货币发行量时所扮演的角色",
            "目前，开动印钞机已经很容易了，但是中央银行能更轻易地增加或减少货币的供应量——他们要做的事只是在电脑中输入几个数字，然后按下回车键。实际上，中央银行每天都在印刷和销毁货币。下面我们将以美国中央银行—美国联邦储备局( Federal Reserve或Fed)为例说明。",
            "当美联储准备降息时，它会通过把短期抵押贷款(称“回购协议”)贷给一级交易商(大型银行)的方式来增加货币供应量。根据回购协议，美联储从各个一级交易商处借入美国国库券，并将其从对方储备账户中勾销。协议期满后，美联储将国库券归还给各个一级交易商，并将记入对方储备账户。",
            "当美联储准备加息时，它通过从一级交易商(大型银行)处购入短期抵押贷款(称“回购协议”)的方式来减少货币供应量。根据回购协议，美联储将美国国库券借给各个一级交易商，并将其记入对方储备账户。协议期满后，美联储收购各个一级交易商手中的国库券，并将其从对方储备账户中勾销。",
            "四、政府干预和货币操纵",
            "政府干预和货币操纵指的是政府通过其中央银行在外汇市场中采取的特定措施，使其货币价值上升或下降的行为。所谓的特定措施分为“直接干预”和“口头干预”两种。直接干预是指政府通过在公开市场买卖货币的方式操纵货币价值。口头干预是指政府单纯的口头警告，实质上不干预市场交易。在参与本国货币买卖时，政府理所当然地有很大的可能性去操纵货币。但是有时候仅靠警告就足以达到预期目标，政府根本无需投入大量资金。",
            "直接干预和口头干预有两种形式：协调干预和单边干预。协调干预是指多国政府以直接干预或口头干预的形式进行市场干预。单边干预是指一国政府单独参与货币操纵。",
            "从长远看，协调干预比口头干预更为有效。但我们可以肯定的是，单边干预在短期内能对市场产生巨大影响，只是效果不长久。 那么，政府为什么要干预市场？这是因为：",
            "担心货币走势过强",
            "担心货币走势过弱",
            "将本国货币钉住另一国货币",
            "担心货币走势过强",
            "为什么政府要担心货币走势过强？难道货币强势并不表示经济运行良，货币需求量大吗？政府似乎并不担心自己的货币走势强劲，除非出口受到影响。如果一个国家无法出口其产品和服务，那么就业岗位就会减少，公众会开始责怪政府，无奈之下，政府决定采取措施，这样一来，政客们也就能保住饭碗了。",
            "担心货币走势过弱",
            "为什么政府要担心货币走势过弱？难道货币疲软并不代表国家更容易出口产品和服务吗？",
            "的确是这样，但是货币贬值过多还是会引起政府的担忧，即使是那些拥有强势货币的政府也会担心其他货币的过度贬值会让全球经济雪上加霜。",
            "将本国货币钉住另一国货币",
            "一些国家和地区的政府——如中国、沙特阿拉伯、丹麦等——为了保持自身在全球金融市场中的稳定性，会将其货币钉住另一国货币，比如美元或欧元。",
            "将一种货币钉住另一种货币需要对外汇市场持续干预和操控。无论何时，只要被挂钩货币的需求量上升，政府就要采取卖出和（或）多发行挂钩货币的方式来增加其供应量，以稳定价格。",
            "五、投资者恐慌",
            "在外汇市场做交易时，你需要记住有一件很重要的事：外汇市场由许多像你这样的人组成。推动市场前进的最根本因素是人，所以人的情绪(尤其是恐慌)永远与市场同在。",
            "在今天的货币市场中，投资者恐慌是最大的影响因素之一。实际上，投资者恐慌太重要了，以至于它的出现会让影响市场的其他重要因素黯然失色。当经济危机发生时，它既可以让某些货币暴跌，也可以让某些货币飞涨。想要好好利用这一市场动态，你得先知道哪些货币可以在经济萧条时逆市繁荣。",
            "避险货币",
            "避险货币可以在投资者恐慌肆虐时繁荣。“避险货币”之所以得名是因为它们能在金融动荡时提供庇护。避险货币包括美元(USD)、瑞士法郎(CHF)和日元(JPY)。",
            "它们成为避险货币的原因各不相同。",
            "美元之所以成为避险货币是因为美国国债的安全性，它能在全球经济危机时吸引大量投资者。美国国债需求量的增加促使美元需求量也增加，从而使美元升值。毕竟，谁不希望自己手中的避险货币能在形势萧条时升值呢？",
            "瑞土法郎之所以会成为避险货币是因为市场上的大部分瑞士法郎都由黄金支持。虽然这个比例较从前有所下降，但相比其法定货币，瑞士法郎仍拥有相当稳定的黄金支持。同时，瑞土经济被认为是非常稳定的，它的通胀率通常很低。",
            "日元之所以会成为避险货币源于日本政府债券市场的稳定。不同于美国国债大部分由海外政府和投资者持有，绝大部分日本国债由本国私人投资者持有。这给日本经济增加了稳定性，同时也减少了日本政府为摆脱债务而实行通货膨胀政策的可能性——某些国家在债务负担过重时会这么做。通胀风险小的货币会更安全。",
            "测量投资者恐慌",
            "投资者的恐慌和信心非常抽象，由于缺乏统计的量化方法，人们很难去测量和分析它。然而，你可以根据一组数据来测量投资者恐慌，那就是芝加哥期权交易所波动率指数( CBOE VIX)。",
            "该指数基于标准普尔500指数期权的波动水平。",
            "该指数升高表示投资者恐慌增加。",
            "该指数降低表示投资者恐慌减少",
        ],
    },
    realize:{
        name1:"看清外汇市场——外汇交易员关注的指标",
        name2:"",
        content:[
            "波动率指数：芝加哥期权交易所的波动率指数",
            "芝加哥期权交易所的波动率指数（VIX）对于投资大众而言是最好的风险和情绪评估指数之一；外汇市场上的所有交易员几乎都能有效运用这一指数。VIX俗称“恐惧指数”，但实际上这一称呼会让人产生一些误解，因为VIX并不直接衡量任何类型的恐惧。VIX的衡量其实是交易员对于标准普尔500指数的波动率的预期。这一预期会以指数的形式标绘出来，指数越高，交易员对于短期市场波动率的预期越高。",
            "市场波动率越高，VIX就越高，因为VIX衡量的是标准普尔500指数期权虚值期权的价格。如果期权的卖方认为波动率在不久之后会上升，他们会向期权的买方要求更高的期权费。这一期权价格的上涨被用于VIX指数的计算中。相反，如果期权的卖方认为波动率将会下降，那么他们会降低期权费来吸引买方。期权价格下跌，则VIX指数通常也呈下降趋势。",
            "在每个交易日，VIX都会实时关注投资者情感和期权费的变化。VIX读数是一个按年度比率重估的数字，反映了交易员认为在未来30天内标准普尔500指数的涨跌幅。如果VIX读数是30，或者30%，这表明交易员认为在接下来的一个月内，标准普尔500指数可能有2.5%的涨跌幅(30%÷12个月=2.5%)。",
            "正如VIX所示，交易员的预期是毫无方向的。在上一例中，我们可以认为交易员预期标准普尔500指数在某个方向上会有2.5%的涨跌幅，但并没有具体指明是涨还是跌。然而，意外的市场波动具有下行倾向，所以上升的VIX指数通常意味着看跌预期。记住，市场不会暴涨，只会暴跌。",
            "所以，如果交易员预期显著的波动率，那么这通常就是一个看跌的迹象。这也就是为什么VIX通常被称为恐惧指数了。如果投资者担心波动率上升，那么VIX指数会上升;相反，如果投资者预期波动率较低，那么VIX指数会下降，这也被认为是一个看涨迹象。一般情况都遵循这个规律，但如果我们每天观察就会发现，还是有例外情况的。",
            "这个含义很明显。如果VIX呈下降趋势，投资者的交易采取看涨时的策略，愿意承担更多风险。如果VIX呈上升趋势，交易员可能会做空市场，试图限制其投资组合的风险。VIX通常都是处于某一范围内的，所以当VIX指数到达支撑位或阻力位时，操盘手会变得特别有兴致。",
            "根据VIX指数，看跌或看涨时交易员的感觉是非常重要的，因为这可以表明他们对于风险的态度。最终，投资者恐惧的增加与股票下跌、债券上涨和美元走强有关。反之亦然。",
            "当市场风险可能增加或减少时，VIX指数可以被用来分析、判断入市和出市的时机或时期。这个信息非常有用，因为这不仅仅是对于价格-时间研究的重复，而且是源自投资者对于近期波动率的预期。那么，当你分析VIX指数时，你应该关注什么呢？你应该关注：",
            "当VIX指数开始呈上升趋势时，避险货币会升值；",
            "当VIX指数开始呈下降趋势时，高风险、高收益的货币会升值。",
            "10年期债券收益率息差",
            "密切注意10年期债券收益率息差可以让你清楚了解未来的投资流向。不过你不能只寻找收益最高的国家，预期该国货币会不断继续升值。你应该寻找债券收益率不断增加的国家。债券收益率的变动可以改变投资流向，这可以引起货币升值。",
            "例如，如果你在关注瑞士的债券收益率，你发现它们稳步走高，这或许是瑞士法郎可能升值的一个可靠信号。如果你同时也发现美国的债券收益率开始下降，那么你应该认真考虑进行一个交易，好好利用瑞士法郎的走强和美元的走弱。",
            "股票市场表现",
            "密切注意股票市场的表现也可以让你清楚了解未来的投资流向。不过和债券收益率一样，你不能只寻找股市最强劲的国家，并预期该国货币会不断升值。你应该寻找股市越来越强劲的国家。股市实力的变化可以改变投资流向，这可以引起货币升值。",
            "比如，如果你在关注日本的股票市场表现，你发现日本股市开始稳步走高，这或许就是日元可能升值的一个可靠信号。如果你同时也发现英国的股市开始下降，那么你应该认真考虑进行一个交易，好好利用日元的走强和英镑的走弱。",
            "美国联邦基金期货价格",
            "交易员可以根据美国联邦基金期货价格和他们对于美国联邦基金利率变动的预期买卖期货。当交易员认为美联储会在未来提高利率时，他们一般会卖出这些期货合约；当交易员认为美联储会在未来降低利率时，他们则会买入这些期货合约。这些合约是机构交易员对冲利率风险、推测未来变化的一个非常好的方式。",
            "对于那些想要了解长期市场预期的外汇交易员而言，美国联邦基金期货价格利率是非常有用的。如果美国联邦基金期货价格利率低于目前的利率，这表明交易员有一个利率降低的预期，通常对于美元而言是个坏消息。相反，如果美国联邦基金期货价格利率高于目前的利率，这表明交易员有一个利率开高的预期，这对于美元而言通常是个好消息。",
            "如果你习惯交易其他期货合约，那么你可能一开始会觉得美国联邦基金期货的定价方式有点难懂。价格利率的计算方式是100%减去预期联邦基金利率。例如，如果当前的价格利率是96%，那么你就能知道交易员预期联邦基金利率是4%(即100%-96%=4%)与此类似，如果联邦基金期货价格利率从96%升至98%，那么这一般表明交易员认为联邦基金利率将从4%降至2%。这种涨幅变化当然是在长期发生的，而且是在很长一段时间内，联邦基金期货价格利率的变动可以在一个非常小的范围内。",
            "美国联邦基金期货价格利率图表明交易员对于未来利率变化的预期，而不是关于目前的利率，记住这点是很重要的。美国联邦基金期货价格利率图是分析师和交易员经常用作参考的，而且也是能够帮助你了解利率可能走向的非常好的来源。你可以在芝加哥商品交易所的网站上找到联邦基金期货价格利率图。你还可以在克利夫兰联储的网站上看到很多关于联邦基金期货期权的预测能力的讨论。",
            "那么，当你分析美国联邦基金期货价格利率时，你应该关注什么呢？你应该关注：",
            "当利率开始上升时，美元贬值;",
            "当利率开始下降时，美元升值。",
            "持仓报告（COT）",
            "操盘手几乎每周都可以得到特殊的市场报告，这IE报告简要介绍了大型机构交易员金额小型投资者所持各种商品期货品种（包括外汇）的仓位。这个信息叫做持仓报告，或COT报告，是由商品期货交易委员会(CFTC)提供的。",
            "持仓报告对于任何市场的交易员而言都是非常好的分析工具，因为该报告提供了关于每个商品市场的走向和交易员对该走向的承诺力度的最新信息持仓报告主要说明了三类不同的交易员所持的现有期货合约的净多头和空头的仓位情况：商业交易员、非商业交易员和未报告交易员。如果交易员做多头，或在增加他们的多头头寸，那么他们一般是对市场看好;类似，如果他们做空头，或在增加他们的空头头寸，那么他们对市场看跌。",
            "报告中并非所有的交易员都一样重要。实际上，在这三类交易员中，投资者通常应关注与其他个人交易员有同样需求的一类交易者——非商业交易员。",
            "商业交易员：这类交易员代表了那些用期货市场来抵消现金或现货市场风险的公司和机构。例如，如果美元会在近期贬值的话，一家有美国公司的应收账款的日本汽车制造厂可能就会出售美元期货合约来保护自身利润。对于零售交易员而言，这类交易员并没有什么可参考性，所以我们不会过多关注。",
            "非商业交易员：这类交易员包括大型机构投资者、对冲基金和其他为了投资和增长在期货市场进行交易的实体。他们通常不直接参与生产、销售或基本商品或资产的管理。我们应主要关注这类交易员。",
            "未报告交易员：这类包含甚广，主要是那些小交易员，他们所持仓位非常小，不需要报告给商品期货交易委员会。我们不知道这类包含了多少个交易员或者他们代表了哪种类型的投资者，因为他们是未被报告的。大多数市场专家认为这类交易员的主要群体是个人投机者。他们是出名的臭手，你经常可以发现，这类交易员通常都是与市场趋势对着干的，而不是顺着来的。我们不关注这类交易员。",
            "那么，当你分析持仓报告时，你应该关注什么呢？你应该关注：",
            "当净多头仓位增加或净空头仓位减少时，报告中提到的货币会升值",
            "当净多头仓位减少或净空头仓位增加时，报告中提到的货币会贬值",
        ],
    },
    main:{
        name:"主要货币对的概况和特性",
        content:[
            "一、货币简介：美元(USD)",
            "美国是世界的主要经济动力，其2006年的国内生产总值超过了11万亿美元。这是世界上最大的GDP数值，根据购买力平价模型，这个数值是日本产值的3倍，德国的5倍，英国的7倍。美国是以服务业为主导产业的国家，几乎80%的GDP都来自房地产、交通、金融、医疗保健和商业服务行业。然而，美国规模庞大的制造业仍然使得美元对制造业的发展状况极为敏感。美国拥有世界上最具流动性的股票市场和固定收益市场，外国投资者一直都在增加美国资产的购买。根据国际货币基金组织统计，外国对美国的直接投资几乎达到美国的全球净流入总额的40%。",
            "特性：",
            "1、超过90%的外汇交易都涉及到美元",
            "2、在9.11事件之前，美元被认为是世界首要的避险货币之一",
            "3、美元的走势与黄金的走势相反",
            "4、很多新兴市场的货币都钉住美元",
            "5、密切关注美国国库券和外国债券的利率差异",
            "6、留意美元指数",
            "7、美元的交易受到股票和债券市场的影响",
            "二、货币简介：欧元(EUR)",
            "欧洲货币联盟是世界第二大经济体，2006年的国内生产总值约为12万亿美元。欧洲货币联盟有高度发达的固定收益市场、股票市场和期货市场，所以对国内外投资者来说，也是世界第二个最具吸引力的投资市场。",
            "特性：",
            "1、欧元/美元是最具流动性的货币对，所有主要的欧元交叉货币对也非常具有流动性",
            "2、欧元具有独一无二的风险",
            "3、10年期美国国库券和10年期德国国债的价差可以指示市场对欧元的情绪",
            "4、预测欧元区的资金流动",
            "三、货币简介：英镑(GBP)",
            "英国是世界第四大经济体，由于有一个世界效率最高之一的央行，英国经历了多年的强劲经济增长、低失业率、产能扩张和富有弹性的消费。消费者的消费力度大部分源于英国强劲的房地产市场，该市场在2003年达到顶点。英国是一个以服务业为主导产业的经济体，制造业在GDP中的比重逐渐减小，现在只相当于国内产值的1/5。英国的资本市场是世界最发达的市场之一，因而金融和银行业对英国的GDP贡献最大。",
            "特性：",
            "1、英镑/美元非常具有流动性",
            "2、英镑有三个名字：the British Pound、Sterling、Cable",
            "3、英镑有大量投机者参与其中",
            "4、密切关注应该金边债券和外国债券的利率差异",
            "5、欧洲英镑期货（Eurosterling futures）可以为利率变动提供指示",
            "6、英国政客对欧元的评论会影响欧元走势",
            "7、英镑与能源价格具有正相关性",
            "8、英镑有关的交叉货币对",
            "四、瑞士法郎(CHF)",
            "瑞士是世界第19大经济体，2006年的GDP超过了2550亿美元。这经济体虽然相对较小，但如果按人均GDP计算，却是世界最富有的一个。它的繁荣程度和先进的技术比得上很多更大的经济体。国家繁荣主要因为制造业、旅游业和银行业具有相当的专业性，具体地说，瑞士的化学和制药业、机器、精密仪器、手表非常著名，尤其是金融系统在保护投资者机密方面在历史上就已闻名于世。加上瑞士长久以来的政治中立，为国家和货币创造了安全避所的美誉。",
            "特性：",
            "1、安全避难所的地位",
            "2、瑞郎与黄金的关系密切",
            "3、套息交易效应",
            "4、密切关注欧洲瑞郎期货和外国利率期货间的利息差异",
            "5、银行制度有可能发生改变",
            "6、跨国并购活动",
            "7、瑞郎相关交易行为和交叉货币对的特征",
            "五、日元(JPY)",
            "日本是世界第三大经济体，2006年的GDP超过了4.2万亿(仅次于美国和整个欧元区或欧洲货币联盟)，也是世界第二大主权经济体。日本还是世界最大的出口国之一，每年出口额超过5000亿美元。",
            "特性：",
            "1、亚洲货币整体强/弱代表",
            "2、日本央行的干预习惯",
            "3、日元的波动季节性很强",
            "4、银行股被广泛关注",
            "5、套息交易效应",
            "六、澳元(AUD)",
            "就GDP而言，澳大利亚是亚太地区第五大国家。在2006年，它的GDP约为6740亿美元。虽然这个经济体相对较小，但如果按人均GDP计算，它可以比上西欧很多工业国家。澳大利亚以服务业为主导产业接近79%的GDP来自金融、房地产和商业服务等行业。",
            "特性：",
            "1、商品货币",
            "2、套息交易效应",
            "3、干旱效应",
            "七、新西兰元(NZD)",
            "新西兰是个很小的经济体，2006年的GDP约为1070亿美元。它曾经是经济合作与发展组织里管制最严的国家，但在过去20年，新西兰逐渐朝着一个更开放、更现代和更稳定的经济体迈进。",
            "特性：",
            "1、与澳元有非常强的相关性",
            "2、商品货币",
            "3、套息交易",
            "4、利率差异",
            "5、移民",
            "6、干旱效应",
            "八、加拿大元(CAD)",
            "加拿大是世界第七大国家，2006年的GDP达到11780亿美元。从1991年开始，加拿大的经济就稳步增长。由于加拿大早期的经济发展完全依赖国家自然资源的开采和出口，所以通常被认为是资源性经济体。现在，它是世界第五大黄金生产国和第四大石油出产国。",
            "特性：",
            "1、商品货币",
            "2、与美国有非常紧密的关系",
            "3、并购",
            "4、利率差异",
            "5、套息交易",

        ],

    },
    go:{
        name:"走进货币——12个关键问题",
        content:[
            "货币和人一样具有性格。有些货币个性抑郁，有些货币活泼好动，也有一些货币死气沉沉。正是如此，外汇市场才会那么有趣。",
            "当你在外汇市场中交易货币时，你要和不同的货币建立关系，所以你最好了解它们。在了解的过程中，你会发现有一些货币和你意气相投，也有一些与你格格不入。",
            "为了让你更好地了解货币，我们为你提供“速配约会”服务。我们预感到你会害羞和尴尬，所以在你赴约前，我们替你准备了12个需要回答的问题。",
            "这些问题有何特别之处？你为什么要花时间学习这些东西？",
            "首先，你对货币越了解，你就能轻松地做出投资选择——这是常识。更重要的是，你要尽可能谨慎地投资货币，避免被突如其来的变故害的倾家荡产。现在让我们一起来看看这12个问题，看看它们为什么和你的投资决定相关联。",
            "一、你们的经济处于贸易顺差还是贸易逆差",
            "贸易顺差国的货币往往较为强势，原因是贸易顺差国的产品服务需求量更大，而国外买家购买时必须用卖方货币支付，从而导致其货币需求量增加。相反，贸易逆差国的货币往往较为疲软，原因是买方国家在支付所购买产品和服务时需要将本国货币兑换成卖方国家的货币，如此一来，本国货币的供应量上升，其价值减少。",
            "二、你们出口什么",
            "我们为什么要关心一个国家出口什么产品和服务？这是因为如果知道一个国家出口的主要产品和服务，我们就能清楚什么样的市场和价格需要关注，而这些市场和价格的变化也正是该国货币变化的预兆。",
            "例如，新西兰是世界主要的奶制品出口国，出口产品包括黄油、奶酪、牛奶和奶粉。知道这一点，你就应该清楚自己需要关注的是奶制品价格。如果奶制品价格上涨，购买相同数量的奶制品，进口商就不得不兑换更多的新西兰元。因此，本国货币会由于市场供应量增加而贬值，新西兰元由于需求量增加而升值。反之，如果奶制品价格下跌，购买相同数量的奶制品，进口商就要减少新西兰元的兑换量。这很可能会导致本国货币因供应量缓慢下降而升值：新西兰元因市场需求量减小而贬值。",
            "你会发现，这种分析方法特别适用于评估那些实行商品经济的国家的货币，例如，澳大利亚、新西兰、加拿大等国家。",
            "随着学习的深入，在对一个国家出口的产品和服务进行分类时，我们将用到世界贸易组织（WTO）使用的一套分类法，该组织把产品和服务分为如下几类：",
            "商品贸易：农产品、燃料和矿产品、制造品",
            "商业服务贸易：运输、旅游、其他商业服务",
            "三、你们向谁出口",
            "我们为什么要关心一个国家向谁出口产品和服务？因为通过调查从外部进口某种产品的国家的经济健康程度，你可以预测出未来这些国家对该产品的需求量。",
            "例如，澳大利亚出口到中国的产品比出口到其他任何国家的都多。或者换一种说法，中国从澳大利亚进口的产品比其他任何国家从澳大利亚进口的产品都多。无论用哪种方式表达，你都能看出中国是澳大利亚极其重要的贸易伙伴。",
            "知道了这一点，你就可以开始调查中国的GDP、就业率、生产数据等指数然后推测出中国在未来是否仍是澳大利亚最大的进口国。如果中国的经济指标很强，那么澳大利亚对中国的出口仍将保持旺盛的活力，同时澳大利亚元的需求量和价值都能保持较高水平;如果中国的经济指标不够强，那么澳大利亚对中国的出口将呈下降趋势，同时澳大利亚元的需求量和价值也会降低。",
            "四、你们进口什么",
            "我们为什么要关心一个国家进口什么产品和服务？因为如果我们知道了一个国家进口的主要产品和服务，我们就能清楚什么样的市场和价格需要关注，而这些市场和价格的变化也正是该国货币变化的预兆。",
            "比如，日本是一个石油净进口国，实际上它目前是全球第四大石油进口国。由于日本严重依赖石油进口，而石油价格又以美元为单位，所以日元对石油价格的变动很敏感。当石油价格上涨时，为了购买相同数量的石油，日本不得不增加日元对美元的兑换量，从而导致日元价值因市场供应量增加而下降，美元价值由于需求量增加而上升。反之，如果石油价格下跌，为了购买相应数量的石油，日本不得不减少日元对美元的兑换量。这可能会造成日元因市场供应量缓慢增加而升值，美元因市场需求量减少而贬值。随着学习的深入，在对一个国家进口的产品和服务分类的时候，我们将使用讨论出口时所用到的WTO分类法。",
            "五、你们的进口来自哪里",
            "我们为什么要关心一个国家从谁那里进口产品和服务?因为出口国的货币价值通常会直接影响进口国的货币价值。",
            "举个例子，加拿大超过半数的进口产品和服务来自美国。也就是说，加拿大的货币和经济极易受到美元的影响。如果美元升值，为了购买相同数量的产品和服务，加拿大必须增加美元的兑换量。这会导致加拿大元因市场供应量增加而贬值，美元因市场需求量增加而升值。反之，如果美元贬值，为了购买相同数量的产品和服务，加拿大要减少美元的兑换量，从而使加拿大元因市场供应量缓慢下降而升值，美元因市场需求减少而贬值。",
            "六、你们的国债市场是否具有吸引力",
            "我们为什么要关心一个国家的国债市场是否具有吸引力?因为倘若一国的国债市场具有吸引力，那么它通常能吸引大量的海外投资。一般情况下，当投资增加时，货币会因其需求量增加而升值。",
            "当投资增加时，货币会因其需求量增加而升值投资者在评估一个国家的国债市场时一般要考量两个问题：",
            "1、市场风险有多大?",
            "2、我的投资回报预期是什么?",
            "这两个问题虽然至关重要，但是两者决不能单独来看。例如，某国债务市场风险巨大，政府有可能无法偿还债务，所以不适合投资者投资。但同时该国的投资回报率却相当高，对投资者来说具有很大的吸引力。反过来说，某国债务市场风险很小，适合投资：但同时投资回报率不高，投资者也有理由不投资。所以，投资者在投资前需要权衡两者。",
            "理想化的情况是，投资者寻求违约风险低但投资回报率高的国家进行投资。但是请你问问自己，有几个国家拥有低风险、高回报的市场?如果你在均衡风险和回报的话，难道不应该风险大的市场回报高，风险小的市场回报低吗?对于这个问题，答案没有绝对的“是”与“不是”。",
            "一个国家的国债市场必然受到市场风险的影响，但是这并不是唯一的影响因素。无论是刺激经济还是降低通货膨胀，中央银行的措施在很大程度上决定了国债市场的回报率。例如，澳大利亚国债市场被认为是相对安全的，但随着本国经济的繁荣(很大程度是因为向中国出口原材料)，其中央银行一澳大利亚储备银行( Reserve Bank of Australia)上调了利率以防止恶性通货膨胀。这一举措加大了投资者在澳大利亚国债市场上的回报。",
            "所以，在比较各国国债市场的时候，我们要挑出利率高、市场稳定的国家。",
            "投资者在评估一个国家国债市场的风险等级时可以参考两个数据：穆迪长期债务评级和债务率(债务占国内生产总值的比重)。",
            "穆迪长债务评级",
            "穆迪长期债务评级是有关金融债务(原始到期日为一年及以上)相对信用风险的意见，它一般会揭示出金融债务无法按承诺履行的可能性，同时反映了违约发生的几率以及违约后造成的一切经济损失，评级过程使用穆迪公司的全球化评级方法，它将债务分成如下九个等级",
            "1、Aaa级：债务质量最高，信用风险最低",
            "2、Aa级：债务质量很高，信用风险很低",
            "3、A级：债务质量中上等，信用风险低",
            "4、Ba级：债务质量中等，信用风险一般并带有不确定性",
            "5、Ba级：债务具有投机性，信用风险较高",
            "6、B级：债务具有投机性，信用风险高",
            "7、Caa级：债务质量差，信用风险很高",
            "8、Ca级：债务投机性高，违约可能性很大，但违约后存在本金利息追回的可能性",
            "9、C级：债务质量最低，通常情况下会违约，违约后本金利息追回的能性极小",
            "另外，穆迪公司还在每种等级分类(从Aa到Caa)前标上数字1、2、3。其中，数字1表示债务在所属类别中排名靠前，数字2表示债务在所属类别中排名居中，数字3则表示债务在所属类别中排名靠后。",
            "债务与GDP的比率通常衡量了一个国家的负债程度。如果某人年收入50000美元，每年负债60000美元去支付一栋房、两辆车、一艘船和五张信用卡的债务，这对大部分金融机构来说，都具有较高的信用风险。同样，大部分金融机构也会认为一个负债率高的国家有较高的信用风险。",
            "一般来说，负债率高的国家会用提高利率的方法吸引他国的借贷。这种做法能够长期帮助投资者的风险回报比率达到平衡，但又打破了一个国家能同时拥有低风险和高回报的美好愿景。",
            "七、你们的股票市场是否具有吸引力",
            "我们为什么要关心一个国家的股票市场是否具有吸引力?因为倘若一国的股票市场具有吸引力，那么它通常能吸引大量的海外投资。一般情况下，当投资增加时，货币会因其需求量增加而升值。",
            "投资者在评估一个国家的股票市场时要考量两个问题",
            "1、市场风险有多大?",
            "2、我的投资回报预期是什么?",
            "股票市场的风险一般受多种因素的影响。市场规模至关重要。相比小而不成熟的股票市场，大而成熟的股票市场(如美国)具有更安全的投资环境。大型股票市场一般都拥有大量投资者，以及供投资者选择的不同股票类型，同时它还具备很强的流动性。",
            "大型股票市场的监管更为有效。比如，想在纽约证券交易所(NYSE)上市的公司会比在博茨瓦纳证券交易所(BSE)上市的公司面临更加烦琐的申报要求。但是，公司提供的信息越准确，投资者越有信心投入更多的钱购买其股票。",
            "投资者自然会权衡股票市场的风险和投资后的潜在利润。高回报的股票市场通常具有高风险;反之，对于回报低的股票市场，其投资风险可能也不高。",
            "理想化的情况是，投资者寻求到回报高且稳定的股票市场进行投资。",
            "八、央行的职责以及持有的黄金和外汇储备",
            "我们为什么要关心一个国家的中央银行是什么、职责是什么以及其黄金和外汇储备量是多少？因为比起一个国家的其他机构，中央银行往往更能决定其货币走向强势还是弱势。",
            "所幸的是，中央银行并没有随意加入外汇市场去操控货币的高低，它在市场中走的每一步都遵循自己的职责。一些中央银行被授予控制经济增长的职责，放置经济扩张或收缩过快；另一些中央银行则被授予放置失业率过高的职责；还有一些中央银行的职责包含前两者（有时会很复杂）。理解监管管你所交易的货币的中央银行的职责，大多能帮助你预测在不同市场形势下银行可能采取的措施。",
            "除了职责之外，你还需要知道中央银行持有多少黄金和外汇储备。我们从中央银行的黄金和外汇储备量中可以看出它干预自由市场的能力。储备量小的中央银行一般没有足够的资本去干预动荡的外汇市场和剧烈的价格波动：相反，储备量大的中央银行在外汇市场中游刃有余，甚至在必要的时候可以调整市场。",
            "在了解中央银行的过程中，你要关注任何表明中央银行在改变其外汇构成的消息。我们发现，各个中央银行的去美元化正在慢慢形成一种趋势。如果这种趋势在未来继续发展，那么美元的总需求量将会受到影响。",
            "九、政府是否过多干预外汇市场",
            "我们为什么要关心货币发行时政府是否过多干预外汇市场呢？因为政府在外汇市场的活跃程度影响着我们交易货币的方式。",
            "有些政府时刻进行着市场干预，这是因为他们在努力保持本国货币与别种货币或一揽子货币挂钩。还有一些政府从不干预市场，他们认为市场应该沿自己的轨迹运行，任何形式的干预都可能产生某些不良影响。",
            "然而在大多数情况下，你会发现政府有必要在某些时候插手市场进行干预，尽管这样的时候不多。",
            "十、哪些经济数据是重要的",
            "我们为什么要关心哪些经济数据是重要的？因为如果我们知道什么样的经济数据是重要的，我们就能够及时观察这些经济数据，因为其趋势做准备。",
            "十一、货币是避险货币吗",
            "我们为什么要关心一个国家的货币是否是避险币？这是因为货币规避风险的能力会影响经济危机时期货币的交易方式。比如，瑞士法郎是避险货币，所以当投资者恐慌增加时，其价值通常也会增加。再比如，新西兰元不是避险货币，所以当投资者恐慌增加时，其价值一般会下降。",
            "十二、我如何交易你们的货币",
            "我们为什么要关心一种货币的投资工具是什么？因为我们花大量时间、精力学习外汇市场知识和影响每种货币的因素，大多只为一个目的：在外汇市场中赚钱。无论是期货合同、现货合同，还是交易所交易基金，知道自己能以何种方式投资均可以帮助我们决定把钱投入到哪里赚钱。",
            "下面我们将通过介绍一些投资工具来告诉你如何交易货币：",
            "1、现货外汇；",
            "2、外汇期货；",
            "3、交易所交易基金（ETF）；",
            "4、交易所交易票据（ETN）；",
            "5、现货外汇期权；",
            "6、交易所交易外汇期权",
        ]
    }
}

const contentEn = {
    market:{
        name:"Forex market:",
        name2:'the contemporary fastest growing financial market',
        content:[
            "1. The comparison of the Forex market with futures and stock market",
            "It is not only the developing of online Forex trade that stimulates the whole Forex market’s transaction amount. Along with the volatility of Forex market rose in the past few years, many investors realized that the volatility of Forex market will also affect the stock market and bond market. Thus, only if considered and tracked the change of Forex market, that could stock, bond and commodity investors make wise trade decisions. There are some historical examples for Forex market affecting the stock market and the bond market.",
            "EUR/USD and company profit",
            "For stock traders, especially those who invest in a large number of European companies which export to the US, paying close attention to exchange rate changes is very important for predicting the company's earnings and profitability. Since 2003, European manufacturers have complained about the appreciation of the euro and the depreciation of the dollar. The chief culprit in the dollar’s weakness is the fast-growing US trade deficit and budget deficit, the so-called “double deficit” issue. This problem caused the euro to rise against the dollar, which in turn made the Eurozone's exports to American consumers more expensive, which ultimately led to a decline in the profits of Eurozone companies. In 2003, the German Volkswagen Company did not conduct sufficient exchange rate hedging, resulting in a loss of profits of approximately 1 billion euros. While the Dutch national mining company, the chemical group warned that a one percent change in the exchange rate of the euro verse the US dollar would lead to the company 7 million to 11 million euros loss. Unfortunately, inadequate exchange rate hedging remains a common problem in the 2008 Eurozone. Therefore, paying close attention to the exchange rate changes between the euro and the US dollar is extremely important for predicting the income and profit levels of euro exporters.",
            "Nikkei index and US dollar",
            "Japanese stock investors should also pay close attention to US dollar trends, and how the trend affecting Nikkei index. Japan has experienced economic stagnation for about ten years. In this period, the US mutual fund and hedge fund have substantially reduced their Japanese stocks. When the Japanese economy began to recover, these funds rushed into the market, and they adjusted their portfolio to not miss the investment chance brought by Japanese economic recovery. Hedge funds borrowed dollars to buy Japanese stocks and increase their exposure to Japanese stocks. However, this action made them extremely sensitive to dollar’s exchange rate, and also to the Fed’s monetary policy of its tightening cycle. The increase cost of US debt will hit the upward trend of the Nikkei, as higher interest rate will lead higher cost of dollar loans. The United States has a huge deficit account, and the Fed must continue to raise interest rates to maintain the dollar assets with attraction. Thus, the continued rate hike along with the slow growth of the Japanese economy may make it unprofitable, for excessive financing to buy Japanese stocks. Therefore, the change for US dollar has significant impact on Nikkei index.",
            "2. The comparison of the Forex market with futures and the stock market.",
            "Traditionally, the Forex market is not pursued by the public, because the regulations, capital requirements and technical limitations. Which made the initial Forex market participants are limited only to large funds organizations such as hedge funds and commodity management funds and other large companies. The cause for the limitation of large organization is because the risk for traders are personalized. For example, one trader may adapt 100 times leverage, while another trader may not use any leverage. However, in recent years, many companies started to provide entrance to Forex market for individual investors (small retail traders). These companies provide trade financing and leverage, free trading platform, markets charts as well as real-time news for individual traders. This makes the Forex market more attractive as one of the finance instruments and Forex trade becomes more popular.",
            "Many investors are adding Forex into their trading pool or they may only trade Forex. Because these traders began to realize that Forex trade is more attractive than stock and futures trade.",
            "The comparison between Forex and stock",
            "Forex spot trading has the following differences compared with securities stock trading:",
            "Main features of the Forex market",
            "The Forex market is the largest financial market, and the transaction amount and liquidity is constantly growing.",
            "The Forex market runs 24/5.",
            "Traders could made profits in an upward trend or a downward trend.",
            "No trading restrictions.",
            "Immediately executive trading platform minimizes transaction slip spreads and errors.",
            "Although high risks comes along with high leverage, many investors still believe Forex market is a “worthy-trading” market.",
            "Main features of the stock market",
            "Main features of the stock market",
            "The market runs from 9:00am to 4:30pm in New York time, and there are restrictions on the trading hours of off-site electronic trading.",
            "Current the cost for transaction and commission fee is relatively high.",
            "The rule of “must selling in an upward trend”, this is the biggest limitation for intraday traders. This trading restriction therefore has negative impact to investors.",
            "Too many steps for completing a trade, which increase the probability of transaction slip spreads and errors.",
            "Forex market is the most liquidity market globally, the huge market volume and extreme high liquidity allow investors to trade with low cost and high leverage. This is the market that runs 24 hours and is profitable either in bear or bull market. It features with minimizing error rate and slip spreads, no rules of trading limitations or selling in upward trend. Traders could use the analysis skills in stock market for Forex market. For fundamental traders, they can analysis the nations as stocks; for technical traders, the Forex market is an ideal market to use technical analysis which is wildly used by professional traders. To better understand why Forex market is so attractive and worthy to take part in, we have to learn the characters for Forex deeply.",
            "The comparison of Forex market and futures market",
            "Main features of the Forex market",
            "It is the largest markets globally, and the liquidity is increasing.",
            "It runs 24 hours of week day.",
            "It is profitable either in bear market or bull market.",
            "No rule of only “selling in an upward trend”.",
            "Immediately executive trading platform minimizes the transaction slip spreads and other errors.",
            "Although high leverage comes with high risks, many investors still believe Forex market brings more potential profits.",
            " Main features of the Futures market",
            "The market liquidity is limiting and mainly depends on contract liquidity each month.",
            "Transaction clearing fee and commission cause higher trading cost.",
            "The market open time for the Futures market is short than the Forex spot market, and relies on each trade category; different trade category comes with different open and close time, and there has trading hour restriction of off-site trading.",
            "The leverage level for futures is higher than securities but far lower than it in Forex market.",
            "Most of time, the bear market last longer in the futures market.",
            "The structure of the pit trade increases the probability of trade slip spreads and other errors.",
            "Just like the technical analysis skills in stock market could apply in the Forex market, the trading strategy in the futures market could also operates in the Forex market. Most of futures traders are using technical analysis, as it is mentioned for the stock market above, the Forex market is an ideal place to use these skills. Actually, technical analysis is the mostly common used analyzing tool for professional traders.",
            "3. Different approached in Forex trading",
            "Forex spot",
            "Forex futures",
            "Forex options",
            "Transactional open index fund",
        ],
    },
    first:{
        name:"Learn about the Forex —— Forex basic knowledge",
        content:[
            "The Forex traders will never buy or sell one currency, this is the base of how the market operates. Traders sell a currency firstly then buy in another currency. Generally, currencies will not be traded solely.",
            "Think about this: how much does 1 dollar worth? It is just 1 dollar? In the same way, is 1 pound worthy 1 pound? Any currency comparing with itself is meaningless. Only coupled them into pairs that could present meaning. When you face a currency pair, it is not only the currency pair you can view but also of their comparison. Now, you can ask the former questions again: how pound does 1 dollar worth? Or, how much dollars can 1 pound buy?",
            "For beginners, it is always a hassle question that trade currency in pairs, as they may get used in trading sole stock or sole fund. They may be unfamiliar to currency pairs. So, if you cannot accept of currency pairs, don’t worry, many other traders are the same as you. It is sure that you could get used to them gradually.",
            "Currency pairs",
            "In a currency pair, the currency on the left side is the basic currency, and the one on the right side is quote currency. A simply way to distinguish these two: the strength of the base currency determine the trend of the currency pair, whereas the strength of quote currency decides the price of the currency pair.",
            "For example, the most common seen currency pair is EUR/USD, in this case, the euro is base currency and the U.S. dollar is the quote currency. The strength of euro against dollar decide the appreciation/depreciation for this currency pair. If euro is stronger than the dollar, then the EUR/USD will appreciated, and vice versa. Here are the tips to help you understand the changes in the currency pairs:",
            "Basic currency strong, quote currency weak, the currency pair appreciate;",
            "Basic currency weak, quote currency strong, the currency pair depreciate;",
            "Quote currency strong, basic currency weak, the currency pair depreciate;",
            "Quote currency weak, basic currency strong, the currency pair appreciate.",
            "Remember that: the currency will not trade independently. Either change of the base currency or the quote currency will affect the currency pair.",
            "The price of EUR/USD represents how much dollars you need to pay of buying 1 euro. Such as, the price of EUR/USD is 1.3055, it shows that 1.3055 dollars needed to buy 1 euro. In the same way, if the price rose to 1.4277, it means 1.4277 dollars needed to buy 1 euro.",
            "Then, who decides what are the base currency and the quote currency? It is the International Organization for Standardization (ISO). As a non-government organization, it is aiming for bringing orders to the chaos world.",
            "There are three main currency pair types:",
            "Major currency pairs",
            "Emerging market currency pairs",
            "Cross currency pairs",
            "Main currency pairs",
            "The major currency pair refers to the currency pair consisting of the US dollar and the other six major currencies in the world:",
            "EUR/USD",
            "USD/JPY",
            "GBP/USD",
            "AUD/USD",
            "USD/CHF",
            "USD/CAD",
            "Emerging markets currency pairs",
            "Emerging markets currency pairs refers to the currency pair consisting of the US dollar and other currencies in the world. Emerging markets features its low liquidity of its currency. Such as Swiss franc (SEK), New Zealand dollar (NZD), South African Rand (ZAR), etc.But as emerging market currencies become more popular, their liquidity is gradually improving.",
            "Next, let's take a look at the list of emerging market currency pairs, from which you can choose to invest to expand your personal portfolio:",
            "USD/HKD",
            "USD/SEK",
            "NZD/USD",
            "USD/SGD",
            "USD/NOK",
            "USD/MXN",
            "USD/ZAR",
            "USD/DKK",
            "USD/THB",
            "Cross currency pairs",
            "Cross currency pairs is the currency pair excludes U.S. dollar. For example, euro and pound, Australian dollar and Japanese Yen are the cross currency pairs. Other common seen cross currency pairs:",
            "GBP/JPY",
            "EUR/GBP",
            "AUD/JPY",
            "EUR/CHF",
            "CAD/JPY",
            "The PIP is the changing unit",
            "People who often trade in stocks, securities or commodity futures are accustomed to using quotes from Yuan and sub-units. But this is not the case for Forex market—the PIP is the basic unit for currency pair.",
            "What is the PIP? PIP is the abbreviation for “ Price Interest Point”. You could also call it “point”. In most cases, a base point represents one ten thousandth of a currency unit. But there are exceptions. For example, a base point for the yen represents one percent of a yen. The base point has always been the smallest trading price point in the foreign exchange market, but recently foreign exchange dealers have begun to use smaller trading units. Initially, they used “one-half basis” for transactions in currency pairs such as EUR/GBP and EUR/CHF. Later, with the expansion of trading volume, some traders began to use \"one tenth of a base point\" as the unit, which is five digits after the decimal point.",
            "PIP value",
            "So, how much is it worthy for a PIP? This is a good question, and the answer depends on several factors.",
            "In stock trading, you could calculate how much you profit or lose by the stock price rising and decreasing. But in calculating the value of a PIP(or in some case, 1/10 of a PIP), you have to know what is the base currency and the contrast volume. We will explain the contrast volume in Chapter 12 of investment tools in Forex market. Now you only need to know that a standard contrast concludes 100,000 currency units, and small contrast concludes 10,000 currency units. Here is the formula helping you to calculate the PIP value:",
            "(1 PIP/ Interest rate)*Contrast volume= PIP value",
            "Let’s substitute real data: imaging you want to know the value of one PIP for USD/JPY, and knowing that the exchange rate for USD/JPY IS 82.65. You can substitute the formula to calculate the result:",
            "(0.01/82.65)×100000=12.10(U.S. dollar)",
            "Another example, imaging you want to know the value of one PIP for EUR/USD, and knowing the exchange rate is 1.3387. Substituting statistics into the formula, you can get:",
            "(0.0001/1.3387×10000=0.74699(Euro)",
            "Of course, if you want to know what the PIP value is for U.S. dollar without being the base currency, you should add one more step. In order to convert the base point value of a non-US dollar currency into the base value of the US dollar, you need to use the following formula:",
            "PIP value×exchange rate= U.S. dollar PIP value",
            "In the above example of EUR/USD, the PIP value of U.S. dollar is:",
            "0.74699×1.3387=1(U.S. dollar)",
            "With this formula, you can calculate the PIP value of any currency.",
        ],
    },
    wave:{
        name1:"Behind the wave of Forex fluctuations",
        name2:"—— what is driving currency prices",
        content:[
            "Once we know what creates a free money market, we can better understand what influences the value of money today; and the more we know about reality, the better we can prepare for the future. For example, Forex, only understand the operating mode behind it to better grasp the key moments of profit. Don't waste every opportunity to get wealth.",
            "1. The trade flow",
            "Trade flows represent the flow of money generated by the circulation of goods or services between the two countries, which is generally affected by two things:",
            "Foreign demand for domestic goods",
            "Domestic demand for foreign goods",
            "Foreign demand for domestic goods",
            "While foreign demand for domestic goods is generated, the demand for domestic currency and the supply of foreign currency will generally increase accordingly. An increase in the demand for domestic money will allow the domestic currency to appreciate, and an increase in the supply of foreign money will depreciate foreign currencies. Its principle is as follows:",
            "For example, a Spanish customer want to buy the product produced by American. As a consumer, this Spanish will naturally think about pay by euros, but American hope he pays by dollars.",
            "This redemption process has increased the supply of euros in the market and has also fueled demand for the dollar. This means that the value of the euro has fallen and the value of the dollar has risen.",
            "Domestic demand for foreign goods",
            "Generally speaking, while domestic demand for foreign goods is generated, the demand for foreign currency and the supply of domestic currency also increase accordingly. The increase in foreign currency demand has caused foreign currencies to appreciate, while the increase in domestic money supply has devalued the national currency.",
            "In the previous example, if we reversed the roles of the United States and Spain, we could get a new example, but the principles are the same. You have to remember that in international trade, when money flows from the buyer to the seller, the buyer's currency depreciates and the seller's currency appreciates.",
            "2. The investment flow",
            "The investment flow represents the flow of money generated by a country's investors buying and selling assets in another country. It is affected by three factors:",
            "Foreign demand for domestic assets",
            "Domestic demand for foreign assets",
            "Asset repatriation",
            "Foreign demand for domestic assets",
            "Under normal conditions, while foreign demand for domestic assets is generated, the demand for domestic currency and the supply of foreign currency also increase accordingly. The increase in domestic currency demand has allowed the national currency to appreciate, while the increase in foreign money supply has devalued foreign currencies. Its principle is as follows.",
            "Suppose a Japanese investor wants to buy New Zealand government bonds. As an investor, the Japanese naturally thought of paying in yen, but the New Zealand government wanted him to pay in New Zealand dollars. In order for this sale to be successful, Japanese investors must first convert the yen into the New Zealand dollar and then pay the bond issuer.",
            "Currency exchange increased the supply of Japanese yen in the Forex market and the demand for the New Zealand dollar, which led to the appreciation of the yen and the depreciation of the New Zealand dollar.",
            "Domestic demand for foreign assets",
            "At the same time as domestic demand for foreign assets, the supply of domestic currency and the demand for foreign currencies have also increased accordingly. The increase in the domestic money supply has caused the domestic currency to depreciate, while the increase in foreign currency demand has allowed foreign currencies to appreciate.",
            "In the previous example, if we reversed the roles of Japan and New Zealand, we can get a new example to illustrate this point. In international asset transactions, when money flows from the buyer to the seller, in general, the buyer's currency depreciates and the seller's currency appreciates.",
            "Asset repatriation",
            "Asset repatriation increases the demand for domestic currency and the supply of foreign currency. The increase in domestic currency demand has allowed the national currency to appreciate, while the increase in foreign money supply has devalued foreign currencies.",
            "3. the money supply",
            "Money supply refers to the total amount of money issued by a country. This concept seems strange, but in today's legal currency (referring to the currency without any physical assets as the standard) and the era of computers, any change in the money supply can be completed in an instant. The government's financial department no longer has to print money in order to increase the money supply, although they can do the same. Now, they only need to tap a few keys on the mirror to achieve the goal.",
            "The money supply of a country is important to Forex traders because it has a direct impact on the value of money. The greater the currency issuance, the lower the monetary value; the less the currency is issued, the higher the monetary value.",
            "The money supply of a country is usually determined by the following departments or agencies:",
            "Government Ministry of Finance",
            "Central Bank",
            "The role of the Ministry of Finance in determining the amount of currency issued",
            "As we mentioned before, the Ministry of Finance controls the currency printing of the mint. Since the legal currency has no physical assets as the currency standard, the Ministry of Finance can simply increase the money supply by ordering the mint to prepare paper and ink and start the printing press. With the entry of these new printed banknotes, the money supply has increased in the true sense.",
            "Of course, if these banknotes are used to replace worn and damaged currencies, the amount of physical money circulating in the market will not change. Here, you only need to remember one point: start the press of the printing machine to complete the increase in money supply.",
            "The role of the Central Banks in determining the amount of currency issued",
            "At the moment, it is easy to start printing presses, but the central bank can more easily increase or decrease the supply of money – all they have to do is enter a few numbers into the computer and press the Enter key. In fact, the central bank prints and destroys currency every day. Below we will use the US Central Bank - Federal Reserve or Fed as an example:",
            "When the Fed is preparing to cut interest rates, it will increase its money supply by lending short-term mortgages (called “repurchase agreements”) to primary dealers (large banks). Under the repurchase agreement, the Fed borrows US Treasury bills from various primary dealers and writes them off from the other's reserve accounts. After the expiration of the agreement, the Federal Reserve will return the Treasury bill to each primary dealer and will be credited to the other party's reserve account.",
            "When the Fed is preparing to raise interest rates, it reduces the money supply by buying short-term mortgages (called “repurchase agreements”) from primary dealers (large banks). Under the repurchase agreement, the Fed lends US Treasury bills to each Tier 1 dealer and credits it to the other's reserve account. After the expiration of the agreement, the Fed acquires the Treasury bills in the hands of each primary dealer and writes it off from the other reserve account.",
            "4. Government intervention and currency manipulation",
            "Government intervention and monetary manipulation refer to the behavior of the government to raise or lower its monetary value through specific measures taken by the central bank in the Forex market. The so-called specific measures are divided into two types: “direct intervention” and “oral intervention”. Direct intervention refers to the government's manipulation of monetary value by buying and selling currencies on the open market. Oral intervention refers to the government’s simple verbal warning, which does not substantially interfere with market transactions. When participating in the trading of domestic currencies, the government naturally has a great possibility of manipulating the currency. But sometimes warnings alone are enough to achieve the desired goals, and the government does not have to invest a lot of money.",
            "There are two forms of direct intervention and oral intervention: coordinated intervention and unilateral intervention. Coordination intervention refers to market intervention by multiple governments in the form of direct intervention or verbal intervention. Unilateral intervention refers to the fact that a government is solely involved in currency manipulation.",
            "In the long run, coordinated intervention is more effective than verbal intervention. But what we can be sure of is that unilateral intervention can have a huge impact on the market in the short term, but the effect is not long-lasting. So why should the government intervene in the market? This is because:",
            "Worried that the currency is too strong",
            "Worried that the currency is too weak",
            "Pinning your national currency to another country's currency",
            "Worried that the currency is too strong",
            "Why is the government worried that the currency is too strong? Doesn't the strength of the currency mean that the economy is running well and the demand for money is large? The government does not seem to be worried about the strength of its currency unless exports are affected. If a country cannot export its products and services, then jobs will be reduced, and the public will begin to blame the government for helplessness. The government has decided to take measures so that politicians can keep their jobs.",
            "Worried that the currency is too weak",
            "Why is the government worried that the currency is too weak? Doesn't the weak currency mean that countries are more likely to export products and services?",
            "This is indeed the case, but excessive currency depreciation will still cause government concerns, even those with strong currencies will worry that the excessive depreciation of other currencies will make the global economy worse.",
            "Pin the national currency to another country's currency",
            "In some countries and regions, such as China, Saudi Arabia, Denmark, etc., in order to maintain their stability in the global financial market, they will peg their currency to another country's currency, such as the US dollar or the euro.",
            "Pegting one currency to another requires continued intervention and manipulation of the Forex market. At any time, as long as the demand for linked money rises, the government will increase its supply by selling and/or issuing more linked currency to stabilize the price.",
            "5. Investor panic",
            "When trading in the Forex market, you need to remember that there is one very important thing: the Forex market is made up of many people like you. The most fundamental factor driving the market forward is people, so people's emotions (especially panic) are always with the market.",
            "In today's money market, investor panic is the biggest factor. In fact, investor panic is so important that its emergence will eclipse other important factors affecting the market. When an economic crisis occurs, it can both make certain currencies plunge and allow some currencies to soar. To take advantage of this market dynamic, you must first know which currencies can thrive in times of economic depression.",
            "Safe haven currency",
            "Safe-haven currencies can thrive when investors panic. “Safe havens” are named because they provide shelter in times of financial turmoil. Safe-haven currencies include the US dollar (USD), the Swiss franc (CHF) and the Japanese yen (JPY).",
            "The reasons for their use as safe havens vary.",
            "The reason why the US dollar became a safe-haven currency is because of the security of US Treasury bonds, which can attract a large number of investors during the global economic crisis. The increase in demand for US Treasury bonds has also led to an increase in demand for US dollars, which has led to an appreciation of the US dollar. After all, who wouldn't want the safe-haven currency in their hands to appreciate when the situation is depressed?",
            "The reason why the Swiss franc is a safe haven is because most of the Swiss francs on the market are supported by gold. Although this ratio has decreased from the previous period, the Swiss franc still has fairly stable gold support compared to its legal currency. At the same time, the Swiss soil economy is considered to be very stable, and its inflation rate is usually very low.",
            "The reason why the yen will become a safe-haven currency stems from the stability of the Japanese government bond market. Unlike most US Treasury bonds, which are held by overseas governments and investors, most Japanese government bonds are held by private investors. This has added stability to the Japanese economy and has reduced the possibility of the Japanese government's inflation policy to get rid of debt – some countries do this when the debt burden is too heavy. A currency with a low inflation risk will be safer.",
            "Measuring investor panic",
            "The panic and confidence of investors is very abstract, and it is difficult to measure and analyze it because of the lack of statistical quantification. However, you can measure investor panic based on a set of data, the Chicago Board Options Exchange Volatility Index (CBOE VIX).",
            "The index is based on the level of volatility of the S&P 500 Index option.",
            "The increase in the index indicates an increase in investor panic.",
            "The decrease in the index indicates a decrease in investor panic.",
        ],
    },
    realize:{
        name1:"See clearly the Forex markets",
        name2:"—— Indicators focused by Forex traders",
        content:[
            "Volatility Index: Volatility Index from Chicago Board Options Exchange",
            "Volatility Index( VIX) from Chicago Board Options Exchange is one of the best risk and emotional assessment indicators for publics; almost all traders in Forex market will adopt this index effectively. VIX is commonly known as the \"fear index\", but in fact this term can cause some misunderstanding, because VIX does not directly measure any type of fear. The assessment of VIX is the expectation of S&P500’s volatility. This expectation is plotted in the form of an index. The higher the index, the higher the trader’s expectations for short-term market volatility.",
            "The higher the market volatility, the higher the VIX. Because VIX measures the price of the S$P 500 Index option virtual option. If the seller of the option believes that the volatility will rise in the near future, they will ask the buyer of the option for a higher option fee. The rise in the price of this option is used in the calculation of the VIX index. Conversely, if the seller of the option believes that the volatility will fall, they will lower the premium to attract the buyer. When the price of options falls, the VIX index usually shows a downward trend.",
            "On each trading day, VIX will pay attention to changes in investor sentiment and option fees in real time. The VIX reading is a revaluation of the annual rate, reflecting the traders' view of the S&P 500's ups and downs over the next 30 days. If the VIX reading is 30, or 30%, this suggests that traders believe that the S&P 500 may have a 2.5% increase or decrease (30% ÷ 12 months = 2.5%) in the next month.",
            "As VIX shows, traders' expectations are undirected. In the previous example, we can think that traders expect the S&P 500 to have a 2.5% increase or decrease in a certain direction, but it does not specify whether it is up or down. However, unexpected market volatility has a downward trend, so the rising VIX index usually means a bearish expectation. Remember, the market will not skyrocket and will only plummet.",
            "So if a trader expects a significant volatility, then this is usually a bearish sign. This is why VIX is often referred to as the fear index. If investors are concerned about rising volatility, then the VIX index will rise; on the contrary, if investors expect low volatility, then the VIX index will fall, which is also considered a bullish sign. This rule is generally followed, but if we observe it every day, we will find that there are exceptions.",
            "This meaning is obvious. If VIX is on a downward trend, investors' trades are taking a bullish strategy and are willing to take on more risks. If VIX is on the rise, traders may short the market and try to limit the risk of their portfolio. VX is usually in a certain range, so when the VIX index reaches the support or resistance level, the trader will become particularly interested.",
            "According to the VIX index, traders' feelings are very important when they are bearish or bullish, because this can indicate their attitude towards risk. Recently, the increase in investor fears has been associated with falling stocks, rising bonds and a stronger dollar. vice versa.",
            "When market risk may increase or decrease, the VIX index can be used to analyze and judge the timing or timing of entering and exiting the market. This information is very useful because it is not just a repetition of price-time research, but also from investors' expectations of recent volatility. So, what should you focus on when analyzing the VIX index? You should pay attention to:",
            "When the VIX index begins to rise, the safe haven will appreciate;",
            "High-risk, high-yielding currencies will appreciate when the VIX index begins to decline.",
            "10-year bond yield spread",
            "Pay close attention to the 10-year bond yield spreads to give you a clear understanding of future investment flows. But you can't just look for the country with the highest earnings, and expect the country's currency to continue to appreciate. You should look for countries where bond yields are increasing. Changes in bond yields can change the flow of investment, which can cause currency appreciation.",
            "For example, if you are concerned about Swiss bond yields, you find that they are steadily rising, which may be a reliable sign that the Swiss franc may appreciate. If you also find that US bond yields are starting to fall, then you should seriously consider making a deal to take advantage of the strength of the Swiss franc and the weakening of the dollar.",
            "Stock market performance",
            "Paying close attention to the performance of the stock market can also give you a clear understanding of future investment flows. But like bond yields, you can't just look for the strongest stock in the stock market, and expect the country's currency to continue to appreciate. You should look for countries where the stock market is getting stronger. Changes in stock market strength can change the direction of investment, which can cause currency appreciation.",
            "For example, if you are paying attention to the performance of the Japanese stock market, you find that the Japanese stock market has begun to rise steadily, which may be a reliable signal that the yen may appreciate. If you also find that the UK stock market is starting to fall, then you should seriously consider making a deal to take advantage of the strength of the yen and the weakness of the pound.",
            "US federal funds futures prices",
            "Traders can trade futures based on US federal funds futures prices and their expectations of changes in US federal funds rates. When traders think that the Fed will raise interest rates in the future, they will generally sell these futures contracts: When traders think that the Fed will lower interest rates in the future, they will buy these futures contracts. These contracts are a very good way for institutional traders to hedge interest rate risk and speculate on future changes.",
            "For Forex traders who want to understand long-term market expectations, the US federal funds futures price rate is very useful. If the US federal funds futures price rate is lower than the current interest rate, this indicates that traders have an expectation of lower interest rates, which is usually bad news for the US dollar. Conversely, if the US federal funds futures price rate is higher than the current interest rate, this indicates that traders have an expectation that interest rates will rise, which is usually good news for the dollar.",
            "If you are used to trading other futures contracts, then you may feel that the pricing of US federal funds futures is a bit difficult to understand at first. The price rate is calculated by 100% minus the expected federal funds rate. For example, if the current price rate is 96%, then you know that the trader expects the federal funds rate to be 4% (ie 100-96% = 4%) similar, if the federal funds futures price rate rises from 96% 98%, then this generally indicates that traders believe that the federal funds rate will fall from 4% to 2%. This change in growth is of course in the long run, and for a long time, the change in the rate of the Fed funds futures price can be in a very small range.",
            "It is important to keep in mind that the US federal funds futures price interest rate chart indicates traders' expectations for future interest rate changes, rather than current interest rates. The US federal funds futures price interest rate chart is often used by analysts and traders as a reference, and it is also a very good source to help you understand how interest rates may go. You can find the federal funds futures price interest rate chart on the Chicago Mercantile Exchange website. You can also see a lot of discussion about the predictive power of FedEx futures options on the Cleveland Fed's website.",
            "So, when you analyze the US federal funds futures price rate, what should you focus on? You should pay attention to:",
            "The dollar depreciates when interest rates begin to rise;",
            "The dollar appreciated when interest rates began to fall.",
            "Commitment of Traders (COT)",
            "Traders can get special market reports almost every week. This IE report briefly describes the positions of various commodity futures (including Forex) held by small investors in large institutional traders. This information is called a position report, or a COT, provided by the Commodity Futures Trading Commission (CFTC).",
            "Position reports are a very good analytical tool for traders in any market, as the report provides an up-to-date information on the direction of each commodity market and the traders' commitment to the trend. The position report mainly shows three different types of Net long and short positions in existing futures contracts held by traders: commercial traders, non-commercial traders and unreported traders. If traders are long, or are increasing their long positions, they are generally bullish on the market; similarly, if they are short, or are increasing their short positions, they are bearish on the market.",
            "Not all traders in the report are just as important. In fact, among the three types of traders, investors should generally focus on a type of trader who has the same needs as other individual traders – non-commercial traders.",
            "Commercial traders: These traders represent companies and institutions that use the futures market to offset the risk of cash or spot markets. For example, if the dollar depreciates in the near future, a Japanese automaker with a US company's accounts receivable may sell dollar futures contracts to protect its profits. For retail traders, such traders have little reference, so we won't pay too much attention.",
            "Non-commercial traders: These traders include large institutional investors, hedge funds, and other entities that invest in and grow in the futures market. They are usually not directly involved in the production, sale or management of basic commodities or assets. We should focus on such traders.",
            "Unreported traders: This type of coverage is very broad, mainly for small traders who have very small positions and do not need to report to the Commodity Futures Trading Commission. We don't know how many traders are included in this class or which type of investors they represent because they are not reported. Most market experts believe that the main group of such traders is individual speculators. They are famous stinkers, and you can often find that such traders are usually opposed to market trends rather than following them. We are not concerned about such traders.",
            "So, what should you focus on when analyzing your position report? You should pay attention to:",
            "When the net long position increases or the net short position decreases, the currency mentioned in the report will appreciate;",
            "When the net long position is reduced or the net short position is increased, the currency mentioned in the report will depreciate.",

        ],
    },
    main:{
        name:"Overview and characteristics of major currency pairs",
        content:[
            "1. US Dollar (USD)",
            "The United States is the world's main economic powerhouse, with a 2006 gross domestic product of more than $11 trillion. This is the world's largest GDP, three times the output of Japan, five times that of Germany and seven times that of Britain, according to the PPP model. The U.S. is a country dominated by service industries. Almost 80% of its GDP comes from real estate, transportation, finance, health care and business services. Yet America's manufacturing prowess still makes the dollar highly sensitive to developments in manufacturing. The United States has the world's most liquid stock and fixed income markets, and foreign investors have been increasing their purchases of U.S. assets. According to the international monetary fund, foreign direct investment in the us accounts for almost 40 per cent of the country's total global net inflows.",
            "Features:",
            "a. More than 90 percent of foreign exchange transactions involve dollars",
            "b. Before 9/11, the dollar was considered one of the world's premier safe-haven currencies",
            "c. The action of the dollar is opposite to that of gold",
            "d. Many emerging-market currencies are pegged to the dollar",
            "e. Pay close attention to the difference in interest rates between U.S. Treasury bills and foreign bonds",
            "f. Watch the dollar index",
            "g. The dollar trades on the influence of the stock and bond markets",
            "2. Euro (EUR)",
            "The European monetary union is the world's second largest economy, with a gross domestic product of about $12 trillion in 2006. With its highly developed fixed income market, stock market and futures market, emu is also the second most attractive investment market in the world for both domestic and foreign investors.",
            "Features:",
            "a. Euro/dollar is the most liquid currency pair and all major euro cross currency pairs are also very liquid",
            "b. The euro carries unique risks",
            "c. The spread between 10-year U.S. Treasury bills and 10-year German bunds can indicate market sentiment toward the euro",
            "d. Predict capital flows in the eurozone",
            "3. Pound sterling (GBP)",
            "With one of the world's most efficient central Banks, the UK, the world's fourth-largest economy, has experienced years of strong growth, low unemployment, capacity expansion and resilient consumption. Much of the consumer spending stems from Britain's strong housing market, which peaked in 2003. Britain is a services-led economy, with manufacturing's share of GDP shrinking to a fifth of GDP. Britain's capital market is one of the most developed in the world, so finance and banking contribute the most to Britain's GDP.",
            "Features:",
            "a. Sterling/dollar is very liquid",
            "b. The British Pound has three names: the British Pound, Sterling and Cable",
            "c. The pound is heavily exposed to speculators",
            "d. The difference in interest rates between gilts and foreign bonds should be closely watched",
            "e. Euro sterling futures can provide instructions on interest rate movements",
            "f. What British politicians say about the euro moves it",
            "g. Sterling has a positive correlation with energy prices",
            "h. Sterling related cross currency pairs",
            "4. Swiss francs (CHF)",
            "Switzerland is the world's 19th largest economy, with a GDP of more than $255 billion in 2006. It is a relatively small economy, but the richest in the world in terms of GDP per head. It is as prosperous and technologically advanced as many larger economies. Switzerland is famous for its chemical and pharmaceutical industries, machinery, precision instruments and watches. In particular, the financial system has a long history of protecting investor secrets. Together with Switzerland's long-standing political neutrality, it has created a reputation as a safe haven for the country and its currency.",
            "Features:",
            "a. The status of a safe haven",
            "b. Swiss franc is closely related to gold",
            "c. Carry trade effect",
            "d. Pay close attention to the interest difference between European franc futures and foreign interest rate futures",
            "e. The banking system may change",
            "f. Cross-border mergers and acquisitions",
            "g. Characteristics of swiss-related trading behaviors and cross-currency pairs",
            "5. Japanese yen",
            "Japan is the world's third-largest economy, with a 2006 GDP of more than $4.2 trillion (after the United States and the entire euro zone or the European monetary union) and the world's second-largest sovereign economy. Japan is also one of the world's largest exporters, exporting more than $500 billion a year.",
            "Features:",
            "a. The overall strength/weakness of Asian currencies represents",
            "b. The bank of Japan's habit of intervention",
            "c. The fluctuation of yen is very seasonal",
            "d. Bank stocks are widely followed",
            "e. Carry trade effect",
            "6. Australian dollar",
            "In terms of GDP, Australia is the fifth largest country in the asia-pacific region. In 2006, its GDP was about $674 billion. Although the economy is relatively small, on a per capita basis it is larger than many industrial countries in Western Europe. Nearly 79% of Australia's service-led GDP comes from sectors such as finance, real estate and business services.",
            "Features:",
            "a. Commodity currency",
            "b. Carry trade effect",
            "c. Drought effect",
            "d. Interest rate difference",
            "7. New Zealand dollars (NZD)",
            "New Zealand is a small economy with a GDP of about $107 billion in 2006. It used to be the most regulated country in the organization for economic co-operation and development, but over the past two decades New Zealand has gradually moved towards a more open, modern and stable economy.",
            "Features:",
            "a. It has a very strong correlation with the Australian dollar",
            "b. Commodity currency",
            "c. Carry trade",
            "d. Interest rate difference",
            "e. Immigration",
            "f. Drought effect",
            "8. Canadian dollar (CAD)",
            "Canada is the seventh-largest country in the world, with a GDP of $1178 billion in 2006. Canada's economy has grown steadily since 1991. Since Canada's early economic development was totally dependent on the exploitation and export of the country's natural resources, it is generally regarded as a resource-based economy. It is now the world's fifth largest gold producer and fourth largest oil producer.",
            "Features:",
            "a. Commodity currency",
            "b. We have a very close relationship with the United States",
            "c. Mergers and acquisitions",
            "d. Interest rate difference",
            "e. Carry trade",
        ],

    },
    go:{
        name:"Walk into currency —— 12 key questions",
        content:[
            "Money and people have the same character. Some currencies are moody, some are hyperactive and some are private. That's what makes currency markets so interesting.",
            "When you trade currencies in the foreign exchange market, you build relationships with different currencies, so you'd better understand them. As you get to know each other, you will find that some currencies are congenial to you, while others are not.",
            "To give you a better idea of money, we offer \"speed dating\" services. We have a hunch that you will be shy and embarrassed, so before you go on the date, we have prepared 12 questions for you to answer.",
            "What is so special about these questions? Why do you take the time to learn these things?",
            "First, the more you know about currencies, the easier it is to make investment choices,which is common sense. What's more, you should invest your money as carefully as possible to avoid being ruined by sudden changes. Now let's take a look at these 12 questions and see why they are relevant to your investment decisions.",
            "1. Is your economy in a trade surplus or a trade deficit",
            "The currencies of surplus countries tend to be stronger because demand for goods and services is greater in surplus countries and foreign buyers have to pay for them in the seller's currency, leading to increased demand for their money. In contrast, the currencies of trade-deficit countries tend to be weak because the buyer's country needs to convert its currency into the seller's when it pays for the goods and services it buys, so the supply of its currency rises and its value falls.",
            "2. What do you export",
            "Why should we care what products and services a country exports? This is because if we know the main goods and services that a country exports, we know what markets and prices to watch, and those markets and prices are the harbingers of changes in the country's currency.",
            "New Zealand, for example, is the world's leading exporter of dairy products, including butter, cheese, milk and milk powder. Knowing this, you should know that you need to pay attention to the price of dairy products. If the price of dairy products goes up and the importer buys the same amount of dairy products, the importer will have to exchange more nz dollars. As a result, the local currency would depreciate due to increased market supply and the New Zealand dollar would appreciate due to increased demand. On the other hand, if the price of dairy products drops and the importer buys the same amount of dairy products, the importer will have to reduce the exchange amount of nz dollars. This is likely to lead to a currency appreciation due to a slow decline in supply: the New Zealand dollar will depreciate due to reduced demand.",
            "You will find that this analysis is particularly useful for assessing the currencies of countries with commodity economies, such as Australia, New Zealand, and Canada.",
            "As learning progresses, when classifying the products and services exported by a country, we will use a classification system used by the world trade organization (WTO), which divides the products and services into the following categories:",
            "Commodity trade: agricultural products, fuels and minerals, manufactured goods",
            "Trade in commercial services: transportation, tourism, other commercial services",
            "3. To whom do you export",
            "Why should we care who a country exports its goods and services to? Because by looking at the economic health of countries that import a product from the outside, you can predict how much demand there will be for that product in the future.",
            "For example, Australia exports more goods to China than to any other country. Or to put it another way, China imports more from Australia than any other country. Either way, you can tell that China is an extremely important trading partner of Australia.",
            "With that in mind, you can start looking at China's GDP, employment, production data and so on to figure out whether China will remain Australia's largest importer in the future. If China's economic indicators are strong, Australia's exports to China will remain robust, while the demand and value of the Australian dollar will remain high. If China's economic indicators are not strong enough, then Australia's exports to China will show a downward trend, and the demand and value of Australian dollars will also decrease.",
            "4. What do you import",
            "Why should we care what products and services a country imports? Because if we know the major goods and services that a country imports, we know what markets and prices to watch, and those markets and prices are the harbingers of changes in the country's currency.",
            "Japan, for example, is a net importer of oil; in fact it is now the world's fourth-largest importer. The yen is sensitive to changes in oil prices because of Japan's heavy dependence on oil imports, which are priced in dollars. When the price of oil rises, in order to buy the same amount of oil, Japan has to increase the exchange amount of yen against the dollar, resulting in the decline of the value of yen due to the increase of supply in the market and the rise of the value of dollar due to the increase of demand. Conversely, if the price of oil were to fall, Japan would have to reduce the value of its yen against the dollar in order to buy the corresponding amount of oil. This may cause the yen to appreciate due to the slow increase in market supply and the dollar to depreciate due to the low market demand.",
            "5. Where do you import from",
            "Why should we care who a country imports its goods and services from? Because the currency value of the exporting country usually directly affects the currency value of the importing country.",
            "For example, more than half of Canada's imports of goods and services come from the United States. That said, Canada's currency and economy are highly vulnerable to the dollar. If the dollar were to rise, Canada would have to increase the amount of dollars it buys in order to buy the same number of goods and services. This would cause the Canadian dollar to depreciate due to increased supply and the dollar to appreciate due to increased demand. On the contrary, if the us dollar depreciates, in order to buy the same number of products and services, Canada needs to reduce the exchange amount of the us dollar, so that the Canadian dollar will appreciate due to the slow decline of market supply and the us dollar will depreciate due to the decline of market demand.",
            "6. Is your Treasury market attractive",
            "Why should we care whether a country's bond market is attractive? Because if a country's bond market is attractive, it usually attracts a lot of foreign investment. Normally, when investment increases, the currency appreciates as demand increases.",
            "When investment increases, the currency appreciates in response to increased demand. Investors generally consider two questions",
            "when evaluating a country's bond market:",
            "a. How big is the market risk?",
            "b. What is my expected return on investment?",
            "These two issues, while crucial, must not be viewed in isolation. For example, a country's debt market is so risky that the government may not be able to pay its debts, so it is not suitable for investors to invest. But at the same time, the country's investment rate of return is quite high, which is very attractive to investors. On the other hand, a country's debt market is low-risk and suitable for investment: but at the same time, the return on investment is not high, and investors have reasons not to invest. Therefore, investors need to weigh the two before investing.",
            "Ideally, investors would seek out countries with low default risk but high returns. But how many countries have low-risk, high-return markets? If you're balancing risk and reward, shouldn't the riskier markets have higher returns and the less risky markets have lower returns? There is no absolute \"yes\" or \"no\" to this question.",
            "A country's bond market is bound to be affected by market risk, but that is not the only factor. Whether it is to stimulate the economy or to reduce inflation, the central bank's actions largely determine the return on the Treasury market. The Australian government bond market, for example, is considered relatively safe, but as the country's economy boomed (largely because of exports of raw materials to China), its central Bank, the Reserve Bank of Australia, raised interest rates to prevent hyperinflation. The move boosted returns for investors in the Australian government bond market.",
            "Therefore, when comparing the bond markets of various countries, we should select countries with high interest rates and stable markets. When assessing the risk profile of a country's bond market, investors can look to two data points: moody's long-term debt rating and its ratio of debt to gross domestic product.",
            "Moody's long debt rating",
            "Moody's long-term debt rating is about financial debts (original maturity date) for a year or more relative to the opinions of the credit risk, which typically reveals the possibility of financial debts are unable to make promise to perform, at the same time reflects the probability of default happened and all the economic losses resulting from the breach of contract after, moody's, a rating process using the company's global rating method, its debt can be divided into the following nine grades",
            "a. Aaa: highest debt quality and lowest credit risk",
            "b. Class Aa: high debt quality and low credit risk",
            "c. Grade A: medium to high quality debt with low credit risk",
            "d. Ba grade: medium debt quality, general credit risk and uncertainty",
            "e. Ba grade: the debt is speculative with high credit risk",
            "f. Class B: the debt is speculative with high credit risk",
            "g. Caa level: poor debt quality and high credit risk",
            "h. Ca level: the debt is highly speculative, with a high possibility of default, but there is a possibility of principal and interest recovery after default",
            "i. Grade C: the lowest quality of debt, which usually leads to default. The recovery of principal and interest after default is extremely unlikely",
            "In addition, Moody's also puts Numbers 1, 2 and 3 in front of each rating category, from Aa to Caa. The number 1 indicates that the debt ranks high in its category, the number 2 indicates that the debt ranks middle in its category, and the number 3 indicates that the debt ranks low in its category.",
            "The debt-to-gdp ratio usually measures a country's level of debt. If someone has an annual income of $50,000 and an annual debt of $60,000 to pay for a house, two cars, a boat and five credit CARDS, that is a high credit risk for most financial institutions. Similarly, most financial institutions believe that a highly indebted country has a high credit risk.",
            "In general, highly indebted countries attract borrowing by raising interest rates. This helps investors balance their risk-reward ratios over the long term, but it also undermines a country's vision of low risk and high returns.",
            "7. Is your stock market attractive",
            "Why should we care whether a country's stock market is attractive? Because if a country's stock market is attractive, it usually attracts a lot of foreign investment. Normally, when investment increases, the currency appreciates as demand increases.",
            "Investors look at two issues when evaluating a country's stock market",
            "a. How big is the market risk?",
            "b. What is my expected return on investment?",
            "Stock market risk is generally affected by a variety of factors. Size matters. Compared with small and immature stock markets, large and mature stock markets (such as the United States) have a safer investment environment. Large stock markets generally have a large number of investors and different types of stocks for investors to choose from, and they are also highly liquid.",
            "Regulation of large equity markets is more effective. Companies that want to list on the New York stock exchange (NYSE), for example, face more onerous filing requirements than those listed on the Botswana stock exchange (BSE). But the more accurate the company's information, the more confident investors will be to put more money into its shares.",
            "Investors naturally weigh the risks of the stock market against the potential profits. High-return equity markets are usually risky;",
            "Conversely, for the stock market with low returns, the investment risk may not be high. Ideally, investors seek a stable stock market with high returns.",
            "8. The responsibilities of the central bank and the gold and foreign exchange reserves it holds",
            "Why should we care what a central bank is, what its responsibilities are and how much gold and foreign exchange reserves it has? Because central Banks often have more control over whether a currency is strong or weak than any other institution in a country.",
            "Fortunately, the central bank does not randomly participate in the foreign exchange market to manipulate the level of the currency. Some central Banks have been given responsibility for reining in growth, placing the burden on the economy to expand or contract too quickly; Other central Banks have been given responsibility for setting unemployment too high; There are also central Banks whose responsibilities include the first two (sometimes complex). Understanding the role of the central bank, which oversees the currencies you trade, can help you predict what Banks might do in different market situations.",
            "In addition to your responsibilities, you also need to know how much gold and foreign exchange reserves the central bank holds. The central bank's ability to intervene in the free market can be seen in its gold and foreign exchange reserves. Central Banks with small reserves often do not have enough capital to intervene in volatile foreign-exchange markets and volatile prices.",
            "In getting to know the central bank, you should pay attention to any message that the central bank is changing its composition of foreign exchange. We are seeing a gradual de-dollarization of central Banks. If this trend continues in the future, the total demand for dollars will be affected.",
            "9. Whether the government interferes too much in the foreign exchange market",
            "Why should we care if the issuing government is intervening too much in the foreign exchange market? Because the level of government activity in the foreign exchange market affects the way we trade currencies.",
            "Some governments intervene at all times because they are trying to keep their currencies pegged to one currency or a basket of currencies. There are also those who never intervene in the market, who believe that the market should follow its own path and that any form of intervention can have some adverse effects.",
            "In most cases, however, you will find it necessary for the government to intervene in the market at certain times, though not often.",
            "10. What economic data is important",
            "Why should we care what economic data is important? Because if we know what kind of economic data is important, we can watch the economic data in time to prepare for the trend.",
            "11. Is the currency a safe-haven currency",
            "Why should we care if a country's currency is a haven? This is because the ability of a currency to hedge risks affects the way currencies are traded in times of economic crisis. The Swiss franc, for example, is a haven currency, so its value usually rises as investors panic. The New Zealand dollar, for example, is not a safe-haven currency, so its value tends to fall as investor panic increases.",
            "12. How do I trade your currency",
            "Why should we care what the investment vehicle of a currency is? Because we spend a lot of time and energy learning about foreign exchange markets and the factors that affect each currency, mostly for one purpose: to make money in foreign exchange markets.Whether it's futures contracts, spot contracts, or exchange-traded funds, knowing how you can invest your money can help you decide where to put your money.",
            "Here are some investment tools to show you how to trade currencies:",
            "a. Spot foreign exchange;",
            "b. Foreign exchange futures0;",
            "c. Exchange traded funds (etfs);",
            "d. Exchange traded notes (ETN);",
            "e. Spot foreign exchange options;",
            "f. Exchange traded foreign exchange options.",
        ],
    },
}
export {
    contents,contentEn
}
