const contents = [
    {big:"A",
    long:["Accrual：累积，在每一次交易期间内，远期外汇交易所分配的升水或折扣直接关系至利益套汇交易。",
        "Account balance/account value：账户余额/账户价值在计算所有的进项和贷项后，某个账户在某个时间所持的净额。",
        "Adjustment：调整，官方行动，用于调整内部经济政策来修正国际收支或货币。",
        "AIM (Alternative Investment Market) : （另类投资市场）伦敦证券交易所 (LSE) 的子市场，小型企业在此筹资所适用的监管制度相较于伦敦证券交易所的主市场更为灵活。不提供另类投资市场上市股票的差价合约产品。",
        "Appreciation：增值,当物价应市场需求抬升时,一种货币即被称作增值，资产价值因而增加。",
        "Arbitrage：套汇，利用不同市场的对冲价格,通过买入或卖出信用工具,同时在相应市场中买入相同金额但方向相反的头寸，以便从细微价格差额中获利。",
        "Ask(Offer) Price：卖出(买入)价，在一外汇交易合同或交叉货币交易合同中一指定货币的卖出价格。以此价格，交易者可以买进基础货币。在报价中,它通常为报价的右部价格。",
        "At Best：最佳价格，一指示告诉交易者最好的买进/卖出价格。现价或更好，一交易以一特定或更理想汇率执行。",
        "AUD-Australian DollAr：澳元",
    ],
    enLong:[
        "Accrual: Generally an accounting term describing the method for recording revenues and expenses when they are incurred, regardless of when cash is exchanged. The term “accrual” refers to any individual entry recording revenue or expense in the absence of a cash transaction.",
        "Account balance/account value: In the most basic sense is the amount of money held in financial repository at any point in time.",
        "Adjustment: Official action used to adjust internal economic policies to correct the international balance of payments or currency.",
        "Appreciation: When prices rise in response to market demand, a currency is called appreciation and the value of assets increases.",
        "AIM (Alternative Investment Market): AIM (formerly the Alternative Investment Market) is a sub-market of the London Stock Exchange. It allows smaller, less-viable companies to float shares with a more flexible regulatory system than is applicable to the main market.",
        "Arbitrage: Use hedging prices in different markets in order to profit from small price differentials by buying or selling credit instruments and simultaneously buying the same amount but in opposite directions in the corresponding market.",
        "Ask(Offer) Price: The sell price of a specified currency in a foreign exchange contract or cross-currency contract at which a trader can buy the base currency, usually at the right side of the quoted price.",
        "At Best: The best price, an indication tells the trader the best buy/sell price. Current price or better, a transaction is executed at a specific or better exchange rate.",
        "AUD: Australian Dollar.",
    ],
    },
    {big:"B",long:[
        "Backwardation：现货溢价。该理论指由于期货合约期限将至，将以高于到期后价格的价格进行交易。亦请参阅“期货溢价",
        "Balance of trade：国际收支，指一国承认的,在一定时期内对外交易的记录包括商品、服务和资本流动。",
        "Bar Chart：棒形图表,一种由4个突点组成的图表:最高和最低价格组成垂直棒状，被一小水平线标志于棒形的左端为开市价格,右端的小水平线则为关市价格。",
        "Base Currency：基础通,其他货币均比照其进行报价的货币。它表示基础货币相对第二种货币的价值。",
        "Base rate：基准利率某个国家/地区中央银行所确定的贷款利率。",
        "Basis point：基准点通常为万分之一或0.01%，比如降息50个基准点即为降息0.5%。",
        "Bear market：熊市，以长时期下跌的价格为特征的市场。",
        "Bid：买入价。买家愿意购买产品的最高价称为“买入价”。亦请参阅“卖出价”。",
        "Bid-offer spread：买卖差价。产品购买价（卖出价）及售出价（买入价）之间的差价。",
        "Bid Price：买入价，该价格是市场在一外汇交易合同或交叉货币交易合同中准备买入一货币的价格。",
        "Bid/ Ask Spread：差价，买人与卖出价格的差额。",
        "Big Figure Quote：大数，交易员术语，指汇率的头几位数字。",
        "Blue chip：蓝筹。蓝筹企业通常地位稳固，财务稳健，更能抵御经济萧条。因此蓝筹股被认为更加稳定。列于某个国家/地区顶级股票指数（如英国富时100指数）的企业被视为蓝筹。",
        "Book：账本，在专业交易环境中,账本是交易商或者交易柜台全部头寸的总览。",
        "Bollinger Bands：布林线。在技术分析中用于衡量市场波动的图表指标，由一条移动平均线和两条标准差线组成。",
        "Bull Market：牛市，以长时期上涨价格为特征的市场。",
        "Bullion：贵金属。贵金属条或锭，如金、银、铂或钯。",
        "Bundes bank：联邦银行，德意志联邦银行。",
        "Buy limit order：买入限价订单该附带条件的交易订单仅可按指定价格或更低的价格购买证券。亦请参阅“止盈订单”。",
        "Buy position：多头头寸市价上涨时获利或市价下跌时亏损的市场头寸。",
        "Buy stop-entry order：买入止损挂单。",
        "Breakout trading：突破交易该交易策略建议一旦价格突破指定的阻力位或支撑位则进行点差交易或差价合约交易。当价格突破阻力位时买入，当价格突破支撑位时卖出。这些策略认为，一旦价格突破支撑或阻力位，很可能开始出现新的趋势。",
        "Broker： 经纪商为促成买卖双方交易充当中介角色的个人或公司，通常收取小额佣金或费用。",
    ],
    enlong:[
        "Backwardation: As a futures contract approaches to the end, it will trade at a price higher than its expiration price.",
        "Balance of trade: It refers to the record of external transactions recognized by a country within a certain period, including goods and services and capital flows.",
        "Bar Chart: A chart with four spikes: the top and bottom prices form a vertical bar, marked by a small horizontal line on the left side of the bar as the opening price, and a small horizontal line on the right side as the closing price.",
        "Base Currency: All other currencies are quoted in terms of the currency in which they are quoted which represents the value of the base currency relative to the second currency.",
        "Base rate: The interest rate set by a country or region central bank for loans.",
        "Basis point: The base point is usually one in ten thousand or 0.01%, for example, a 50 basis point cut in interest rates is a 0.5% cut.",
        "Bear market: A market characterized by a long period of falling prices.",
        "Bid: The highest price that a buyer would pay for a product.",
        "Bid-offer spread: The difference between the buying price (selling price) and the selling price (buying price) of a product.",
        "Bid Price: The price at which the market is prepared to buy a currency in a foreign exchange or cross-currency transaction contract.",
        "Bid/ Ask Spread: the difference between the buying price and the selling price.",
        "Big Figure Quote: Trader term, the first digits of an exchange rate.",
        "Blue chip: Blue-chip companies are generally stable, financially sound, and more resilient to economic depression. Therefore, blue chip stocks are considered to be more stable. Companies listed in a country's top stock index (such as the UK FTSE 100 Index) are considered blue chips.",
        "Book: In a professional trading environment, book is an overview of the entire position of a dealer or a trader counter.",
        "Bollinger Bands: A chart that indicator used in technical analysis to measure market volatility consisting of a moving average line and two standard deviations lines.",
        "Bull Market: A market characterized by a long period of rising prices.",
        "Bullion: Precious metal. A precious metal strip or ingot such as gold, silver, platinum or palladium.",
        "Bundesbank: German Federal Bank.",
        "Buy limit order: Trade order with buy limit condition can only buy a security at a specified price or less.",
        "Buy stop order: A buy stop order instructs a broker to purchase a security when it hits a strike price that is higher than the current spot price. Once the price hits that strike, the buy stop becomes a market order, fillable at the next available price.",
        "Breakout trading: The strategy suggests a spread or CFD trade once a price breaks through a specified resistance or support level. Buy when price breaks resistance level and sell when price breaks support level. Once prices break through support or resistance levels, it is likely that new trends will begin to emerge.",
        "Broker: A person or company that acts as an intermediary between buyers and sellers, usually for a small commission or fee.",
    ],
},
    {big:"C",long:[
        "Cable：英镑兑美元汇率,交易商针对英国英镑的行话,指英镑兑美元的汇率。",
        "CAC 40：在巴黎股票交易所上市的前40大公司的市值加权指数。CAC指数由Societe des Bourse Francaises发布。",
        "CAD-Canadian Dollar：加拿大元。",
        "Candlestick Chart：烛台图表，表示当日成交价格幅度以及开盘及收盘价格的图表。",
        "Capital：资本。由个人或公司持有的财富（货币或资产）。",
        "Carry cost：持有成本。持仓产生的成本（如 纳入大宗商品期货价格的套息成本包括保险成本、存储成本、利息费用和其他相关费用）。",
        "Carry trade：套息交易。该策略指交易者卖出低利率的特定货币并利用该资金来购买利率更高的其他货币，以获得利率之间的差额。常见的低收益货币包括美元和日元，常见的高收益货币包括澳元和新西兰元。",
        "Cash market：现金市场，是以期货或期权为实际操作的金融工具的市场。",
        "Cash price：现金价格。可立即交付的资产价格。亦可称为资产的现行实际价格。该术语通常用于股票指数，而同义术语现货价格通常用于外汇和大宗商品价格。亦请参阅“现货汇率”。",
        "Central bank：中央银行，管理一国货币政策并印制一国货币的政府或准政府机构，比如美国中央银行是联邦储备署,德国中央银行是联邦银行。",
        "Channel：轨道。图表中由两条直线标示界限的向上或向下的趋势。向上或向上突破轨道线表明可能出现趋势变化。",
        "Charting：制图。利用过去的价格图表以及其他指标预测未来价格走势的一系列技巧。",
        "Chartist：图表专家，使用图表和图形，解释历史数据,以便能找到趋势，预测未来走势，并协助技术分析的人。也可称为技术交易员。",
        "CHF-Swiss franc：瑞士法郎。",
        "Cleared Funds：清算资金，能立即使用的现金，被用于支付交易。",
        "Closed position: 关单价位，外汇的交易已不再存在。一关单过程为卖出或买进货币来抵消同等数量的现有交易。",
        "Close out：结清。卖出多头仓位或买入空头仓位进行平仓，以不再面临市场价格变动的风险。",
        "Closing price：收盘价：闭市时可交易金融产品的最终价格。",
        "Collateral：抵押，被用来作为贷款担保或执行保证的有价值的东西。",
        "Commission：佣金，由经纪人收取的交易费用。",
        "Confirmation：确认书、由交易双方交换、确认交易的各项条款的交易文件。",
        "Consumer Price Index (CPI)：消费物价指数(CPI)。衡量消费者所购买商品和服务的价格变动的指标。该数据衡量由具代表性的城镇居民所消费的各种常见商品及服务项目的价格水平随时间的平均变化。",
        "Contagion：金融风暴，经济危机从一个市场蔓延至另一个市场的趋势。",
        "Contract (unit or lot)：成交单位或手。部分交易所的标准交易单位。对股票指数、外汇和大宗商品仓位来说，它是市场点位每次变动以基础货币计值的盈利或亏损金额单位。",
        "Contract for difference (CFD)：差价合约(CFD)。差价合约 (CFD) 是一种金融衍生产品，让您可对标的金融资产（如股指、股票和大宗商品）的价格变动进行交易。这是交易员与供应商之间的协议，即交换某项资产从合约开口到关闭之间的价值差额。进行差价合约交易时，您并不实际拥有选择交易的资产或金融工具，但如果市场变动符合您的预期仍可获利。",
        "Controlled risk：受控风险。通过保证止损严格限制最高损失的仓位。亦请参阅“有限风险”。",
        "Contract：合约或单位，外汇交易的标准单位。",
        "Core inflation：核心通胀。剔除受价格走势波动影响的项目后的通胀度量。比如蔬菜价格易受到季节性条件而产生变动。这些产品不在计算范围内，因为它们的价格会偏离总体走势，从而造成通胀度量错误。",
        "Corporate Action：公司行为。股份公司发起的可影响股东的任何事项。对于某些事项，股东可能或必须对公司行为做出回应或从一系列可选行动中选出要做出的行动。公司行为示例包括股息支付、并购、股票认购权发行和股票分割。亦请参阅“股息和股票认购权发行”。",
        "Counter Currency：相对货币、成对货币中的第二个货币。",
        "Counterparty：交易对方，外汇交易中的其一参与者。",
        "Country Risk：国家风险,与政府干预相关的风险(不包括中央银行干预)。",
        "Cross Curreney Pairs or Cross Rate：交叉配对货币/交叉货率，在外汇交易中外汇与另一外汇之交易。",
        "Cross rate：交叉汇率。两种货币之间的兑换率，但两种货币均不得是报价所在国家/地区的官方货币。亦请参阅不涉及美元的货币报价。",
        "Crossed price：交叉价格。买入价超过卖出价的情况。这通常表明处于拍卖期的地点或市场发生某个事件。",
        "Cunrrency Symbol：外汇符号。",
        "Currency：货币，由一国政府或中央银行发行的该国交易单位,作为法定货币及交易之基本使用。",
        "Currency Pair：对货币，由两种货币组成的外汇交易汇率。",
        "Currency Risk：货币风险，由于汇率的反向变化而导致蒙受损失的风险。",
    ],
    enlong:[
        "Cable: The exchange rate of the British pound against the U.S. dollar.",
        "CAC 40: The CAC index of the top 40 listed companies by market capitalization on the Paris stock exchange, which is published by Societe des Bourse Francaises.",        
        "CAD: Canadian Dollar.",        
        "Candlestick Chart: A chart showing daily transaction range and the closing and opening prices.",        
        "Capital: Wealth (money or assets) held by an individual or company.",        
        "Carry cost: Cost of holding a position (such as the carry cost of commodity futures prices include insurance cost, storage cost, interest expense and other related expenses).",        
        "Carry trade: The strategy involves a trader selling a specific currency with low interest rates and using the funds to buy other currencies with higher interest rates in order to get the difference between interest rates. Common low-yielding currencies include the U.S. dollar and the Japanese yen, while common high-yielding currencies include the Australian dollar and the New Zealand dollar.",        
        "Cash market: A market for financial instruments in which futures or options are traded.",        
        "Cash price: The price of an asset that can be delivered immediately can also be called the current actual price of the asset. The term is usually used for stock indices, while the synonym spot price is usually used for foreign exchange and commodity prices.",        
        "Central bank: A governmental or quasi-governmental institution that manages the monetary policy of a country and prints its currency. For example, the U.S. central bank is the Federal Reserve and the German central bank is Bundesbank.",        
        "Channel: An upward or downward trend in a chart marked by two straight lines and when they go upward or break an upward trajectory, it indicates a possible trend change.",        
        "Charting: A series of techniques for predicting future price movements using past price charts and other indicators.",        
        "Chartist: A chartist who uses charts and graphs to interpret historical data in order to find trends, predict future trends, and assist with technical analysis. Also called a technical trader.",        
        "CHF: Swiss franc.",        
        "Cleared Funds: Liquidation funds, cash that can be used immediately to pay for transactions.",        
        "Closed position: Foreign exchange transaction is closed, the currency is bought or sold to offset the same amount of existing transactions.",        
        "Close out: Sell long positions or buy short positions to cover positions to prevent from the risk of market price changes.",        
        "Closing price: The final price of a tradable financial product at market closing.",        
        "Collateral: Something of value used as a loan guarantee or enforcement guarantee.",        
        "Commission: A transaction fee charged by a broker.",        
        "Confirmation: A transaction document in which the parties exchange terms confirming a transaction.",        
        "Consumer Price Index (CPI): A indicator that measures the changes in the prices of goods and services purchased by consumers. This data measures the average change over time in the prices of various common goods and services consumed by urban residents, a representative group.",        
        "Contagion: The tendency of an economic crisis to spread from one market to another.",        
        "Contract (unit or lot): The standard trading unit on some exchanges. For stock index, forex and commodity, it is the unit of profit or loss in the base currency for each change in the market point position.",        
        "Contract for difference (CFD): In finance, a contract for difference (CFD) is a contract between two parties, typically described as \"buyer\" and \"seller\", stipulating that the seller will pay to the buyer the difference between the current value of an asset and its value at contract time.",        
        "Controlled risk: Strictly limit the position with the highest loss by ensuring stop loss.",        
        "Contract: Standard unit of forex trading.",        
        "Core inflation: Core inflation is the change in costs of goods and services, but does not include those from the food and energy sectors. This measure of inflation excludes these items because their prices are much more volatile. It is most often calculated using the consumer price index (CPI).",        
        "Corporate Action: Any matter initiated by a corporation which may affect shareholders. For certain matters, shareholders may or must respond to corporate actions or select actions to be taken from a series of optional actions. The corporate include dividend payment, merger and acquisition, issuance of stock options and stock split.",        
        "Counter Currency: The second currency in a counter currency, currency pairs.",        
        "Counter party: One of the participants in a foreign exchange transaction.",        
        "Country Risk: Risk associated with the government intervention.",        
        "Cross Currency Pairs or Cross Rate: A currency pair is the quotation of the relative value of a currency unit against the unit of another currency in the foreign exchange market. The currency that is used as the reference is called the counter currency, quote currency or currency and the currency that is quoted in relation is called the base currency or transaction currency.",        
        "Cross rate: The exchange rate between the two currencies, but neither currency must be the official currency of the country where the quote is located.",        
        "Crossed price: A condition in which the bid exceeds the offer price. This usually indicates that an event has occurred at a place or market during the auction period.",        
        "Currency Symbol: A currency symbol is a graphic symbol used as a shorthand for a currency's name, especially in reference to amounts of money.",
        "Currency: A national unit of exchange issued by a government or central bank and used as legal tender and as the basis for transactions.",        
        "Currency Pair: Foreign exchange rate consisting of two currencies.",        
        "Currency Risk: The risk of loss due to adverse exchange rate changes.",    
],
},
    {big:"D",long:[
        "Daily charts：每日图表。包含金融产品每日价格走势的图表，比如货币对、指数或股票。",
		"Data releases：数据发布。通常情况下会定期发布全球经济统计数据，通常每月一次。该数据可对金融市场产生不同的影响，取决于发布时间、所提供的经济卓见水平以及其他因素。",
        "DAX 30：在德国法兰克福股票交易所上市的前30大公司的市值加权指数。",
        "Day Trader：日内交易员,投机者在商品交易中的同一交易日内先于最后交易时限清算价位。",
        "Day trading：日间交易。在同一天或同一个交易期内进场和退场交易的过程。",
        "Day order：当日订单。买入或卖出金融产品的订单，如果在下单当日没有执行订单将会在当日结束后自动过期。",
        "Dealer：交易员,在交易中充当委托人或者交易对方角色的人。",
        "Dealing spread：交易价差。合约买入价和卖出价之间的差价。",
        "Deficit：赤字,贸易(或者收支)的负结余,支出大于收入/收益。",
        "Delivery：交割,交易双方过户交易货币的所有权的实际交付行为。",
        "Depreciation：贬值,由于市场供需作用,货币价值下跌。",
        "Deposit：定金。发起和维系敞口价差赌注或差价合约买卖仓位所需的资金。由于点差交易和差价合约按保证金交易，定金仅为全部交易值的一小部分，而非交易中全部可亏损的数额。",
        "Depreciation：贬值。资产价值下降。",
        "Derivative：衍生工具,由另一种证券(股票、债券、货币或者商品)构成或衍生而来的交易。",
        "Devaluation：贬值,通常因官方公告引起的一种货币币值对另一种货币币值的刻意下调。",
        "Diversification：多元化。通过投资者交易组合的多样化管理风险的投资战略。由于从各不同的行业选出不同的组成部分，因此不太可能所有投资都会出现同一方向的波动。其认为比起投资组合的单一组成部分，投资组合整体将得出更为一致稳定的结果。",
        "Dividends：股息。股息为由董事会决定向一类股东分配的部分公司收益。股息可以现金、股票或其他财产的方式分配。",
        "Dove：鸽派。鸽派与鹰派对立，指鼓吹低利率是一种经济刺激手段、奉行传统经济政策的经济政策顾问。",
        "Dow Jones Industrial Average (DOW)：道琼斯工业平均指数 (DOW)。道琼斯指数是美国第二个最悠久的股票市场指数，是美国股票市场整体状况的最广泛使用的指标。它选出美国30家蓝筹国有企业并对其业绩进行度量。",
        "Downtrend：下降趋势。",
    ],
    enlong:[
        "Daily charts: A chart containing the daily price movements of a financial product, such as a currency against an index or stock.",
		"Data releases: Global economic statistics are regularly released, usually monthly, which have a different impact on financial markets depending on the level of economic insight release date, and other factors.",
        "DAX 30: A Capitalization-weighted Index of the top 30 companies listed on the Frankfurt stock exchange in Germany.",
        "Day Trader: The speculator clears the price before the last trading time on the same trading day in the commodity transaction.",
        "Day trading: The process of entering and exiting a trade on the same day or within the same trading period.",
        "Day order: An order to buy or sell a financial product which will automatically expire at the end of the day if it is not executed on the day the order was placed.",
        "Dealer: One who acts as principal or counter party in a transaction.",
        "Dealing spread: The difference between the buying price and the selling price of a contract.",
        "Deficit: Deficit, negative balance of trade (or income and expenditure), expenditure is greater than income/revenue.",
        "Delivery: The actual delivery of the ownership of a currency by both parts.",
        "Depreciation: Currency value falls because of the effect of market supply and demand.",
        "Deposit: A foreign exchange account, or Forex account, is used to hold and trade foreign currencies. Typically, you open an account, deposit money denominated in your home country currency, and then buy and sell currency pairs.",
        "Depreciation: Depreciation. The value of assets has fallen.",
        "Derivative: A transaction consisting of or derived from another security ( stock, bond, currency, or commodity).",
        "Devaluation: A deliberate lowering of the value of one currency against another, usually as a result of an official announcement.",
        "Diversification: Investment strategy of risk management through diversification of investors &#39; trading portfolios. Since different components are selected from different industries, it is unlikely that all investments will show the same direction fluctuations. It is believed that the overall portfolio will achieve more consistent and stable results than a single component of the portfolio.",
        "Dividends: A portion of a company &#39; s earnings that the board of directors decides to distribute to a class of shareholders. Dividends may be distributed in cash, stock or other property.",
        "Dove: Dovish versus hawkish: economic policy advisers who advocate low interest rates as a means of economic stimulus and pursue traditional economic policies.",
        "Dow Jones Industrial Average (DOW): Sometimes referred to as simply the Dow, is one of several well-known stock market indices. The DJIA was created by Charles Dow, founder of the Wall Street Journal, to measure the daily stock price movements of 30 large, publicly-owned U.S. companies.",
        "Downtrend: A downtrend occurs when the price of an asset moves lower over a period of time. While the price may move intermittently higher or lower, downtrends are characterized by lower peaks and lower troughs over time.",

    ],
},
    {big:"E",long:[
        "Economic driver：经济驱动因素。造成投资（如股票、大宗商品或物业）市价变动的经济变动。",
        "Economic Indicator：经济指标,由政府或者非政府机构发布的,显示当前经济增长率以及稳定性的统计数字。",
        "Electronic Currency Network (ECN)：电子货币网络 (ECN)。用于外汇交易的虚拟交易。",
        "Elliot wave theory：艾略特波浪理论。该理论由RN Elliott提出，其为基于可预见性的假设借由识别金融产品价格走势的特定流动和结构的技术分析方法。",
        "End of Day Order(EOD)：结束日订单,以一个指定的价格买入或卖出订单。",
        "Euro：欧元。欧元区货币单位。",
        "European Monetary Union(EMU)：欧洲货币联盟,欧洲货币联盟的主要目标是要建立名为欧元的单一欧洲货币。",
        "European Central Bank(ECB)：欧洲中央银行,欧洲货币联盟的中央银行。",
        "Equity：权益。代表所有权益的股票或股份。",
        "Ex-dividend date：除权日。股份买方不再有权获得当前股息支付的首个交易日。",
        "Exchange：交易所。证券、大宗商品、衍生品和其他金融产品交易的市场。交易所（比如股票交易所）的核心功能是确保交易公平有序并为交易所的任何证券交易提供有效的价格信息传播。交易所给公司、政府和其他团体提供向投资大众销售证券的平台。交易所可为交易者会面开展业务的实际场所或为电子平台。",
        "Execute and eliminate order：执行和撤销订单。执行当前市价或更低价的限价订单。若订单没有完全达到指定的订单水平，任何余下的结余将会被取消。",
        "Execution-only stockbroker：仅执行股票经纪人。为客户提供廉价的交易设施但不会提供有关投资方式或政策的建议、研究或提议的股票经纪人。",
        "Expiration date：到期日。特定合约交易的最后一天。",
        "Expiration/ Expiry：到期/过期。一些价差赌注或差价合约市场有一个固定期限。例如期货合约将在未来预定的日期和时间到期。到期后可以说期货合约已过期并待交收。交收与合约到期时的达成程度有关，一般会涉及到期时的市场情况。",
        "Exposure：风险。风险投资水平。风险越高，潜在损失或收益越大。",
    ],
    enlong:[
        "Economic driver: An economic change that causes a change in the market price of an investment, such as a stock, a commodity, or a property.",
        "Economic Indicator: Statistics released by the government or non-governmental organizations showing the current economic growth rate and stability.",
        "Electronic Currency Network: Virtual transaction used to forex transaction.",
        "Elliott wave theory: A method of market analysis, based on the idea that the market forms the same types of patterns on a smaller time frame (lesser degree) that it does on a longer time frame (higher degree). These patterns provide clues as to what might happen next in the market.",
        "End of Day Order(EOD): To buy or sell an order at a specified price.",
        "Euro: Currency unit of euro religion.",
        "European Monetary Union(EMU): The main goal of European monetary union is to create a single European currency called the euro.",
        "European Central Bank(ECB): The central bank of the European monetary union.",
        "Equity: Stock or share representing all equity.",
        "Ex-dividend date: The first trading day on which the share buyer is no longer entitled to the current dividend payment.",
        "Exchange: Securities, commodity, derivatives and other financial products trading market. Exchange (such as stock exchanges) core function is to ensure that trade fair and orderly and to provide effective price for any securities trading exchange information. Exchange provide company, government and other groups a public platform to sell securities and also for traders the actual place and electronic platform to do business.",
        "Execute and eliminate order: Limit orders at current market price or lower. Any remaining balance will be canceled if the order does not fully meet the specified order level.",
        "Execution-only stockbroker: A stockbroker who provides clients with cheap trading facilities but does not provide research or advice on investment methods or policies.",
        "Expiration date: The last date of specific trading contract.",
        "Expiration/ Expiry: Some spread betting or CFD markets have a fixed term such as futures contracts that will expire at a predetermined date and time in the future.",
        "Exposure: The investment risk level. The higher the risk, the greater the potential loss or gain.",

    ]
},
    {big:"F",long:[
        "Fair value：公允价值。期货合约对其标的现货/现金金融产品的溢价（或贴现），一般包含利息和股息部分。公允价值指期货合约的合理定价，从而不会在期货和现金中产生套利机会。",
        "Federal Deposit Insurance Corporation(FDC)：联邦存款保险公司,美国负责管理银行存款保险的管理机构。",
        "Federal reserve(Fed)：联邦储备署,美国中央银行。",
        "Fibonacci：斐波那契交易中用来识别未来价格走势的技术分析比率，以数学家列奥纳多斐波那契 (Leonardo Fibonacci) 的名字命名。最出名的斐波纳契工具是斐波纳奇回调线和扩展线。",
        "Fill or kill order：全数执行或立刻取消订单该限价订单仅在可以于指定订单水平全部成交时才会被执行。若没有达到此条件订单将会被撤销。",
        "Fill：全数执行。执行订单。",
        "Financial Conduct Authority (FCA)：金融行为监督局 (FCA)在英国负责监督金融服务公司的机关。金融行为监督局的作用之一是监管证券、期权、股票、点差交易和差价合约经纪人和交易商的行为，以使客户可以公平交易。",
        "Financing costs：融资成本。差价合约及价差赌注股票的隔夜仓位会产生仓位全额的融资成本。如果以5%的保证金建仓，隔夜融资将按全部余额进行计算。持有多头头寸的客户将支付利息； 空头头寸的客户可能会收到利息。",
        "First In First Out(FIFO)：根据FIFO会计法则,所有货币对交易头寸必须清算。",
        "Fiscal policy：财政政策。财政政策是指政府的开销政策，会对整体经济产生重大影响。该政策影响到政府的收入和支出。当政府赤字（开销大于收益）时，经济投入将大于支出并计入国内生产总值 (GDP)。",
        "Flat/ square：持平/或者轧平—如既没有多头也没有空头,即相当于持平或者轧平。",
        "Flexible spread：灵活价差。经纪人可根据市况调整买入价和卖出价的差额。亦可称为动态价差、浮动价差或可变价差。",
        "Floating profit/ loss：浮动损益。按当前价格计算的未平仓头寸流动损益。",
        "Foreign Exchange：外汇，( Forex,FX)在外汇交易场中同时买入一种货币并卖出另一种货币。",
        "Forward：远期交易，将在未来约定日期开始的交易。",
        "Forward Points：远期点数，为计算远期价格，加入当前汇率或从当前汇率中减去的点数。",
        "Free margin：建仓保证金。可用于建仓的交易账户资金。其按账户总值减所需保证金计算。",
        "FTSE 100：英国富时100指数。在伦敦股票交易所上市的前100大公司的市值加权指数。其常作为评估英国大体市场的指标。",
        "Fundamental Analysis：基本面分析，以判断金融市场未来走势为目标，对经济政治数据的透彻分析。",
        "Futures( Contract）：期货，一种在将来某个日期以特定价格交易金融工具或者商品的方式。",
    ],
    enlong:[
       "Fair value: The sale price agreed upon by a willing buyer and seller, assuming both parties enter the transaction freely and knowledgeably. Many investments have a fair value determined by a market where the security is traded. Fair value also represents the value of a company’s assets and liabilities when a subsidiary company’s financial statements are consolidated with a parent company.",
       "Federal Deposit Insurance Corporation(FDC): The Federal Deposit Insurance Corporation (FDIC) is a United States government corporation providing deposit insurance to depositors in U.S. commercial banks and savings institutions.",
       "Fed: Federal reserve, American central bank.",
       "Fibonacci: A Fibonacci retracement is a term used in technical analysis that refers to areas of support or resistance.",
       "Fill or kill order: An order to buy or sell a stock that must be executed immediately—a few seconds, customarily—in its entirety; otherwise, the entire order is cancelled; no partial fulfillment are allowed.",
       "Fill: Execute order.",
       "Financial Conduct Authority (FCA): A financial regulatory body in the United Kingdom, but operates independently of the UK Government, and is financed by charging fees to members of the financial services industry.",
       "Financing costs: Also known as the cost of finances (COF), is the cost, interest, and other charges involved in the borrowing of money to build or purchase assets.",
       "First In First Out(FIFO): \"FIFO\" stands for first-in, first-out, meaning that the oldest inventory items are recorded as sold first but do not necessarily mean that the exact oldest physical object has been tracked and sold. In other words, the cost associated with the inventory that was purchased first is the cost expense first.",
       "Fiscal policy: Fiscal policy refers to the use of government spending and tax policies to influence economic conditions, including demand for goods and services, employment, inflation and economic growth.",
       "Flat/ square: Where a client has not traded in that currency or where an earlier deal is reversed thereby creating a neutral (flat) position.",
       "Flexible spread: Brokers may adjust the difference between the bid price and the offer price depending on market conditions.",
       "Floating profit/ loss: Floating Profit or Loss is the profit or loss that a trader has when they hold an open position. It floats (changes) since it changes in correspondence with the open position(s). Thanks to floating profit or loss, a trader can keep track of how their open positions are doing and see when he should close them.",
       "Foreign Exchange: Buying one currency and selling another in a foreign exchange market.",
       "Forward: A transaction that will commence on a future agreed date.",
       "Forward Points: In currency trading, forward points are the number of basis points added to or subtracted from the current spot rate of a currency pair to determine the forward rate for delivery on a specific value date.",
       "Free margin: Free margin is the difference of your account equity and margin used for the open positions. When you have no positions then no money from your account is used for margin.Therefore, all the money you have in your account is free. The formula is: Free Margin= Equity - Margin.。",
       "FTSE 100: The Financial Times Stock Exchange 100 Index, also called the FTSE 100 Index, FTSE 100, FTSE, or, informally, the \"Footsie\", is a share index of the 100 companies listed on the London Stock Exchange with the highest market capitalization.",
       "Fundamental Analysis: The examination of the underlying forces that affect the well being of the economy, industry groups, and companies. As with most analysis, the goal is to derive a forecast and profit from future price movements.",
       "Futures(Contract): A futures contract is a legal agreement to buy or sell a particular commodity or asset at a predetermined price at a specified time in the future. Futures contracts are standardized for quality and quantity to facilitate trading on a futures exchange.",

    ],
},
    {big:"G",long:[
        "G7：7个领先工业国家:美国、德国、日本、法国、英国、加拿大、意大利。",
        "Gapping：缺口。市场交易以偏离先前交易价的价格进行而没有出现以干预价格进行交易的现象； 其常常（但不一定）与闭市一段时间后市场重新恢复交易时相关。亦请参阅“滑点”。",
        "GBP- British pound：英镑。",
        "Gearing： 杠杆比率。杠杆比率是对所用杠杆的度量，通常用百分比表示。高杠杆交易需要的首次支出少于交易的名义价值，可被视为高风险。小规模的价格走势可创造放大的收益或亏损，因此亏损可超过投入的定金。亦请参阅“杠杆”。",
        "Going Long：买涨,对股票、商品和货币作为投资或投机的购买。",
        "Going Short：卖空,卖出不属于卖方的货币或金融工具。",
        "Good-for-day (day order)：即日有效订单（即日订单）。当天过去之前没有被全数执行将会失效的订单类型。亦请参阅“待建订单”、“取消前有效”、“全数执行”。",
        "Good-till-cancelled (GTC)： 取消前有效 (GTC)。与即日有效订单不同，取消前有效订单除非在全数执行前被取消，否则将会在账户上一直等待全数执行。亦请参阅“待建订单”、“即日有效订单”、“全数执行”。",
        "Greenback：绿币。美元的俚语。",
        "Gross Domestic Product (GDP)：国内生产总值,一国的总生产量,收入及支出。",
        "Gross National Product：国民生产总值,国内生产总值加上国际投资,交易收入。",
        "Guaranteed stop-loss order (GSLO)：保证止损订单。该止损订单可在市场触及“止损”价时进行买卖，从而限制亏损。与标准止损订单不同，保证止损订单不受滑点或缺口影响且能保证买卖中将要平仓的价格。向我们下达保证止损订单时需要支付费用；不过如果保证止损订单没有被执行而出现平仓，我们会返还100%的费用。",
   
    ],
    enlong:[
        "G7: 7 leading industrial countries: USA, Germany, Japan, France, UK, Canada, Italy.",
        "Gapping: Gapping is when a stock opens significantly above or below the previous day’s close with no trading activity in between. Partial gapping occurs when the opening price is higher or lower than the previous day’s close but within the previous day’s range. Full gapping occurs when the open is outside of the previous day’s range.",
        "GBP: British pound.",
        "Gearing: When a trader is trading on partial debt, or margin.",
        "Going Long: buying up, the purchase of stocks, commodities, and currencies as investments or speculation.",
        "Going Short: Short selling, the selling of money or financial instruments that do not belong to the seller.",
        "Good-for-day: Orders that have not been fully executed before the end of the day will be invalidated.",
        "Good-till-cancelled (GTC): Good ’til canceled (GTC) describes an order an investor may place to buy or sell a security that remains active until either the order is filled or the investor cancels it.",
        "Greenback: A greenback is a slang term for U.S. paper dollars.",
        "GDP: Gross Domestic Product.",
        "Gross National Product: Gross national product, gross domestic product plus international investment, transaction income.",
        "Guaranteed stop-loss order (GSLO): Guaranteed stop-loss orders(GSLOs) work exactly the same as regular stop-loss orders except that, for a small premium charge, they guarantee to close you out of a trade at the price you specify, regardless of market volatility or gapping.",

    ],
},
    {big:"H",long:[
        "Hawk, hawkish：鹰派。支持较高利率可控制通胀或遏制经济的快速增长观点的经济政策顾问。亦请参阅“鸽派”。",
        "Hedge：对冲,用于减少投资组合价值易变性的投资头寸或者头寸组合。",
        "Hit the bid：达到买价,在一买价价位上交易被执行。",
        "Holding costs：持仓成本。超过纽约时间17:00后仍未平仓会产生持仓成本。这些持仓成本将基于仓位总规模计算。亦请参阅“融资成本”。",
    ],
    enlong:[
        "Hawk, hawkish: A hawk, also known as an inflation hawk, is a policymaker or advisor who is predominantly concerned with interest rates as they relate to fiscal policy. A hawk generally favors relatively high interest rates in order to keep inflation in check.",
        "Hedge: A hedge is an investment to reduce the risk of adverse price movements in an asset. Normally, a hedge consists of taking an offsetting position in a related security.",
        "Hit the bid: Hit the bid is a buzzword used to describe an event where a trader agrees to sell at a bid price quoted by another trader. The \"bid-offer\" (or \"bid-ask\") quote is controlled by a broker, or market maker, who collects commission based on the bid-offer spread.",
        "Holding costs: Holding costs are those associated with storing inventory that remains unsold. These costs are one component of total inventory costs, along with ordering and shortage costs.",
    ],
},
    {big:"I",long:[
        "Illiquid market：非流动市场。买卖盘记录中总成交量较小的市场。在非流动市场，少量业务通常以不成比例的金额改动价格，从而买入价和卖出价可能相距甚远。",
        "Illiquidity：流动性不足。由于要售出的资产需求不足，从而难以用现金兑换资产的情况。我们作为做市商可通过持续报出买卖价差提供流动性。亦请参阅“流动性”。",
        "Index：指数。诸如富时100或标准普尔500的指数，是对一部分股市繁荣度或价值的度量。其通常采用加权平均数从所选股票的价格进行计算。无法直接投资指数； 但投资者可以投资追踪指数走势的基金或其他产品。",
        "Industrial production：英国工业生产指数。衡量英国工业板块（包括制造业、采矿业和公共事业）产出变动的月度经济指标。",
        "Inflation：通货膨胀,一种经济状态,其中消费品物价上涨,进而导致货币购买力下降。",
        "Inflation rate：通胀率。对指定期限（比如一年或一个日历季度）所发生通胀的度量。通胀率显示商品和劳务一般价格的上升速度。",
        "Initial Margin：原始保证金,为进入头寸所需的期初抵押存款,用于担保将来业绩。",
        "Initial Public Offering (IPO)： 首次公开招股 (IPO)。一家公司首次在股市上市的过程。向投资大众发行股票是一种用于进一步扩张的集资方式。也称为“新发行”。",
        "Interbank Rates：银行同业买卖汇率,大型国际银行向其他大型国际银行报价时所按照的外汇汇率。",
        "Interest：权益。为反映拥有或收取点差交易或差价合约仓位所控制股权名义金额的经济影响而做出的现金调整。",
        "Intervention：干预,由中央银行所采取的行动,以此调整该货币的价值。",
        "Intraday trading：即日交易。同一交易日做出建仓和平仓的交易。",
        "Instant execution：即时执行。按屏幕显示价格执行的订单。若价格不可用，可重新报价作为新的双向报价，投资者可按该报价重新提交订单或取消订单。",
    ],
    enlong:[
        "liquid market: A market in which that is difficult to sell assets because of their expense, lack of interested buyers, or some other reason. Examples of illiquid markets include real estate, some stocks with low trading volume, or collectibles.",
        "Illiquidity: The lack of demand for assets to be sold makes it difficult to exchange assets with cash. As a market maker, we can provide liquidity by continuously reporting the bid-ask spread.",
        "Index: An index such as the FTSE 100 or Standard & Poor 	&#39;s 500 is a measure of the prosperity or value of a portion of the stock market. It is usually calculated from the price of the selected stock using a weighted average. It is not possible to invest directly in the index; but investors can invest in funds or other products by tracking the movement of the index.",
        "Industrial production: Monthly economic indicator that measures changes in output in the UK&#39;s industrial sectors, including manufacturing, mining and utilities.",
        "Inflation: Inflation is a quantitative measure of the rate at which the average price level of a basket of selected goods and services in an economy increases over a period of time. It is the constant rise in the general level of prices where a unit of currency buys less than it did in prior periods.",
        "Inflation rate: The measure of inflation is the inflation rate, the annualized percentage change in a general price index, usually the consumer price index, over time. The opposite of inflation is deflation.",
        "Initial Margin: Initial margin denotes the percentage of the purchase price of a security or basket of securities (purchased on margin) that an account holder must pay for with available cash in the margin account, additions to cash in the margin account or other marginable securities.",
        "Initial Public Offering (IPO): Initial public offering (IPO) or stock market launch is a type of public offering in which shares of a company are sold to institutional investors[1] and usually also retail (individual) investors.",
        "Interbank Rates: The interbank rate, also known as the federal fundsrate, is the interest charged on short-term loans made between financial institutions. The terminterbank rate may also refer to the foreign exchange rates paid by banks when they trade currencies with other banks.",
        "Interest: A currencys interest rate is probably the biggest factor in determining the perceived value of a currency. So knowing how a country\'s central bank sets its monetary policy, such as interest rate decisions, is a crucial thing to wrap your head around.",
        "Intervention: A central bank&#39;s attempt to influence exchange rates by refusing to buy or sell assets or currencies. This allows the money supply to change without interference of the central bank.",
        "Intraday trading: Intraday is shorthand for securities that trade on the markets during regular business hours and their price movements.",
        "Instant execution: Instant execution is a type of execution when a client is placing an order and specifies both volume and price; the order should be processed instantly.",

    ],
},
    {big:"J",long:[
        "Japanese candlestick charts：日本蜡烛图。日本蜡烛图类似于条形图，每根“蜡烛”显示该时期的开盘价、收盘价、高价和低价。蜡烛为绿色或红色，收盘价高于开盘价时为绿色，收盘价低于开盘价时为红色。主体“蜡烛”表示开盘价和收盘价之间的范围，“烛芯”显示价格的高低点。",
        "JPY- Japanese Yen：日元。",
    ],
    enlong:[
        "Japanese candlestick charts: A candlestick chart (also called Japanese candlestick chart) is a style of financial chart used to describe price movements of a security, derivative, or currency. Each \"candlestick\" typically shows one day, thus a one-month chart may show the 20 trading days as 20 \"candlesticks\".[1] Shorter intervals than one day are common on computer charts, longer are possible.",
        "JPY: Japanese Yen.",
    ],
},
    {big:"K",long:[
        "Kiwi：新西兰货币的另一名称。",
    ],
    enlong:[
        "Kiwi: Another name for the New Zealand currency.",
    ],
},
    {big:"L",long:[
        "Last dealing day：最后交易日。可在特定市场交易的最后一天。其不可与该市场的交收日为同一天。",
        "Last roll-over date：最后展期日期。特定远期交易或订单可人工展现、取消或重新选择自动展期（详见产品库）的最后可行日期和时间。",
        "Last trade opening date：最后交易开放日。可在特定远期市场进入或延续交易或修改现有订单（包括待执行订单）的最后可行日期和时间。",
        "Leading Indicators：领先指标,被认为可预测未来经济活动的经济变量。",
        "Leverage：杠杆,也称为保证金,为实际交易的金额与要求保证金的比例。",
        "LBOR：伦敦银行间拆放款利率。最大型国际银行间互相借贷的利率。",
        "Libor：（伦敦银行同业拆放利率）。伦敦银行同业之间就短期贷款的利率，其为许多其他利率收费/产品的重要影响基准。单一货币计价有相应的伦敦银行同业拆放利率。其为十种货币而设，每种货币有15种报价期（包括隔夜和12个月），每个工作日做出150个利率。",
        "Limit Order：限价订单,以指定价格或低于指定价格买入,或者以指定价格或高于指定价格卖出的订单。",
        "Limited risk：有限风险。严格限制最大亏损的交易。亦请参阅“受控风险”。",
        "Line charts：折线图。用线连接一系列数据点的折线图，通常为以往的收盘价。它是金融市场中最常使用的基本图表类型。",
        "Liquidation：清算,通过执行一笔抵销交易,以结清一份未结头寸。",
        "Liquidity：流动性与非流动性市场,市场能够轻松买人或卖出而不会影响价格稳定的能力。",
        "Log file：日志文件。交易活动的持续记录日志。",
        "Long Position：多头,购人的工具数量多于卖出数量的头寸。",
        "Long-term trading：长期交易。就差价合约产品或价差赌注而言，长期交易指未平仓头寸平均期限在一周至几个月之内的策略。",
        "Loonie：加拿大元的俚语。",
        "Lot：单,一用来衡量外汇交易数量的单位。交易的价值总是相对于一整数“单”而言。",
        "Lot size：每手数量。金融产品的标准数量，比如每份合约的基本货币及标的资产或股份。",
        "Liquid market：流动市场流动市场的大型交易双向业务的成交量充足，不会对价格产生重大影响或根本不会产生影响。该市场通常表现出收紧的买卖价差。",
        "Liquidity providers：流动性提供者流动性提供者为在指定资产类别充当做市商的个人或机构。在全球外汇中，大部分全球流动性由众多大牌投资银行（称为一级流动性提供者）提供。",

    ],
    enlong:[
        "Last dealing day: The last trading day is the final day that a futures contract may trade or be closed out before the delivery of the underlying asset or cash settlement must occur. By the end of the last trading day, the contract holder must be prepared to accept delivery of the commodity or settle in cash if the position is not closed.",
        "Last roll-over date: The last available date and time for a specific forward transaction or order to be manually displayed, cancelled, or automatically renewed (see product library for details).",
        "Last trade opening date: The last available date and time on which an existing order, including an order to be executed, can be entered or extended in a particular forward market or modified.",
        "Leading Indicators: A leading indicator is any economic factor that changes before the rest of the economy begins to go in a particular direction. Leading indicators help market observers and policymakers predict significant changes in the economy.",
        "Leverage: Also called margin, it is the ratio of the amount of actual transaction to the required margin.",
        "LBOR: The \"London Interbank Offered Rate\" is a reference rate based on rate London banks lend unsecured funds to each other.",
        "LBOR: The\"London Interbank Offered Rate\" is a reference rate based on rate London banks lend unsecured funds to each other.",
        "Limit Order: A limit order allows an investor to set the minimum or maximum price at which they would like to buy or sell, while a stop order allows an investor to specify the particular price at which they would like to buy or sell.",
        "Limited risk: Limited risk is an investment strategy where the amount an investor could lose is capped. The limit is usually the amount invested initially.",
        "Line charts: Line chart is the easiest chart at Forex. It represents a curve, which shows closing price for a certain period of time. Line charts can be also based on the median price, opening price, lows or highs.",
        "Liquidation: Closing one position by opening a new transaction to offset it.",
        "Liquidity: In the Forex market, liquidity pertains to a currency pair &#39; s ability to be bought and sold without causing significant change in its exchange rate. A currency pair is said to have high level of liquidity when it is easily bought or sold and there is a significant amount of trading activity for that pair.",
        "Log file: A continuous log of trading activity.",
        "Long Position: A long (or long position) is the buying of a security such as a stock, commodity or currency with the expectation the asset will rise in value. In the context of options, it is the buying of an options contract.",
        "Long-term trading: Long term trading, otherwise known as position trading, refers to a trading style in which the trader will hold on to a position for an extended period of time. A position trade can last anywhere from a few weeks to a couple of years.",
        "Loonie: Canadian currency.",
        "Lot: A lot is a number of currency units. A standard lot equal to 100,000 units of a base currency/your account currency.",
        "Lot size: A standard lot is the equivalent of 100,000 units of the base currency in a forex trade. A standard lot is similar to trade size. It is one of the three commonly known lot sizes.",
        "Liquid market: A liquid market a market with many available buyers and sellers and comparatively low transaction costs. The details of what makes a market liquid may vary depending on the asset being exchLiquidity providers: A liquidity provider is an individual or institution which acts as a market maker in a given asset class. This means that the liquidity provider will act as the both the buyer and seller of a particular asset, thus making a market.",

    ],
},
    {big:"M",long:[
       "Major currency pairs：主要货币对。外汇市场最活跃的交易货币对，包括欧元/美元、美元/日元、英镑/美元和美元/瑞郎。",
        "Margin：保证金，客户必须存入的抵押金，以便承担由反向价格运动引起的任何可能损失。",
        "Margin call：追加保证，经纪人或者交易员发出的，对额外资金或者其他抵押的要求，使保证金额到达必要数量，以便能保证向不利于客户方向移动的头寸的业绩。",
        "Market capitalisation (MCAP)： 市价总值 (MCAP)。市价总值指公司股票价值。该数值由已发行股份数目乘以当前股份价格得出。投资者会发现在确定公司规模时市价总值很有用处。",
        "Market execution：市价执行。不经重新报价按市场上的最优价格执行的订单。",
        "Market Make：运营者，提供价格，并准备以这些所述的买卖价格买入或者卖出的交易员。",
        "Market Risk：市场风险，与整体市场相关的风险，并且不能以对冲或者持有多种证券等方式加以分散。",
        "Market order：市价订单。",
        "Market-making：做市。根据投机、期望和供需报出买入价和卖出价的过程。",
        "Mark-to- Market：至市价，交易商以下列两种方式计算各自持有头寸：自然增长或者调至市价。",
        "Maturity：到期日，一金融工具的交易日或到期日。用来指明交易方向和规模而非价格的订单。这可以保证订单尽快完成。",
        "Medium-term trading：中期交易就差价合约产品和价差赌注而言，指交易员准备持仓超过一天但未平仓头寸平均期限不超过几周的策略。",
        "Mid-price：中间价。按买入价加卖出价除以二计算。",
        "Monetary policy：货币政策。中央银行在经济中设定利率和控制资金量的行为，旨在将通胀和失业率控制在可接受的水平。",
        "Moving Average Convergence Divergence (MACD)：平滑异同移动平均线 (MACD)。技术分析中用来表示可能出现看涨或看跌走势逆转的图表指示。",
        "Moving average：移动平均线。以图形的方式表示特定时间段的价格加以平均。移动平均线可以帮助识别走势、进入点和潜在的目标停止水平。",

    ],
    enlong:[
        "Major currency pairs: the most active currency pair in the market, including euro/dollar, dollar/Japanese yen, pound sterling/dollar, dollar/Swiss franc.",
        "Margin: A deposit that the customer must deposit in order to absorb any possible losses arising from a contrarian price movement.",
        "Margin call: A margin call happens when a broker demands that an investor deposits additional money or securities so that the margin account is brought up to the minimum maintenance margin.",
        "Market capitalization (MCAP): MCAP is the market value of a company, market or sector at a point in time commonly used to rank relative size. In equities, it refers to the total market value of a company\'s outstanding shares.",
        "Market execution: The order will be filled at the next available price.",
        "Market Maker: Market makers \"make\" or set both the bid and the ask prices on their systems and display them publicly on their quote screens. They stand prepared to make transactions at these prices with their customers, who range from banks to retail forex traders. In doing this, market makers provide some liquidity to the market.",
        "Market Risk: Foreign exchange risk refers to the losses that an international financial transaction may incur due to currency fluctuations.",
        "Market order: An order to a broker to sell or buy stocks or commodities at the prevailing market price.",
        "Market-making: The process of making a bid and offer based on speculation, expectations and supply and demand.",
        "Mark-to- Market: Adjusting an account to reflect it\'s current market value.",
        "Maturity: The expiration or settlement date of a financial instrument.",
        "Medium-term trading: A strategy whereby a trader is prepared to hold a position for more than one day but the average duration of an open position is not more than a few weeks.",
        "Mid-price: It is calculated by buying price plus selling price divided by two.",
        "Monetary policy: Monetary policy is one of the ways in which the Government can influence the economy.",
        "Moving Average Convergence Divergence (MACD): Moving Average Convergence Divergence(MACD) is a trend-following momentum indicator that shows the relationship between two moving averages of a security\'s price.",
        "Moving average: A simple moving average (SMA) is the simplest type of moving average in forex analysis. Basically, a simple moving average is calculated by adding up the last “X” period 	&#39; s closing prices and then dividing that number by X.",

    ]
},
    {big:"N",long:[
        "NASDAQ： 纳斯达克。纳斯达克是美国第二大的股票交易所，有许多科技公司在纳斯达克上市已久，比如微软。纳斯达克的走势对英国市场（特别是科技、传媒和电话通讯公司的techMARK指数）影响重大。",
        "Net Position：价位，还未由相反交易抵消的买/卖的货币数量。",
        "New issue：新发行。一家公司首次在股市上市。向投资大众发行股票是一种用于进一步扩张的集资方式。也称为“首次公开招股 (IPO)”。",
        "New York Stock Exchange (NYSE)：纽约证券交易所 (NYSE)。美国最大和最悠久的股票交易所。",
        "Nikkei 225：日经225。在东京股票交易所上市的前225大股票的价格加权指数。",
        "Non-dealing desk (NDD)：无交易员模式 (NDD)，该执行模式可直接与众多市场流动性提供者直接交易，以获得最有竞争力的买入价和卖出价。",
        "Non-farm payrolls： 非农就业数据。美国劳工部通常在每月第一个星期五发布的重要经济指标。其表示所有行业就业人口数量，但不包括农业、当地政府、私人及非盈利经济机构。每月数据可发生重大变动，通常约在发布时会导致外汇货币对（比如欧元/美元）的大幅波动。一般来说，数值高被认为是有利（或看涨）美元，而数值低被认为是不利（或看跌）美元。",

    ],
    enlong:[
        "NASDAQ: The Nasdaq Stock Market is an American stock exchange. It is the second-largest stock exchange in the world by market capitalization.",
        "Net Position: The value of the position subtracting the initial cost of setting up the position. For example, if 100 options where purchased for $1 each and the option is currently trading for $9, the value of the net position is $900 - $100 = $800.",
        "New issue: A company 	&#39; s initial public offering of stock to the investing public is a way to raise money for further expansion.",
        "New York Stock Exchange (NYSE): The New York Stock Exchange (NYSE, nicknamed \"The Big Board\") is the world'\'s largest stock exchange.",
        "Nikkei 225: The Nikkei 225, more commonly called the Nikkei, the Nikkei index, or the Nikkei Stock Average, is a stock market index for the Tokyo Stock Exchange.",
        "Non-dealing desk (NDD): No dealing desk is a way of forex trading that provides immediate access to the interbank market.",
        "Non-farm payrolls: Nonfarm payroll employment is a compiled name for goods, construction and manufacturing companies in the US. It does not include farm workers, private household employees, or non-profit organization employees. The financial assets most affected by the non-farm payroll (NFP) data include the US dollar, equities and gold.",

    ],
},
    {big:"O",long:[
        "OCO (one cancels the other)：OCO（二选一订单）。同一时间对同一股票下达限价卖出订单和卖出止损订单。当执行其中一个订单时，另一个订单将自动取消。也适用于限价买入和买入止损订单。",
        "Offer：发盘价。由发盘或递盘组成的当前市价。在两种价格中，递盘价总是高于发盘价。",
        "Offer(ask) price：卖出价，在卖出时，卖方愿意依照的价格或汇率。参看买入价。",
        "Offsetting Transaction：抵消交易，用于撤销或者抵消未结头寸的部分或全部市场风险的交易。",
        "One Cancels the Other Order(OCO)：选择性委托单，一种突发性订单，执行订单的一部分将自动撤销订单的另一部分。",
        "Online trading： 在线交易。通过经纪人（如CMC Markets的在线交易平台）经由互联网买卖金融产品的行为。",
        "Open Order：开放订单,在市场价格向指定价位移动时买入或卖出的订单。",
        "Open Position：未结头寸，尚未撤销或者清算的交易，此时投资者利益将受外汇汇率走势的影响。",
        "Option：期权。在一定期限内按指定价格（“行使价”）买入（“看涨期权”）或卖出（“看跌期权”）一定数量的指定股票、大宗商品、货币或指数的权利但非义务。对持有人而言，潜在损失仅限于获取期权支付的价格。期权若未被行使将会到期失效。",
        "Order：指令，给予交易在特定日期执行的指示。",
        "Order / order to open：订单/建仓订单。客户指示经纪人/交易员当触及指定价格时的买卖指示。订单在被客户执行或取消前一直有效。",
        "Order book：买卖盘记录。当触及指定买入价或卖出价时，新近订单会自动按订单进行记录。自1997年10月20日起英国富时100指数股票一直在电子买卖盘记录上交易。",
        "Out-of-hours： 在正式交易时间以外的交易。在主要市场（如英国100或美国30）主要开放时间以外的时间进行的交易。",
        "Over the Counter(OTC)：柜台市场，用于描述任何不在交易所进行的交易。",
        "Overnight Position：隔夜交易，直到第二个交易日仍保持开放的交易。",
        "Oscillator：摇摆指标。在图表分析中显示走势逆转发生的可能性的先行指标。",
    ],
    enlong:[
        "OCO (one cancels the other): A one-cancels-the-other order (OCO) is a pair of orders stipulating that if one order executes, then the other order is automatically canceled.",
        "Offer: The current market price consisting of an offer or a bid in which the bid price is always higher than the offer price.",
        "Offer(ask) price: when selling, the seller is willing to sell according to the price or exchange rate.",
        "Offsetting Transaction: An offsetting transaction is a transaction that cancels out the effects of another transaction.",
        "One Cancels the Other Order(OCO): A sudden order in which part of the execution order will automatically cancel another part of the order.",
        "Online trading: The act of buying and selling financial products over the Internet through brokers.",
        "Open Order: An open order is an order that is to be executed when an, as yet, unmet requirement has been met before it is canceled by the customer or expires.",
        "Open Position: An open position in investing is any established or entered trade that has yet to close with an opposing trade. An open position can exist following a buy, a long position, a sell, or a short position.",
        "Option: Options are financial instruments that are derivatives or based on underlying securities such as stocks. An options contract offers the buyer the opportunity to buy or sell—depending on the type of contract they hold—the underlying asset.",
        "Order: To give instructions for the execution of a transaction on a specified date.",
        "Order/order to open: An open order is an order that is to be executed when an unmet requirement has been met before it is canceled by the customer or expires.",
        "Order book: An order book is an electronic list of buy and sell orders for a specific security or financial instrument organized by price level.",
        "Out-of-hours: Trading outside official trading hours. Trading conducted outside the main opening hours of a major market such as the United Kingdom 100 or the United States 30.",
        "Over the Counter(OTC): Over-the-counter (OTC) or off-exchange trading is done directly between two parties, without the supervision of an exchange. It is contrasted with exchange trading, which occurs via exchanges.",
        "Overnight Position: Overnight positions are trading positions that are not closed by the end of the trading day. These trades are held overnight for trading the following day.",
        "Oscillator: An oscillator is a technical analysis indicator that varies over time within a band (above and below a center line, or between set levels). Oscillators are used to discover short-term overbought or oversold conditions. Common oscillators are MACD, ROC, RSI, CCI.",
    
    ],
},
    {big:"P",long:[
        "Pips：点，在货币市场中运用的术语，表示汇率可进行的最小增幅移动。根据市场环境，正常情况下是一个基点。",
        "Pivot points：枢轴点。枢轴点在技术分析中使用前一个时期的最高、最低和收盘计算当前期间的支撑位和阻力位。",
        "Political risk：政治风险，一国政府政策的变化，此种变化可能会对投资者的头寸产生负面效果。",
        "Portfolio：投资组合。个人或公司持有的投资组合。",
        "Position：头寸（仓位），是一种以买入或卖出表达的交易意向。",
        "Position margin：仓位保证金。价差赌注者或差价合约交易员新建仓位需要支付的保证金净值。",
        "Position sizing：仓位规模。特定投资组合的仓位规模。其与风险管理技巧有关，投资者计算每个新仓规模，以便仓位可能遭受的最大损失不会超过其资本的一定数额或比例。",
        "Premium：升水，在货币市场中，升水指为判断远期或期货价格而向即期价格中添加的点数。",
        "Price depth：价格深度。",
        "Price Transparency：价格透明度，每一位市场参与者都对报价说明有平等的访问权。",
        "Producer Price Index (PPI)：生产价格指数 (PPI)。衡量生产者售出成品和服务的价格的统计数据。",
        "Profit /Loss or\“PL\" or Gain/Loos：利润/损失，实际操作时，完结交易的兑现利润或损失，再加上被调至市价的理论“未兑现”利润或损失。",
        "Purchasing Managers Index (PMI) ：采购经理人指数(PMI)。由众多制造企业经理完成调查而创建的经济活动指标。它以图片的形式显示制造业的经济条件，常被投资者用于预测一个国家/地区经济的未来国内生产总值。",

    ],
    enlong:[
        "Pips: A pip, short for point in percentage, is a very small measure of change in a currency pair in the forex market. It can be measured in terms of the quote or in terms of the underlying currency.",
        "Pivot points: A forex pivot point is an indicator developed by floor traders in the commodities markets to determine potential turning points, also known as \"pivots\".",
        "Political risk: Political risk is the risk an investment returns could suffer as a result of political changes or instability in a country. Instability affecting investment returns could stem from a change in government, legislative bodies, other foreign policy makers or military control.",
        "Portfolio: A portfolio generally refers to a collection of assets and holdings that are managed by either an individual investor or an investment manager.",
        "Position: A position is the amount of a security, commodity or currency which is owned by an individual, dealer, institution, or other fiscal entity.",
        "Position margin: A forex margin account is very similar to an equities margin account – the investor is taking a short-term loan from the broker. The loan is equal to the amount of leverage taken on by the investor.",
        "Position sizing: Position sizing basically refers to the size of a position within a particular portfolio, or the dollar amount that an investor is going to trade.",
        "Premium: A forward premium is a situation in which the forward or expected future price for a currency is greater than the spot price.",
        "Price depth: The depth of price.",
        "Price Transparency: Price transparency is the ability to know all of the bid prices, ask prices, and trading quantities for a given stock, good, or service at any point in time.",
        "Producer Price Index (PPI): The Producer Price Index (PPI) is a weighted index of prices measured at the wholesale, or producer level. A monthly release from the Bureau of Labor Statistics (BLS), the PPI shows trends within the wholesale markets (the PPI was once called the Wholesale Price Index), manufacturing industries and commodities markets.",
        "Profit /Loss or\“PL\" or Gain/Loos: The profit or loss is realized (realized P&L) when you close out a trade position. In case of a profit, the margin balance is increased, and in case of a loss, it is decreased.",
        "Purchasing Managers Index (PMI): A measure of the prevailing direction of economic trends in manufacturing. The PMI is based on a monthly survey of supply chain managers across 19 industries, covering both upstream and downstream activity.",

    ],
},
    {big:"Q",long:[
        "Quantitative easing：量化宽松。当传统货币政策措施（如削减利率）不凑效时中央银行为刺激经济而采取的措施。中央银行以电子方式在其自己的银行账户设立资金以购买以前发行的政府债券，加上私营部门和不良的资产（这样公司能筹集资金）。这有助于创造更多的市场交易和流动性，以帮助刺激经济。",
        "Quarterly CFDs： 季度性差价合约产品。每隔三个月到期的期货类型。通常会报出未来两个或三个季度的价格。亦请参阅“展期”。",
        "Quote：报价。一种指示性市场价格,显示在任何特定时间,某一证券最高买入和或最低卖出的有效价格。",
        "Quote currency：计价货币。货币对中的第二个货币（如美元是英镑/美元的计价货币）。亦请参阅“基本货币”或“可变货币”。",
    ],
    enlong:[
        "Quantitative easing: Quantitative easing is an unconventional monetary policy in which a central bank purchases government securities or other securities from the market in order to to increase the money supply and encourage lending and investment.",
        "Quarterly CFDs: Futures that mature every three months usually which offer prices for the next two or three quarters.",
        "Quote: An indicative market price indicating the effective price at which a security is bought and sold at the highest or lowest level at any given time.",
        "Quote currency: A quote currency is the second currency quoted in a currency pair in forex. In a direct quote, the quote currency is the foreign currency.",

    ],
},
    {big:"R",long:[
        "Rally：上升幅度，从一阶段的价位下降开始回升。",
        "Range：波动范围，在将来的交易记录中，一指定阶段的最高价与最低价的差别。",
        "Rate：汇率，以别种货币计的一种货币价格。",
        "Realised profit/ loss：实现盈利/亏损。平仓时赚取或亏损的金额。实现盈利或亏损将计入账户现金余额或从中扣除。",
        "Relative strength index (RSI) ：相对强弱指标 (RSI)。技术分析使用的图表指标。其可识别走势将要达到当前方向尽头的时间以及超卖和超买市场条件。",
        "Requote： 重新报价。当执行订单所要求的价格不再有效时会进行重新报价，从而得出不同的报价。在快速流动的市场可发生重新报价。",
        "Resistance level：阻力位，技术分析术语，表示货币无力超越的某一具体价位。",
        "Retail sales： 零售销量。零售商向顾客售出耐用品和非耐用品的总数。该统计数据在很大程度上不包括服务。",
        "Revaluation：再估价汇率，是交易商在进行每日结算时，为确定当日利润和亏损而使用的市场汇率。",
        "Rights issue：股票认购权发行。公司以有利优惠的价格向现有股东额外发行股份，通常是为了筹措新的资金用于进一步发展或为新的收购融资。按145p的五得二股票认购权发行指现有股东有权按每持有五份股份可以每份收购股份145p的新成本额外增购两股。",
        "Risk：风险，风险暴露在不确定变化中，收益的多变性；更重要的是，少于预期收益的可能性。",
        "Risk Management：风险管理，利用金融分析与交易技术来减少和/或控制不同种类的风险。",
        "Rollover：展期。平掉到期的期货仓位并在下一个可交易期限重新建仓。在外汇中，该流程的价值按两种货币的利率差计量。展期通常需要支付小额费用。",
        "Round Trip：双向交易，买和卖一指定数量之货币。",
        "Running profit/loss：可得盈利/亏损，其表示未平仓头寸的表现情况：若按现行市价平仓将会得出多少未实现收益或亏损额。",
],
    enlong:[
        "Rally: A rally is a period of sustained increases in the prices of stocks, bonds or indexes.",
        "Range: A range-bound market is one in which price bounces in between a specific high price and low price.",
        "Rate: A foreign exchange rate is the price of the domestic currency stated in terms of another currency.",
        "Realized profit/ loss: The amount earned or lost when closing a position. Realization of profit or loss will be credited to or deducted from the account balance.",
        "Relative strength index (RSI): The relative strength index (RSI) is most commonly used to indicate temporary overbought or oversold conditions in a market. An intraday forex trading strategy can be devised to take advantage of indications from the RSI that a market is overextended and therefore likely to retrace.",
        "Requote: The broker you are dealing with is not able or willing to give you a trade based upon the price you entered. Generally this happens in a fast-moving market, usually around the time of a big news announcement or some kind of shock to the system.",
        "Resistance level: Resistance, or a resistance level, is the price point at which the rise in the price of an asset is halted by the emergence of a growing number of sellers who wish to sell the at that price.",
        "Retail sales: Retail sales measure the purchases of durable and non-durable goods over a certain period of time—usually once a month. This figure monitors and tracks consumer spending habits and the demand for finished goods.",
        "Revaluation: Revaluation is a treasury concept defining the method by which international businesses translate the value of all their foreign currency-denominated open accounts – i.e. payable and receivable transactions – into the company s reporting currency.",
        "Rights issue: A rights issue is the term for when a company offers more of its shares to current shareholders, usually to raise extra capital.Typically, a rights issue will offer shares at a price lower than the current market price, with a stipulation that the rights must be taken up within a time period.",
        "Risk: A financial risk that exists when a financial transaction is denominated in a currency other than that of the base currency of the company.",
        "Risk Management: Use financial analysis and trading techniques to reduce and/or control different types of risks.",
        "Rollover: The rollover rate in forex is the net interest return on a currency position held overnight by a trader. That is, when trading currencies, an investor borrows one currency to buy another.",
        "Round Trip: Round-tripping, also known as round-trip transactions or \"Lazy Susans\", is defined by The Wall Street Journal as a form of barter that involves a company selling \"an unused asset to another company, while at the same time agreeing to buy back the same or similar assets at about the same price.\"",
        "Running profit/loss: It represents the performance of the open position: if close the position according to the current market price, how much unrealized gains or losses will get.",

    ]
},
    {big:"S",long:[
        "S&P 500： 标普500。在纽约证券交易所 (NYSE) 或纳斯达克上市的前500强公司的市价总值加权指数。通常用作美国市场情绪的度量。",
        "Scalping：超短线交易法。该交易策略涉及做出短期交易（有时候低于一分钟），通常为了尝试和捕捉微小价格走势。",
        "Sector：板块。市场不同的子集，所组成的股份性质类似。股票通常根据公司的业务被分到不同的板块。比如英国富时100指数拥有银行、油气和制造板块。",
        "Sell limit / limit sell：限价卖出订单。指金融产品的条件性交易订单，仅可按指定价或更高价售出。",
        "Sell stop：卖出止损。按低于下单时的价格建空头仓位的订单。其受价格深度阶梯影响，可能会滑落至当前市价。",
        "Selling short：卖空。卖出非本身所有的股份并希望在结清合约前股价下跌的操作。若价格下跌，可按较低价格买入股份赚取差额。亦请参阅“空头交易”。",
        "Settlement：清算结算，一笔交易并进入记录的过程。",
        "Shorting：空头交易。该交易形式为首次交易（如点差交易或差价合约仓位）卖出仓位并希望市场下跌。之后通过买入交易平仓。若价格下跌则盈利，价格上涨则亏损。在交易外汇时它是指根据计价货币卖出基本货币。",
        "Short Position：空头头寸，由卖出空头而产生的投资头寸。",
        "Slippage： 滑点。订单请求水平和订单实际执行价格的差额。市价变动迅速或有缺口时，在波动变强期间会产生滑点。亦请参阅“全数执行”和“缺口”。",
        "Spot position：即期价格，当前市场价格。",
        "Spot price：即期价格。即时结算或交付货币、指数、大宗商品或股份的报价（支付和交付产品的款项）。其为特定时间可买卖大宗商品或货币的当前价格。",
        "Spot rate：即期汇率。即时结算的汇率。",
        "Spread：价差，买卖价格之间的差价。",
        "Spread charts：点差表。点差表以双线图表格式绘制买卖价格。蓝色线表示买入价，橙色线表示卖出价； 阴影区域为两个价格的差别或称为“点差”。",
        "Square：轧平，没有多头也没有空头，即相当于持平或者轧平。",
        "Sterling：英国英镑的另一名称。",
        "Stochastic：随机指标。在技术分析中用于确定可能的走势逆转的图表指标，以表现出超买或超卖市场状况。",
        "Stock exchange：股票交易所。证券交易市场。",
        "Stock index：股票指数。股票指数为编入一个由许多股票组合的总价格，以使投资者容易跟进特定组别股票的表现。",
        "Stockbroker：股票经纪人。交易所成员公司，向公众提供建议和交易服务，同时也使用自己的账户进行交易。",
        "Stop entry order：止损挂单。止损挂单可在设定期限内按选定的目标价格进场交易。买入止损挂单是指以高于当前市价的价格交易的订单。卖出止损挂单是指以低于当前市价的价格交易的订单。止损挂单通常受滑点影响。",
        "Stop loss: 止损。下达订单在价格触及指定止损价格时自动平仓。止损订单旨在限制仓位亏损。但是由于市场缺口或滑点的原因，根据市场状况交易可能会按稍微偏离的价格退场，不能完全保证止损。也称为止损订单。",
        "Stop Loss Order：停止损失订单，以协议价格买入/卖出的订单。",
        "Stop order：止损订单。价格触及特定点位时平仓的订单。",
        "Strike price：行使价。数位 100结清须遵循的目标价格；期权交易中可行使或结清合约的价格。",
        "Support Levels：支撑位，一技术性分析中的术语，表示一货率在指定最高与最低价位间能自动调整自身走势。",
        "Swap：掉期，一货币掉期为同时以远期货币汇率卖/买一相同数量货币。",
        "Swissy：瑞郎，瑞士法郎的俚语。",
    ],
    enlong:[
        "S&P 500: The S&P 500 uses a market capitalization weighting method, giving a higher percentage allocation to companies with the largest market capitalization. The market capitalization of a company is calculated by taking the current stock price and multiplying it by the outstanding shares.",
        "Scalping: Forex scalping is a trading strategy used by forex traders to buy or sell a currency pair and then hold it for a short period of time in an attempt to make a profit.",
        "Sector: Different subsets of the market, consisting of shares of similar nature, are usually divided into different sectors according to the company &#39;s business. For example, the FTSE 100 in the UK owns the oil and gas sector and the manufacturing sector.",
        "Sell limit/limit sell: A conditional order for a financial product that can only be sold at or above the specified price.",
        "Sell stop: SELL STOP AND STOP-LIMIT FOREX ORDER. In forex trading, a sell stop is a trade order from a trader to a broker asking that a trade be executed in the best possible price once the price gets to a stated price or below.",
        "Short Selling: Short selling occurs when an investor borrows a security and sells it on the open market, planning to buy it back later for less money. Short sellers bet on, and profit from, a drop in a security &#39;s price.",
        "Settlement: A transaction is entered into the recording process.",
        "Shorting: This is the first time a trade (such as a spread trade or a CFD position) has been made in which a position is sold for hoping that the market will fall and then the position will be closed by a buying trade.",
        "Short Position: An investment position created by selling a short position.",
        "Slippage: Slippage occurs when there is a change in the bid/ask spread. A market order may get executed at a less or more favorable price than originally intended when this happens.",
        "Spot position: The present markets price.",
        "Spot price: A foreign exchange spot transaction, also known as FX spot, is an agreement between two parties to buy one currency against selling another currency at an agreed price for settlement on the spot date.",
        "Spot rate: Instant settlement rate.",
        "Spread: The difference between the selling price and buying price.",
        "Spread charts: The point difference table plots the buying and selling prices in a two-line chart format. The blue line represents the buying price and the orange line represents the selling price. The shaded area is the difference or point difference between two prices.",
        "Square: Square position can take on a different nuance depending on the speaker. For an individual forex trader, a square position can refer to offsetting long and short positions in the same currency pair or a situation where a currency trader holds no positions in the market.",
        "Sterling: The name of UK currency.",
        "Stochastic: Stochastic compares closing prices in a market to the high and low prices for that market over a certain period of time. Stochastic is calculated by taking the lowest low price and the highest high price for a number of previous trading periods, usually fourteen.",
        "Stock exchange: Stock exchange market.",
        "Stock index: A stock index is a group of shares that are used to give an indication of a sector, exchange or economy. Usually, a stock index is made up of a set number of the top shares from a given exchange.",
        "Stockbroker: A stockbroker (or a Registered Representative) is an individual or firm who buys and sells stocks and other securities for clients.",
        "Stop entry order: A stop order is an order to buy or sell a security when its price moves past a particular point, ensuring a higher probability of achieving a predetermined entry or exit price, limiting the investors loss or locking in a profit.",
        "Stop Loss: Orders will be automatically close the position when the price hits the specified stop-loss price. Stop-loss orders are designed to limit the loss of a position. However, due to market gaps or slippages, the trade may exit at slightly deviated prices according to market conditions.",
        "Stop Loss Order: A trade order to sell a currency when the price reaches or falls below the specified price.",
        "Stop order: Order to close when prices hit a specific point.",
        "Strike price: The strike price (or exercise price) of an option is the fixed price at which the owner of the option can buy (in the case of a call), or sell (in the case of a put), the underlying security or commodity.",
        "Support Levels: Support, or support level, refers to the price level that an asset does not fall below for period of time.",
        "Swap: a simultaneous purchase and sale of identical amounts of one currency for another with two different value dates (normally spot to forward)[1] and may use foreign exchange derivatives.",
        "Swissy：Swiss franc.",
    ],
},
    {big:"T",long:[
        "Take profit： 获利。以相比下单价格更可盈利的价格平掉未平仓头寸的订单。",
        "TechMARK：集结市场上全部科技公司的市场。techMARK有其专门的指数：FTSE techMARK 100和FTSE techMARK All-share。",
        "Technical Analysis：技术分析，通过分析诸如图表、价格趋势、交易量等市场数据，试图预报未来市场活动的做法。",
        "Tick：替克，货币价格的最小单位变化。",
        "Tomorrow Next(Tom/Next)：明日次日，为下一日交割同时买入和卖出一种货币。",
        "Trade balance：贸易差额。一个国家/地区商品和劳务（如汽车、电子产品、纺织品、银行业和保险业）进出口的差额。",
        "Trade size：交易规模。正在交易的相关仓位的规模。其支配市场价格每次走动交易的盈利或亏损量。",
        "Trailing stop：移动止损订单。移动止损订单是特殊类型的止损订单，当市场走势有利时止损点也随着市价移动。",
        "Transaction Cost：交易成本，与买入或卖出一款金融工具相关的成本。",
        "Transaction Date：交易日，交易发生的日期。",
        "Treasury： 国债。政府发行的债券。由英国政府发行的债券被称为金边债券，通常所说的“英国国债”。",
        "Trend lines：趋势线。图表中绘制显示大体趋势的直线。在呈上升的趋势中，下面画的线充当支撑位； 在呈下降的趋势中，上面画的线充当阻力位。一旦资产突破趋势线，趋势被认为无效。",
        "Trend：走势。价格走向的大体趋势。",
        "Turnover：交易额，指定时期内的交易量或交易规模。",
        "Two- Way Price：双向报价，同时提供一项外汇交易的买入和卖出报价。",
    ],
    enlong:[
        "Take profit: Take profit(TP) or target price is an order that you tell or send to your broker informing them to close your position or trade when price reaches a specified price level in profit.",
        "TechMARK: The market of all technology companies in the market. techMARK has its own special index: FTSE techMARK 100 and FTSE techMARK All-share.",
        "Technical Analysis: Also techmark uk STOCK MARKET. On the London Stock Exchange, the market for shares in technology companies, The company was one of the first arrivals on the Stock Exchange &#39;s techmark index.",
        "Tick: The smallest currency unit change.",
        "Tomorrow Next(Tom/Next): To buy and sell a currency for the next delivery day.",
        "Trade balance: Regional balance of imports and exports of goods and services (e.g. automotive electronics, textiles, banking and insurance).",
        "Trade size: The size of the relevant position being traded. It governs the profit or loss of the market price per move.",
        "Trailing stop: A trailing stop is a stop order that can be set at a defined percentage or dollar amount away from a securitys current market price.",
        "Transaction Cost: transaction cost is any expenses incurred when buying or selling securities.",
        "Transaction Date: The date when transaction occurs.",
        "Treasury: Government stocks. Stocks issued by the British government are called gilts and are commonly referred to as gilts.",
        "Trend lines: Trend lines are a staple for technical Forex traders that can be used on any currency pair and on any time frame.",
        "Trend: The trend of price.",
        "Turnover: The trading amount of a specific period.",
        "Two-Way Price: Offer a selling and buying price of a forex transaction at the same time.",
    ],
},
    {big:"U",long:[
        "Underlying：标的物。在衍生品交易中（如差价合约产品）使用的术语。衍生品这一金融产品的价格来自于（衍生于）各类资产。标的物为金融产品（如股票、期货、大宗商品、货币、指数），衍生物的价格以标的物为基础。",
        "Unemployment claims： 失业救济金认领人数。这一统计数字表示在过去的一周内首次申请失业保险的人数。这是美国最早的就业相关经济数据发布。",
        "Unrealized Gain//Loss，未兑现盈利/损失，现价的为开市价位的理论上的盈利/损失，由经纪人单独对其做决定。",
        "Uptick：证券提价交易，高于同种货币较前报价的最新报价。",
        "Uptick Rule：证券提价交易规则，美国法律规定证券不能被卖空，除非在卖空交易前的交易价格低于卖空交易被执行的价格。",
        "US Prime Rate：美国基本利率，美国银行向其主要企业客户贷款所依照的利率。",
    ],
enlong:[
        "Underlying: Underlying, in equities, is the common stock that must be delivered when a warrant is exercised, or when a convertible bond or convertible preferred share is converted to common stock. The price of the underlying is the main factor that determines prices of derivative securities, warrants and convertibles.",
        "Unemployment claims: This statistic represents the number of people filing for unemployment insurance in the past week, the earliest release of U.S. employment-related economic data.",
        "Unrealized Gain//Loss: An Unrealized Gain/Loss is the hypothetical gain or loss on a single Open Position, or on all Open Positions, valued at current market rates, as determined by the forex trader or by his broker to assess his outstanding risk.",
        "Uptick: An uptick is a transaction for a financial instrument that occurs at a higher price than the previous transaction. An uptick has occurred if a stock'+\"\'\"+\'s price has increased in relation to the last “tick” or trade.",
        "Uptick Rule: Regulation in which a security is not allowed to be sold short unless the previous trade to the short sale was at a price lower than the price at which the short sale was executed.",
        "US Prime Rate: The interest rate at which America bank lends to its main corporate customers.",
],
},
    {big:"V",long:[
        "Value date：交割日，交易双方同意交换款项的日期。",
        "Variation Margin：变动保证金，由于市场波动，经纪人向客户提出的附加保金要求。",
        "Volatility(vol)：易变性，在特定时期内市场价格变动的统计计量。",
        "VWAP：成交量加权平均价格 (VWAP) - 按特定价格对交易成交量下的金融产品进行定价的方法。",
    ],
    enlong:[
        "Value date: The date when the entry to an account is considered effective in accounting.",
        "Variation Margin: Variation margin (VM) In derivatives markets, variation margin is one of two types of collateral required to protect parties to a contract in the event of default by the other counter party.",
        "Volatility: Volatility (in Forex trading) refers to the amount of uncertainty or risk involved with the size of changes in a currency exchange rate.",
        "VWAP: Volume Weighted Average Price (VWAP) is calculated by adding up the dollars traded for every transaction (price multiplied by the number of shares traded) and then dividing by the total shares traded.",
    ],
},
    {big:"W",long:[
        "Wall Street：华尔街，对美国最大的股票交易所纽约证券交易所 (NYSE) 的叫法，这一叫法广为人知。",
        "Whipsaw：锯齿，此词条用于说明一种高速变动的市场状态，即在剧烈价格周期之后又紧接着出现一个反向的剧烈价格变动周期。",
        "Working an order：处理订单，对仍未执行的订单进行处理的过程，亦称为待执行订单。",
    ],
    enlong:[
        "Wall Street: The name for the largest stock exchange in the United States, the New York stock exchange (NYSE).",
        "Whipsaw: Whipsaw refers to a loss that a trader incurs when a security suddenly and unexpectedly drops soon after it is purchased.",
        "Working an order: The process of processing unexecuted orders.",
    ],
},
    {big:"X",long:[
        "XD：这一符号用来表示证券或股票已除息。",
    ],
    enlong:[
        "XD: used to indicate that a security or stock has ex-dividend.",
    ],
},
    {big:"Y",long:[
        "Yard：十亿的另一种说法。",
        "Yield：收益，投资所得收入回报。收益的类型很多，并在某些情况下各类型收益计算方法不尽相同。收益指证券所得股息或利息，通常为年度数据。",
        "Yuan：元，中国货币的基本单位。",
    ],
    enlong:[
        "Yard: Billion.",
        "Yield: Mainly the yield is an indicator of profitability and viability of your investment.",
        "Yuan: Chinese currency unit.",
    ],
},
    {big:"Z",long:[
        "Zloty： 兹罗提。波兰的货币单位。",
    ],
    enlong:[
        "Zloty: Poland currency unit.",
    ],
},
]

export {
    contents,
}
