module.exports = [
    {
        en:{
            team:'Forex Markets Pros Team',
            help:'Help You to Profit',
            know:'Know Better, Earn More',
            daily:'Daily Forex Analysis Article',
            regular:'Regular Education Videos',
            online:'Online and Offline Lectures',
            apply:'Apply Now',
            FirstName:'First Name',
            LastName:'Last Name',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Phone Number',
            Email:'Email',
            register:'Register Now',
            ten:'10 years of experience',
            twenty:'20 years of experience',
            thirty:'30 years of experience',
            forex:'FOREX FOUR',
            most:'The Most Experienced Forex Market',
            analysts:'Analysts Team',
            malong:'-Malong: Forex Education Expert',
            ray:'-Ray Shen: Forex Chief Analyst',
            daker:'-Derek Baker: CF30 in FCA and ACSI qualified Trader',
            marius:'-Marius Paun: CF30 in FCA Senior Dealer',
            learn:'Register Now',
            any:'Daily Analysis',
            all:'All fundamental and technical analyses are only for your profitable trades.',
            webinar:'Webinars',
            hot:'Regular hot topic discussion in video forms when you can find the spark of Wisdom.',
            offline:'Offline Seminar',
            support:'Seminars support clients with a real-time and face-to-face communication.',
            viet:'Vietnam',
            yield:'The yield',
            more:'Learn more',
            maly:'Malaysia',
            indo:'Indonesia',
            profit:'Profit Now!',
            professional:'CPT Markets professional analyst team, only for you and your better future!',
            create:'CPT Markets Pro Team create a range of Free Forex learning tools including Video Center, Knowledge Base and Webinars, etc. Enhancing your trading skills with these free educational tools and resources.',
            
        },
        cn:{
            team:'外汇专业分析师团队',
            help:'助力交易盈利',
            know:'学得多，赚得多',
            daily:'每日外汇分析文章',
            regular:'专业外汇教学视频',
            online:'线上线下研讨会',
            apply:'个人信息',
            FirstName:'姓',
            LastName:'名',
            Indonesia:'印度尼西亚',
            Vietnam:'越南',
            Thailand:'泰国',
            Singapore:'新加坡',
            Malaysia:'马来西亚',
            Philippines:'菲律宾',
            Cambodia:'柬埔寨',
            Burma:'缅甸',
            Laos:'老挝',
            Brunei:'文莱',
            Timor:'东帝汶',
            phone:'手机号码',
            Email:'电子邮箱',
            register:'立即注册',
            ten:'10年行业经验',
            twenty:'20年行业经验',
            thirty:'30年行业经验',
            most:'最具行业经验的外汇分析师团队',
            analysts:'',
            malong:'-Malong: 外汇教育专家',
            ray:'-Ray Shen: 资深外汇专业分析师',
            daker:'-Derek Baker: FCA 和 ACSI 认证交易员',
            marius:'-Marius Paun: FCA认证高级分析师',
            learn:'马上学习',
            any:'每日汇评',
            all:'适用于交易员的基本面以及技术面分析',
            webinar:'网络研讨会',
            hot:'时事热点、实时汇市分析，行业领先专家引导您发掘交易的潜能',
            offline:'线下交流会',
            support:'与客户面对面的线下交流，专业的行情分析和操作见解',
            viet:'越南',
            yield:'收益率',
            more:'了解更多',
            maly:'马来西亚',
            indo:'印度尼西亚',
            profit:'马上盈利！',
            professional:'CPT Markets 资深专业外汇分析师团队竭尽所能为我们所有的客户提供丰富的外汇教育资源。CPT Markets金融学院，专为您的未来而生！',
            create:'从外汇基础知识到到专业外汇分析，丰富多元的教育资源，提升您的交易技能。',
      
        },
        vn:{
            team:'Đội ngũ chuyên gia phân tích Forex chuyên nghiệp',
            help:'Giúp giao dịch tăng thêm lợi nhuận',
            know:'Học càng nhiều, thu nhập càng cao',
            daily:'Cập nhật bài viết phân tích forex mỗi ngày',
            regular:'Video giảng dạy forex chuyên nghiệp',
            online:'Hội thảo online và offline',
            apply:'Thông tin cá nhân',
            FirstName:'Tên',
            LastName:'Họ',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Số điện thoại',
            Email:'Email',
            register:'Đăng ký ngay',
            ten:'10 năm kinh nghiệm trong ngành',
            twenty:'20 năm kinh nghiệm trong ngành',
            thirty:'30 năm kinh nghiệm trong ngành',
            most:'Đội ngũ chuyên gia phân tích Forex chuyên',
            analysts:'nghiệp giàu kinh nghiệm',
            malong:'-Malong: Chuyên gia giáo dục Forex',
            ray:'-Ray Shen: Chuyên gia phân tích Forex',
            daker:'-Derek Baker: Nhà giao dịch CF30 của FCA và ACSI',
            marius:'-Marius Paun: Đại lý cấp cao CF30 của FCA',
            learn:'Học ngay',
            any:'Đánh giá mỗi ngày',
            all:'Phù hợp với trader trên phương diện phân tích cơ bản và kỹ thuật.',
            webinar:'Hội thảo online',
            hot:'Điểm nóng thời sự, phân tích thị trường forex kịp thời, được các chuyên gia đầu ngành trong lĩnh vực forex hướng dẫn khám phá tiềm năng của giao dịch.',
            offline:'Giao lưu offline',
            support:'Đối thoại trực tiếp với khách hàng, phân tích và đánh giá thị trường chuyên nghiệp.',
            viet:'Vietnam',
            yield:'Lợi nhuận',
            more:'Tìm hiểu thêm',
            maly:'Malaysia',
            indo:'Indonesia',
            profit:'Lợi nhuận tức thì!',
            professional:'Đội ngũ chuyên gia phân tích forex của CPT Markets đã và đang nỗ lực hết mình để mang đến cho khách hàng những tài liệu, thông tin phong phú và vô cùng giá trị. Học viện tài chính CPT Markets, tất cả vì tương lai của bạn!',
            create:'Từ kiến thức forex cơ bản đến chuyên sâu, tài liệu giáo dục thiết thực phong phú, nâng cao kỹ năng giao dịch của bạn!',
      
        },
        in:{
            team:'Tim pro pasar Forex',
            help:'Membantu anda Profit',
            know:'Ketahuilah lebih baik, dapatkan lebih banyak',
            daily:'Artikel analisis Forex harian',
            regular:'Video pendidikan reguler',
            online:'Pendidikan online dan offline',
            apply:'Daftar Sekarang',
            FirstName:'Nama depan',
            LastName:'Nama belakang',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Nomor telepon',
            Email:'Email',
            register:'Daftar sekarang',
            ten:'10 years of experience',
            twenty:'20 years of experience',
            thirty:'30 years of experience',
            most:'Tim analis Forex yang paling',
            analysts:'berpengalaman',
            malong:'-Malong: Ahli Pendidikan Forex',
            ray:'-Ray Shen: Kepala Analis Forex',
            daker:'-Derek Baker: CF30 dalam Trader yang memenuhi syarat FCA dan ACSI',
            marius:'-Marius Paun: CF30 dalam Dealer Senior FCA',
            learn:'Daftar Sekarang',
            any:'Analisis harian',
            all:'Semua analisis fundamental dan teknis supaya menguntungkan perdagangan anda',
            webinar:'Webinar',
            hot:'Diskusi hot topik reguler dalam bentuk video supaya anda dapat menemukan percikan kebijaksanaan dalam trading',
            offline:'Seminar Offline',
            support:'Seminar yang mendukung klien dengan komunikasi real-time dan face-to-face',
            viet:'Vietnam',
            yield:'Hasil',
            more:'Learn more',
            maly:'Malaysia',
            indo:'Indonesia',
            profit:'Profit-lah sekarang juga!',
            professional:'Tim analis profesional CPT Markets, untuk masa depan anda yang lebih baik!',
            create:'Tim pro CPT Markets membuat berbagai alat belajar Forex gratis termasuk pusat video kami, basis pengetahuan, webinar, dll. Tingkatkan keterampilan perdagangan anda dengan alat dan sumber daya pendidikan gratis ini.',
      
        },
    }
]