module.exports = [
    {
        cn:{
            time:'活动时间：2019.7.1 -- 2019.12.31',
            johnNow:'立即加入',
            gits:'立即加入，赢取丰厚奖品',
            plan:'达成目标，即刻赢取奖品',
            unit:'(单位：标准手)',
            active:'在活动期间达成目标手数',
            obj:'活动对象',
            IB:'凡CPT Markets旗下介绍服务经纪商（IB）均可参加此活动',
            mail:'邮件报名',
            send:'凡CPT Markets旗下介绍服务经纪商，发送邮件至',
            name:'报名参加本计划',
            ruler:'活动规则',
            rules1:'1. 此忠诚计划适用于所有真实账户类型。',
            rules2:'2. 凡CPT Markets旗下介绍服务经纪商，发送邮件至cs@cptmarkets.com报名参加本计划，活动时间从2019年7月1日持续至2019年12月31日。',
            rules3:'3. 此忠诚计划不与其他活动重复，如已参与其他活动的IB，需编辑邮件发送至cs@cptmarkets.com申请放弃已参与活动，方可参与本计划。',
            rules4:'4. 凡CPT Markets介绍服务经纪商（IB），完成一定手数后，即可编辑邮件发送至cs@cptmarkets.com申请领取该档奖品。经审核达标后，实物奖品将在客户确认领取后15个工作日内寄出，旅游等虚拟奖品，客服将在15个工作日内联系获奖IB沟通相关事宜，确认领取此奖品后，该账户可兑换交易手数清零。IB可在活动时间内重复参与此活动。',
            rules5:'5. 在活动结束后，我们将在5个工作日内以邮件的形式告知参加本次活动的介绍服务经纪商（IB）的获奖情况。若已达成了多个奖品目标，则默认领取最近或最高水平对应的奖品。若在28天内无法联系到IB或IB未作出回应，奖品将被取消。',
            rules6:'6. 参加本次活动的介绍服务经纪商（IB）的交易手数仅统计其直属的交易账户。',
            rules7:'7. CPT Markets保留更改此计划的条款和条件的权利，并有可能根据实际情况对奖品进行调整，包括奖品的颜色及型号。',
            rules8:'8. 活动期间，CPT Markets有权在客户违反活动规则的情况下取消客户参与资格。',
            rules9:'9. 违反CPT Markets交易流动性指南或其他恶意交易的交易量将不计入活动手数。',
            rules10:'10. 合作伙伴接受奖品即自动明确同意并允许CPT Markets使用其照片、名字、联系信息和奖励详情供 CPT Markets营销目的所用。合作伙伴拒绝参加任何营销/宣传视频、摄影和/或其他由CPT Markets安排的宣传活动可能会导致取消奖品且在此情况下合作伙伴有义务将奖品退回至CPT Markets。',
            rules11:'11. CPT Markets保留对此次活动的最终解释权。',
            all:'本活动最终解释权归CPTMarkets所有',

        },
        en:{
            time:'1st July, 2019 - 31st December, 2019',
            johnNow:'Join Now',
            gits:'Join now to get your prize!',
            plan:'Win the prize when you achieve the goal!',
            unit:'(Std Lot)',
            active:'When the required transaction volume is done, the prize will be yours!',
            obj:'Participant',
            IB:'All CPT Markets Introducing Brokers',
            mail:'Apply by Email',
            send:'All CPT Markets Introducing Brokers can send email to ',
            name:'to apply for this loyalty program.',
            ruler:'Terms and Conditions',
            rules1:'1.The Loyalty Program is adapted for all real account types.',
            rules2:'2.All CPT Markets introducing broker can send email to cs@cptmarkets.com to apply for this program. The duration of this program is from 1st July, 2019 to 31st December, 2019.',
            rules3:'3.IB can not participate in this Loyalty Program and other promotions at the same time. IB who is participating in other promotion should send email to cs@cptmarkets.com to waive the promotion participating and to apply for this program.',
            rules4:'4.All CPT Markets IB participated in this program can send email to cs@cptmarkets.com to claim the prize after finishing the required transaction volume. After auditing, the prize will be delivered within 15 business days when confirmed. Prize like European Study Tour, our CS will contact the IB to communicate the related issue. After confirmed, the convertible volume will be cleared. IB can re-participate in this program within program duration.',
            rules5:'5.CPT Markets will inform all the IB participated the awards by email within 5 business days after the end of Loyalty Program. If more than one prize goal has been achieved, the nearest or highest prize will be awarded by default. If IB cannot be reached within 28 days or if the IB does not respond, the prize will be cancelled.',
            rules6:'6.Only the transaction volume of the direct trading accounts under the name of the IB participating in this program counted.',
            rules7:'7.CPT Markets reserves the rights to modify the Terms and Conditions of this program and may adjust the prizes according to the actual situation which includes the color and model.',
            rules8:'8.During the program, CPT Markets reserves the rights to cancel the customer’s participation when breaking the terms and conditions.',
            rules9:'9.The transaction volume will not be counted when customers violate the “CPT Markets Liquidity Guidelines”or make other malicious transactions.',
            rules10:'10.The acceptance of the prize by the IB automatically and expressly allows CPT Markets to use its photo, name, contact information and rewards details for marketing purposes. When refusing to participate in any marketing/promotional activities like video, photography arranged by CPT Markets may result in the cancellation of the prize and in this case, the IB is obliged to return the prize to CPT Markets.',
            rules11:'11.CPT Markets reserves all rights for final explanation.',
            all:'CPTMarkets reserves the right to interpret this activity',
        },
        tc:{
            time:'活動時間：2019.7.1 -- 2019.12.31',
            johnNow:'立即加入',
            gits:'立即加入，贏取豐厚獎品',
            plan:'達成目標，即刻贏取獎品',
            unit:'(單位：標準手)',
            active:'在活動期間達成目標手數',
            obj:'活動對象',
            IB:'凡CPT Markets旗下介紹服務經紀商（IB）均可參加此活動',
            mail:'郵件報名',
            send:'凡CPT Markets旗下介紹服務經紀商，發送郵件至',
            name:'報名參加本計劃',
            ruler:'活動規則',
            rules1:'1. 此忠誠計劃適用於所有真實賬戶類型。',
            rules2:'2. 凡CPT Markets旗下介紹服務經紀商，發送郵件至cs@cptmarkets.com報名參加本計劃，活動時間從2019年7月1日持續至2019年12月31日。',
            rules3:'3. 此忠誠計劃不與其他活動重復，如已參與其他活動的IB，需編輯郵件發送至cs@cptmarkets.com申請放棄已參與活動，方可參與本計劃。',
            rules4:'4. 凡CPT Markets介紹服務經紀商（IB），完成壹定手數後，即可編輯郵件發送至cs@cptmarkets.com申請領取該檔獎品。經審核達標後，實物獎品將在客戶確認領取後15個工作日內寄出，旅遊等虛擬獎品，客服將在15個工作日內聯系獲獎IB溝通相關事宜，確認領取此獎品後，該賬戶可兌換交易手數清零。IB可在活動時間內重復參與此活動。',
            rules5:'5. 在活動結束後，我們將在5個工作日內以郵件的形式告知參加本次活動的介紹服務經紀商（IB）的獲獎情況。若已達成了多個獎品目標，則默認領取最近或最高水平對應的獎品。若在28天內無法聯系到IB或IB未作出回應，獎品將被取消。',
            rules6:'6. 參加本次活動的介紹服務經紀商（IB）的交易手數僅統計其直屬的交易賬戶。',
            rules7:'7. CPT Markets保留更改此計劃的條款和條件的權利，並有可能根據實際情況對獎品進行調整，包括獎品的顏色及型號。',
            rules8:'8. 活動期間，CPT Markets有權在客戶違反活動規則的情況下取消客戶參與資格。',
            rules9:'9. 違反CPT Markets交易流動性指南或其他惡意交易的交易量將不計入活動手數。',
            rules10:'10. 合作夥伴接受獎品即自動明確同意並允許CPT Markets使用其照片、名字、聯系信息和獎勵詳情供 CPT Markets營銷目的所用。合作夥伴拒絕參加任何營銷/宣傳視頻、攝影和/或其他由CPT Markets安排的宣傳活動可能會導致取消獎品且在此情況下合作夥伴有義務將獎品退回至CPT Markets。',
            rules11:'11. CPT Markets保留對此次活動的最終解釋權。',
            all:'本活動最終解釋權歸CPTMarkets所有',
        },
    }
]