module.exports = [
    {
        en:{
            college:'CPT Markets Financial College',
            wisdom:'Wisdom in Trade    Road to Wealth',
            crawl:'Learn to crawl before you walk',
            course:'Take CPT education course before you Profit',
            apply:'Apply Now',
            FirstName:'First Name',
            LastName:'Last Name',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Phone Number',
            Email:'Email',
            register:'Register Now',
            education:'Forex Beginner Education',
            new:'',
            beginner:'Forex Beginners',
            are:'are those who are mostly like to loss. How to ',
            loss:'avoid loss',
            key:'is the key point for most Forex learners.Thus CPT Markets here with the most experienced Forex analysts help you to',
            profit:'Profit',
            learn:'Register Now',
            center:'Video Center',
            uploading:'CPT Markets is uploading education videos to the major video platform. Either you want to find serious material or fun stuff, CPT Markets offers these videos all for Free!',
            gathering:'Gathering the most experienced',
            over:'analysts from all over the world CPT',
            success:'Markets’ elite team is only for your success.',
           
        },
        cn:{
            college:'CPT Markets 金融学院',
            wisdom:'通往财富的智慧之路',
            crawl:'专业资深分析师',
            course:'量身定制教育资源',
            apply:'个人信息',
            FirstName:'姓',
            LastName:'名',
            Indonesia:'印度尼西亚',
            Vietnam:'越南',
            Thailand:'泰国',
            Singapore:'新加坡',
            Malaysia:'马来西亚',
            Philippines:'菲律宾',
            Cambodia:'柬埔寨',
            Burma:'缅甸',
            Laos:'老挝',
            Brunei:'文莱',
            Timor:'东帝汶',
            phone:'手机号码',
            Email:'电子邮箱',
            register:'立即注册',
            education:'外汇课堂',
            new:'初步踏入外汇世界的',
            beginner:'新手',
            are:'往往都是最容易亏损的。学会如何',
            loss:'避免亏损',
            key:'是新手入门外汇的重点。因此CPT Markets资深专业分析师团队竭尽全力提供丰富多元的教育资源，助力外汇菜鸟交易',
            profit:'盈利之旅',
            learn:'立即了解',
            center:'视频中心',
            uploading:'CPT Markets专业投资教学视频，关注CPT Markets视频发布网站。无论是专业知识或是趣味外汇新闻，在CPT Markets您都能获得！',
            gathering:'强大的',
            over:'分析师团体',
            success:'快来认识他们',
      
        },
        vn:{
            college:'Học viện tài chính CPT Markets',
            wisdom:'Con đường trí tuệ mang đến lợi nhuận',
            crawl:'Đội ngũ chuyên gia phân tích giàu kinh nghiệm',
            course:'Tài liệu giáo dục phù hợp và chuyên sâu',
            apply:'Thông tin cá nhân',
            FirstName:'Tên',
            LastName:'Họ',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Số điện thoại',
            Email:'Email',
            register:'Đăng ký ngay',
            education:'Lớp học Forex',
            new:'',
            beginner:'Những nhà đầu tư mới bắt đầu',
            are:'bước vào thị trường forex thường dễ gặp thất bại nhất. ',
            loss:'Học cách đầu tư',
            key:'là trọng tâm mà các nhà đầu tư forex cần hướng đến.Do đó, đội ngũ chuyên gia phân tích của CPT Markets đã nỗ lực hết sức để cung cấp tài liệu giáo dục phong phú và đa dạng, giúp cho hành trình đầu tư forex của các tân binh có thêm nhiều ',
            profit:'lợi nhuận',
            learn:'Tìm hiểu ngay',
            center:'Videos',
            uploading:'CPT Markets - nơi đăng tải video giảng dạy đầu tư chuyên nghiệp. Thường xuyên theo dõi trang web đăng tải video, bất luận là kiến thức chuyên ngành hay tin tức Forex thú vị, bạn đều có thể tìm thấy tại CPT Markets.',
            gathering:'Nhóm chuyên gia phân tích vô cùng',
            over:'chuyên nghiệp.',
            success:'Làm quen và học hỏi ngay bây giờ!',
      
        },
        in:{
            college:'Pendidikan Keuangan CPT Markets',
            wisdom:'Kebijaksanaan di Perdagangan, Jalan Menuju Kekayaan',
            crawl:'Belajar merangkak sebelum bisa berjalan',
            course:'Ambil pendidikan CPT sebelum anda melakukan trading',
            apply:'Daftar Sekarang',
            FirstName:'Nama depan',
            LastName:'Nama belakang',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Nomor telepon',
            Email:'Email',
            register:'Daftar sekarang',
            education:'Pendidikan Forex untuk pemula',
            new:'',
            beginner:'Para pemula Forex',
            are:'mereka adalah yang kemungkinan besar akan rugi.Cara ',
            loss:'menghindari kerugian',
            key:'adalah kunci utama bagi sebagian besar pelajar forex.CPT Markets disini dengan analisa Forex paling berpengalaman untuk',
            profit:'membantu anda untung',
            learn:'Daftar sekarang',
            center:'Pusat Video',
            uploading:'CPT Markets mengunggah video pendidikan ke platform video ternama seputar dunia. Entah anda ingin mempelajari materi serius atau hal-hal lain yang menyenangkan, CPT Markets menawarkan semua video ini secara gratis.',
            gathering:'Tim analisis yang berpengalaman.Temui',
            over:'mereka secepatnya',
            success:'',
      
        },
    }
]