module.exports = [
    {
        en:{
            welcome:'Welcome Bonus',
            date:'1st Sep. 2019 - 30th Sep. 2019',
            register:'Register now!',
            up:'Up to',
            best:'Best Deposit Bonus',
            information:'Personal Information',
            FirstName:'First Name',
            LastName:'Last Name',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Phone Number',
            Email:'Email',
            read:'I\'ve read and accept the',
            terms:'Terms & Conditions',
            registernow:'Register now',
            already:'Already registered ?',
            login:'Login now!',
            claim:'How to claim bonus?',
            regist:'Register',
            deposit:'Deposit',
            trade:'Trade',
            four:'Bonus',
            valid:'Valid deposit: ',
            minimum:'Minimum transaction volume: ',
            lots:'lots',
            bonus:'Bonus',
            newly:'Newly register customers?',
            get:'Then you can get',
            additional:'additional bonus!',
            conditions:'Terms and Conditions',
            all:'1. All CPT Markets real retail USD accounts can apply for this promotion by sending email to cs@cptmarkets.com for registration after the deposit from 1st September, 2019 to 30th September, 2019.',
            retail:'2. All registered CPT Markets real retail USD accounts can claim the corresponding bonus after the required transaction volume is done before 31st December, 2019.',
            customers:'3. When the “valid deposit” of all newly registered retail customers during the registration period is greater than or equal to $2,000, an additional $99 welcome bonus will be awarded to customer’s account after the required transaction volume is done.',
            calculated:'4. The “valid deposit” is calculated based on the total amount of deposits from 1st September , 2019 to the date of registration via email.',
            account:'5. The US cent account cannot participate in this promotion.',
            promotion:'6. This promotion is only available to customers of Southeast Asia countries and regions. Each account ID can only be used once and is not allowed to participate in other promotions at the same time.',
            detects:'7. If CPT Markets detects that the customer has abused the terms of this promotion, CPT Markets reserves the right to withdraw the trading bonus or terminate the customer access to the services provided by CPT Markets.',
            volume:'8. The transaction volume will not be counted when customers violate the “CPT Markets Liquidity Guidelines”or make other malicious transactions.',
            reserves:'9. CPT Markets reserves all rights for final explanation.',
        },
        cn:{
            welcome:'迎新赠金',
            date:'2019年9月1日-2019年9月30日',
            register:'立即领取',
            up:'高达',
            best:'9月迎新赠金',
            information:'个人信息',
            FirstName:'姓',
            LastName:'名',
            Indonesia:'印度尼西亚',
            Vietnam:'越南',
            Thailand:'泰国',
            Singapore:'新加坡',
            Malaysia:'马来西亚',
            Philippines:'菲律宾',
            Cambodia:'柬埔寨',
            Burma:'缅甸',
            Laos:'老挝',
            Brunei:'文莱',
            Timor:'东帝汶',
            phone:'手机号码',
            Email:'电子邮箱',
            read:'我已阅读并同意此',
            terms:'条款',
            registernow:'立即注册',
            already:'已经注册？',
            login:'立即登录！',
            claim:'如何领取赠金？',
            regist:'注册',
            deposit:'入金',
            trade:'交易',
            four:'赠金',
            valid:'有效入金：',
            minimum:'最低入金要求:',
            lots:'手',
            bonus:'赠金',
            newly:'新注册客户？',
            get:'那您还可领取 ',
            additional:' 额外赠金！',
            conditions:'条款与规则',
            all:'1、 所有CPT Markets真实零售美元账户可在2019年9月1日至2019年9月30日期间入金后发送邮件至cs@cptmarkets、com报名参加此活动。',
            retail:'2、 活动时间内在CPT Markets所有真实零售美元账户可按照其赠金金额，在2019年12月31日前完成要求的交易手数后即可领取相应赠金。',
            customers:'3、 活动报名期间内的所有新注册零售用户“有效入金金额”大于等于$2,000时， 在完成相应交易手数要求后，还可额外获得$99欢迎赠金。',
            calculated:'4、 有效入金金额按照自2019年9月1日起至邮件报名前所有入金总额计算。',
            account:'5、 美分账户不能参加此活动。',
            promotion:'6、 此活动仅限CPT Markets东南亚国家及地区用户参加，每个账户ID只可参加一次，且不与其他活动重复。',
            detects:'7、 若客户滥用此活动条款，一经发现，CPT Markets保留撤销活动奖金或终止客户访问CPT Markets提供所有服务的权利。',
            volume:'8、 违反CPT Markets交易流动性指南或其他恶意交易的交易量将不计入活动手数。',
            reserves:'9、 此活动最终解释权归CPT Markets所有。',
        },
        vn:{
            welcome:'Phần thưởng chào mừng',
            date:'1 tháng 9 năm 2019 đến 30 tháng 9 năm 2019',
            register:'Đăng ký ngay!',
            up:'Lên đến',
            best:'Phần thường gửi tiền lớn nhất',
            information:'Thông tin cá nhân',
            FirstName:'Tên',
            LastName:'Họ',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Số điện thoại',
            Email:'Email',
            read:'Tôi đã đọc và đồng ý với',
            terms:'Điều khoản sử dụng',
            registernow:'Đăng ký ngay!',
            already:'Đã đăng ký?',
            login:'Đăng nhập ngay！',
            claim:'Các bước để nhận thưởng',
            regist:'Đăng ký',
            deposit:'Nạp tiền',
            trade:'Giao dịch',
            four:'Nhận thưởng',
            valid:'Tiền nạp có hiệu lực: ',
            minimum:'Giao dịch lot thấp nhất: ',
            lots:'lots',
            bonus:'Phần thưởng',
            newly:'Tài khoản đăng ký mới?',
            get:'Có thể nhận thêm',
            additional:'tiền thưởng',
            conditions:'Điều kiện và điều khoản',
            all:'1. Tất cả tài khoản USD cá nhân thực của CPT Markets có thể tham gia sự kiện này bằng cách đăng ký thông qua email cs@cptmarkets.com từ 1 tháng 9 năm 2019 đến 30 tháng 9 năm 2019 sau khi nạp tiền.',
            retail:'2. Tất cả tài khoản USD cá nhân thực của CPT Markets trong thời gian diễn ra sự kiện có thể nhận được số tiền thưởng tương ứng sau khi hoàn thành mức giao dịch theo yêu cầu trước ngày 31 tháng 12 năm 2019.',
            customers:'3. Tất cả tài khoản cá nhân đăng ký mới trong thời gian diễn ra sự kiện có “ Mức tiền nạp có hiệu lực“ lớn hơn hoặc bằng 2000$, sau đó hoàn thành giao dịch theo yêu cầu tương ứng sẽ nhận thêm 99$ tiền thưởng.',
            calculated:'4. Mức tiền nạp có hiệu lực được tính dựa trên tổng số tiền nạp từ ngày 1 tháng 9 năm 2019 đến thời điểm đăng ký qua email.',
            account:'5. Tài khoản cent Mỹ không được tham gia sự kiện này.',
            promotion:'6. Sự kiện này chỉ dành cho tài khoản CPT Markets các quốc gia và khu vực Đông Nam Á. Mỗi ID tài khoản chỉ được sử dụng một lần và không được tham gia đồng thời các sự kiện khác.',
            detects:'7. Nếu tài khoản vi phạm các điều khoản, CPT Markets có quyền hủy phần thưởng hoặc chấm dứt quyền truy cập của khách hàng vào tất cả các dịch vụ do CPT Markets cung cấp.',
            volume:'8. Mức giao dịch vi phạm nguyên tắc thanh khoản hoặc mang tính chất tương tự sẽ không được tính trong sự kiện.',
            reserves:'9. Quyền quyết định cuối cùng thuộc về CPT Markets.',
        },
        in:{
            welcome:'Menyambut Bonus',
            date:'1st Sep. 2019 - 30th Sep. 2019',
            register:'Daftar sekarang!',
            up:'Hingga',
            best:'Menyambut Bonus',
            information:'Informasi Pribadi',
            FirstName:'Nama depan',
            LastName:'Nama belakang',
            Indonesia:'Indonesia',
            Vietnam:'Vietnam',
            Thailand:'Thailand',
            Singapore:'Singapore',
            Malaysia:'Malaysia',
            Philippines:'Philippines',
            Cambodia:'Cambodia',
            Burma:'Burma',
            Laos:'Laos',
            Brunei:'Brunei',
            Timor:'Timor-Leste',
            phone:'Nomor telepon',
            Email:'Email',
            read:'Saya sudah membaca dan menerima',
            terms:'syarat dan ketentuan.',
            registernow:'Daftar sekarang',
            already:'Sudah terdaftar?',
            login:'Log in sekarang!',
            claim:'Bagaimana cara klaim bonus?',
            regist:'Daftar',
            deposit:'Deposit',
            trade:'Trade',
            four:'Bonus',
            valid:'Setoran Valid: ',
            minimum:'Volume transaksi minimum: ',
            lots:'lots',
            bonus:'Bonus',
            newly:'Baru terdaftar?',
            get:'Maka Anda bisa mendapatkan bonus tambahan',
            additional:'',
            conditions:'Syarat dan ketentuan',
            all:'1. Semua akun CPT Markets real retail USD dapat mengajukan permohonan untuk promosi ini dengan mengirim email ke cs@cptmarkets.com untuk pendaftaran setelah deposit mulai dari 1 September 2019 hingga 30 September 2019.',
            retail:'2. Semua akun CPT Markets real retail USD terdaftar dapat mengklaim bonus yang sesuai setelah volume transaksi yang diperlukan sebelum tanggal 31 Desember 2019.',
            customers:'3. Ketika "setoran valid" dari semua pelanggan ritel yang baru terdaftar selama periode registrasi lebih besar atau sama dengan $ 2.000, bonus sambutan $ 99 tambahan akan diberikan ke akun pelanggan setelah volume transaksi yang diperlukan.',
            calculated:'4. “Setoran valid” dihitung berdasarkan jumlah total setoran mulai 1 September 2019 hingga tanggal pendaftaran melalui email.',
            account:'5. Akun US sen tidak dapat berpartisipasi dalam promosi ini.',
            promotion:'6. Promosi ini hanya tersedia untuk pelanggan di negara dan wilayah Asia Tenggara. Setiap ID akun hanya dapat digunakan satu kali dan tidak diizinkan untuk berpartisipasi dalam promosi lainnya secara bersamaan.',
            detects:'7. Jika CPT Markets mendeteksi bahwa pelanggan telah menyalahgunakan ketentuan promosi ini, CPT Markets berhak untuk menarik bonus perdagangan atau menghentikan akses pelanggan ke layanan yang disediakan oleh CPT Markets.',
            volume:'8. Volume transaksi tidak akan dihitung jika pelanggan melanggar "Pedoman Likuiditas Pasar CPT" atau melakukan transaksi jahat lainnya.',
            reserves:'9. CPT Markets memiliki semua hak untuk penjelasan akhir.',
        },
    }
]